export class ManifestError extends Error {}
export type Category = "managed" | "seeded" | "generated" | "hybrid";
export type Format = "markdown" | "shell" | "json" | "javascript";
export interface ManifestEntry {
	path: string;
	category: Category;
	format?: Format;
	owned_keys?: string[];
}
/** A path written by a prior pack version that should no longer exist in consumer repos. */
export interface DeprecatedPath {
	path: string;
	since_version: string;
	reason: string;
}
/**
 * A directory root that the scaffold manages.
 * strict=true: closed set — flag any file not in the manifest.
 * strict=false: open for user growth — never flag unexpected files here.
 */
export interface ManagedRoot {
	root: string;
	strict: boolean;
}
export interface Manifest {
	files: ManifestEntry[];
	canonical_paths: string[];
	lookalike_ignore: string[];
	/** Paths that prior pack versions seeded/managed but are now obsolete. `reconcile` surfaces these. */
	deprecated_paths: DeprecatedPath[];
	/** Per-root strictness policy. Strict roots flag extra files; open roots allow user growth. */
	managed_roots: ManagedRoot[];
	/** Glob patterns for files generated by hooks (e.g. showcase companions). Excluded from orphan detection. */
	generated_patterns: string[];
}
export function isManifestOrKeepfile(path: string, manifestPaths: Set<string>): boolean {
	if (manifestPaths.has(path)) return true;
	if (path.endsWith("/.gitkeep")) {
		return manifestPaths.has(path.slice(0, -".gitkeep".length) + ".keep");
	}
	if (path.endsWith("/.keep")) {
		return manifestPaths.has(path.slice(0, -".keep".length) + ".gitkeep");
	}
	return false;
}

const CATS = new Set<Category>(["managed", "seeded", "generated", "hybrid"]);
const FMTS = new Set<Format>(["markdown", "shell", "json", "javascript"]);
export function parseManifest(raw: string): Manifest {
	const o = JSON.parse(raw) as {
		files?: unknown;
		canonical_paths?: unknown;
		lookalike_ignore?: unknown;
		deprecated_paths?: unknown;
		managed_roots?: unknown;
		generated_patterns?: unknown;
	};
	if (!Array.isArray(o.files)) throw new ManifestError("files: array required");
	const out: ManifestEntry[] = [];
	for (const e of o.files as Record<string, unknown>[]) {
		if (typeof e.path !== "string") throw new ManifestError("entry.path: string required");
		if (!CATS.has(e.category as Category))
			throw new ManifestError(`entry.category invalid: ${e.category}`);
		if (e.category === "hybrid") {
			if (!FMTS.has(e.format as Format))
				throw new ManifestError(`hybrid entry missing/invalid format: ${e.path}`);
		}
		const owned_keys: string[] | undefined = Array.isArray(e.owned_keys)
			? (e.owned_keys as unknown[]).filter((k): k is string => typeof k === "string")
			: undefined;
		out.push({
			path: e.path,
			category: e.category as Category,
			format: e.format as Format | undefined,
			owned_keys,
		});
	}
	const canonical_paths: string[] = Array.isArray(o.canonical_paths)
		? (o.canonical_paths as unknown[]).filter((p): p is string => typeof p === "string")
		: [];
	const lookalike_ignore: string[] = Array.isArray(o.lookalike_ignore)
		? (o.lookalike_ignore as unknown[]).filter((p): p is string => typeof p === "string")
		: [];
	const deprecated_paths: DeprecatedPath[] = [];
	if (Array.isArray(o.deprecated_paths)) {
		for (const d of o.deprecated_paths as Record<string, unknown>[]) {
			if (typeof d.path !== "string")
				throw new ManifestError("deprecated_paths entry missing path");
			if (typeof d.since_version !== "string")
				throw new ManifestError(`deprecated_paths[${d.path}]: since_version required`);
			if (typeof d.reason !== "string")
				throw new ManifestError(`deprecated_paths[${d.path}]: reason required`);
			deprecated_paths.push({ path: d.path, since_version: d.since_version, reason: d.reason });
		}
	}
	const managed_roots: ManagedRoot[] = [];
	if (Array.isArray(o.managed_roots)) {
		for (const r of o.managed_roots as Record<string, unknown>[]) {
			if (typeof r.root !== "string") throw new ManifestError("managed_roots entry missing root");
			if (typeof r.strict !== "boolean")
				throw new ManifestError(`managed_roots[${r.root}]: strict (boolean) required`);
			managed_roots.push({ root: r.root, strict: r.strict });
		}
	}
	const generated_patterns: string[] = Array.isArray(o.generated_patterns)
		? (o.generated_patterns as unknown[]).filter((p): p is string => typeof p === "string")
		: [];
	return {
		files: out,
		canonical_paths,
		lookalike_ignore,
		deprecated_paths,
		managed_roots,
		generated_patterns,
	};
}
