/**
 * `runConsumerVerify` — the A2 verify-gate runner (PRD #407 / issue #410).
 *
 * Detects the consumer's verify command (prefer an explicit `verify` /
 * `typecheck` script, else `tsc --noEmit`, else `build`), runs it, and
 * returns `{ ok, errors, scaffoldErrors, consumerErrors }` parsed from the
 * tsc-style output. Pure orchestration behind a simple interface so
 * mutating commands can gate their clean / converged / "no action required"
 * verdict on a real green tree and tests can stub the subprocess.
 *
 * **The contract:** any command that mutated the tree (`audit --fix`,
 * `heal`, `upgrade` post-apply, `sync` when it wrote) must call this before
 * emitting a success verdict. `ok === false` ⇒ the command surfaces the
 * offending errors and exits non-zero — never prints "clean."
 *
 * **Scaffold-vs-consumer split.** Pre-existing consumer errors that
 * claude-ds did not touch must not block the success verdict (the risk
 * noted in PRD #407): we partition errors by whether they live in a file
 * claude-ds owns or just touched. Scaffold errors block (`ok = false`);
 * consumer errors are reported as warnings via `consumerErrors` so the
 * caller can surface them without failing.
 *
 *  - **scaffold** = path matches `managedFiles` (exact pack-managed paths),
 *    OR sits under any `managedRoots` prefix (default: `design-system/`),
 *    OR is in the optional `touchedFiles` set (paths claude-ds wrote
 *    this run).
 *  - **consumer** = everything else.
 *
 * Errors with no file location (TS plumbing errors, "Cannot find module
 * 'tsconfig.json'") count as scaffold by default so an environment
 * failure of the verify command itself is never silently warned-on.
 */
import { spawn } from "node:child_process";
import { readFile, stat } from "node:fs/promises";
import { join } from "node:path";
import { detectPackageManager } from "./package-manager.js";

/** Parsed entry from `tsc --noEmit` (or compatible) output. */
export interface VerifyError {
	/** Path relative to the verify command's cwd (matches `cwd` arg). */
	file: string;
	line: number;
	col: number;
	/** TS error code like `TS2304`. Empty string for non-tsc shapes. */
	code: string;
	message: string;
	/** Raw line for debugging / display. */
	raw: string;
}

/** Result of the consumer verify run. */
export interface VerifyResult {
	/**
	 * `true` ⇒ no scaffold-caused errors. Pre-existing consumer errors do
	 * not flip this to false (warn-only — see module header). The verify
	 * subprocess exiting non-zero with no parseable errors counts as a
	 * scaffold error (env failure of the gate itself).
	 */
	ok: boolean;
	/** The resolved verify command label (e.g. `"npm run verify"`, `"npx tsc --noEmit"`). */
	command: string;
	/** Subprocess exit code. */
	exitCode: number;
	/** Every error parsed from the run. */
	errors: VerifyError[];
	/**
	 * Errors in claude-ds-owned files: in `managedFiles`, under a `managedRoots`
	 * prefix, or in `touchedFiles` — minus the hand-verify carve-out below. A
	 * claude-ds defect; blocks the green verdict. Includes errors in `@generated`
	 * showcases: the header forbids editing and regeneration is deterministic, so
	 * these route to a claude-ds-defect verdict, never to hand-verify (ADR-0030).
	 */
	scaffoldErrors: VerifyError[];
	/**
	 * Errors in consumer-authored JSX-bearing showcase/example companions (ADR-0026
	 * hand-verify territory, narrowed by ADR-0030): a `.showcase.tsx`/`.stories.tsx`
	 * in scaffold territory that lacks the `@generated by claude-ds` header. claude-ds
	 * can't regenerate JSX-bearing examples, so the remedy is the operator's eye —
	 * not a loop step. Warn-only: does not flip `ok` (the consumer owns these), but
	 * surfaced as its own bucket so heal can name a "hand-verify only" partial fixed
	 * point instead of looping.
	 */
	handVerifyErrors: VerifyError[];
	/** Errors whose file is none of the above (pre-existing consumer errors). */
	consumerErrors: VerifyError[];
	/** `true` ⇒ verify command timed out. */
	timedOut: boolean;
	/** Pre-existing or environmental note (e.g. "no verify command detected"). */
	reason?: string;
	/**
	 * Truncated tail of the combined stdout/stderr, populated only when the
	 * run failed (timeout or non-zero exit). Carries the raw failing output
	 * so a non-tsc failure (Biome, eslint, vitest) is diagnosable from the
	 * report alone instead of being dropped on the floor (issue #494).
	 */
	outputTail?: string;
}

/** Injectable subprocess executor — tests stub this to assert no real spawn. */
export type ExecFn = (
	cmd: string,
	args: string[],
	opts: { cwd: string; timeoutMs: number },
) => Promise<{ exitCode: number; stdout: string; stderr: string; timedOut: boolean }>;

export interface RunConsumerVerifyOpts {
	/**
	 * Paths (relative to cwd) claude-ds wrote during this run. Errors in any
	 * of these count as scaffold errors and block the green verdict.
	 */
	touchedFiles?: Set<string>;
	/**
	 * Pack-managed paths (relative to cwd) — typically `ctx.manifest.files`.
	 * Errors in any of these count as scaffold errors.
	 */
	managedFiles?: Set<string>;
	/**
	 * Directory prefixes (with trailing slash). Errors under any of these
	 * count as scaffold errors. Defaults to `["design-system/"]` — the
	 * canonical scaffold root.
	 */
	managedRoots?: string[];
	/**
	 * Override the resolved verify command. Object form so tests can pin
	 * exactly what the subprocess runs.
	 */
	command?: { cmd: string; args: string[]; label: string };
	/** Override the subprocess executor (test seam). */
	exec?: ExecFn;
	/**
	 * Subprocess timeout. Resolution order: this option → the
	 * `CLAUDE_DS_VERIFY_TIMEOUT` env var (whole seconds) → `DEFAULT_TIMEOUT_MS`.
	 */
	timeoutMs?: number;
}

/**
 * Default verify timeout. 300s, not 60s (issue #497): a real consumer's full
 * verify chain (`typecheck && lint && test`) routinely exceeds a minute on a
 * warm run — vitest's cold import alone can be ~40s — so a 60s ceiling SIGKILLs
 * green suites and heal reports `verify-failed` on a passing tree. 300s is
 * suite-scaled; outliers raise it per-run via `--verify-timeout` (heal) or the
 * `CLAUDE_DS_VERIFY_TIMEOUT` env var.
 */
const DEFAULT_TIMEOUT_MS = 300_000;
/** Env var (whole seconds) overriding the verify timeout when no explicit `timeoutMs` is passed. */
const TIMEOUT_ENV_VAR = "CLAUDE_DS_VERIFY_TIMEOUT";
const DEFAULT_MANAGED_ROOTS = ["design-system/"];
/**
 * Header claude-ds stamps on every showcase it generates. An error in a file
 * carrying it is a claude-ds defect (the header forbids hand-editing), never
 * ADR-0026 hand-verify (ADR-0030). Matched against the file's leading bytes.
 */
const GENERATED_HEADER_PREFIX = "// @generated by claude-ds";
/**
 * Showcase/example companion suffixes — the only scaffold-territory files
 * eligible for the hand-verify carve-out. A type error elsewhere in the
 * scaffold (an atom, a hook) is always claude-ds's, never hand-verify.
 */
const HAND_VERIFY_SUFFIXES = [".showcase.tsx", ".stories.tsx"];
/** Bytes read from the head of a candidate file to detect the `@generated` header. */
const HEADER_PROBE_BYTES = 200;
/** Max chars of raw failing output kept in `outputTail` — the tail, where the failure summary lives. */
const OUTPUT_TAIL_CHARS = 4_000;

/**
 * Detect the consumer's verify command. Tries (in order):
 *   1. `verify` script in package.json
 *   2. `typecheck` script in package.json
 *   3. `tsc --noEmit` when `typescript` is a dep and `tsconfig.json` exists
 *   4. `build` script in package.json
 *
 * Returns `null` when nothing detectable is present — the caller decides
 * whether that is a hard failure or a soft skip.
 */
export async function detectVerifyCommand(
	cwd: string,
): Promise<{ cmd: string; args: string[]; label: string } | null> {
	let pkg: {
		scripts?: Record<string, string>;
		devDependencies?: Record<string, string>;
		dependencies?: Record<string, string>;
	} = {};
	try {
		pkg = JSON.parse(await readFile(join(cwd, "package.json"), "utf8"));
	} catch {
		// No package.json — fall through to the tsc / nothing branches.
	}

	const pm = await detectPackageManager(cwd);
	const runScript = (script: string): { cmd: string; args: string[]; label: string } => {
		if (pm === "yarn") return { cmd: "yarn", args: [script], label: `yarn ${script}` };
		return { cmd: pm, args: ["run", script], label: `${pm} run ${script}` };
	};

	if (pkg.scripts?.verify) return runScript("verify");
	if (pkg.scripts?.typecheck) return runScript("typecheck");

	const hasTsconfig = await exists(join(cwd, "tsconfig.json"));
	const hasTypescript = !!(pkg.devDependencies?.typescript || pkg.dependencies?.typescript);
	if (hasTsconfig && hasTypescript) {
		return { cmd: "npx", args: ["tsc", "--noEmit"], label: "npx tsc --noEmit" };
	}

	if (pkg.scripts?.build) return runScript("build");

	return null;
}

/**
 * Run the consumer verify command and return a structured result.
 *
 * Never throws — environmental failures are folded into the result
 * (`reason` + `exitCode`). The caller decides whether to print, exit
 * non-zero, or roll back.
 */
export async function runConsumerVerify(
	cwd: string,
	opts: RunConsumerVerifyOpts = {},
): Promise<VerifyResult> {
	const command = opts.command ?? (await detectVerifyCommand(cwd));
	if (!command) {
		return {
			ok: true,
			command: "(none)",
			exitCode: 0,
			errors: [],
			scaffoldErrors: [],
			handVerifyErrors: [],
			consumerErrors: [],
			timedOut: false,
			reason: "no verify command detected (no `verify`/`typecheck`/`build` script and no tsc)",
		};
	}

	const exec = opts.exec ?? defaultExec;
	// A non-finite / non-positive explicit timeout (e.g. `heal --verify-timeout abc`
	// → NaN via parseInt, or `0`/`-5`) must not slip through: `NaN ?? x` keeps NaN,
	// and `setTimeout(NaN)` fires immediately → instant SIGKILL of a green suite —
	// the exact `verify-failed`-on-passing-tree regression this gate guards against.
	// Fall back just like a bad env var does (issue #497).
	const explicitTimeoutMs =
		opts.timeoutMs !== undefined && Number.isFinite(opts.timeoutMs) && opts.timeoutMs > 0
			? opts.timeoutMs
			: undefined;
	const timeoutMs = explicitTimeoutMs ?? envTimeoutMs() ?? DEFAULT_TIMEOUT_MS;
	const result = await exec(command.cmd, command.args, { cwd, timeoutMs });

	const errors = parseVerifyErrors(result.stdout + "\n" + result.stderr);
	const { scaffoldErrors, handVerifyErrors, consumerErrors } = await partitionErrors(cwd, errors, {
		touchedFiles: opts.touchedFiles,
		managedFiles: opts.managedFiles,
		managedRoots: opts.managedRoots ?? DEFAULT_MANAGED_ROOTS,
	});

	let ok = scaffoldErrors.length === 0;
	let reason: string | undefined;
	let outputTail: string | undefined;

	if (result.timedOut) {
		// Timeout is distinct from a lint/test failure: a cold consumer (fresh
		// install, no tsc/test cache) can legitimately exceed a limit tuned for
		// warm runs. Label it as such and show the configured limit (issue #494).
		ok = false;
		reason = `${command.label} timed out after ${timeoutMs}ms (exit ${result.exitCode}) — a cold consumer (fresh install, no tsc/test cache) can exceed a limit tuned for warm runs; raise it via heal --verify-timeout <s> or CLAUDE_DS_VERIFY_TIMEOUT (seconds), or warm the cache`;
		outputTail = tailOf(result.stdout, result.stderr);
	} else if (result.exitCode !== 0 && errors.length === 0) {
		// Non-zero exit with no parseable TS errors: an env failure of the gate
		// itself, OR a non-tsc failure (Biome, eslint, vitest) whose output shape
		// the TS parser doesn't recognize. Treat as a scaffold problem so the
		// gate fails loud, and carry the raw output so the failure is diagnosable
		// from the report alone (issue #494).
		ok = false;
		reason = `${command.label} exited ${result.exitCode} with no parseable TS errors (likely a non-tsc failure — Biome/eslint/vitest — or an env failure of the verify command itself); see outputTail`;
		outputTail = tailOf(result.stdout, result.stderr);
	}

	return {
		ok,
		command: command.label,
		exitCode: result.exitCode,
		errors,
		scaffoldErrors,
		handVerifyErrors,
		consumerErrors,
		timedOut: result.timedOut,
		reason,
		...(outputTail !== undefined ? { outputTail } : {}),
	};
}

/**
 * Parse `tsc --noEmit`-style diagnostics from a combined stdout/stderr
 * blob. Matches the canonical line shape
 *   `path/to/file.ts(12,7): error TS2304: Cannot find name 'Foo'.`
 * which `tsc`, `vue-tsc`, and most TS-driven verify scripts emit.
 *
 * Exported so the harness, integration tests, and ad-hoc tooling can
 * reuse the same parser the gate decides on.
 */
export function parseVerifyErrors(raw: string): VerifyError[] {
	const errors: VerifyError[] = [];
	const re = /^([^()\n]+)\((\d+),(\d+)\):\s+error\s+(TS\d+):\s+(.*)$/gm;
	let m: RegExpExecArray | null;
	while ((m = re.exec(raw)) !== null) {
		errors.push({
			file: m[1],
			line: Number(m[2]),
			col: Number(m[3]),
			code: m[4],
			message: m[5].trim(),
			raw: m[0],
		});
	}
	return errors;
}

/**
 * One-line note for hand-verify blockers, or `null` when there are none. Lets
 * every command that runs the gate surface ADR-0026 hand-verify errors with
 * consistent wording — claude-ds's own files are clean, but consumer-authored
 * JSX showcases it can't regenerate still need the operator's eye. `heal` turns
 * this into a named partial fixed point (its own exit code); the other commands
 * note it without blocking, so the blocker is never silently dropped (ADR-0003).
 */
export function handVerifyNote(verify: VerifyResult): string | null {
	const n = verify.handVerifyErrors.length;
	if (n === 0) return null;
	return (
		`${n} hand-verify blocker${n === 1 ? "" : "s"} need your eye — JSX-bearing example(s) you authored ` +
		`that claude-ds can't regenerate (ADR-0026); claude-ds's own files type-check`
	);
}

interface PartitionOpts {
	touchedFiles?: Set<string>;
	managedFiles?: Set<string>;
	managedRoots: string[];
}

async function partitionErrors(
	cwd: string,
	errors: VerifyError[],
	opts: PartitionOpts,
): Promise<{
	scaffoldErrors: VerifyError[];
	handVerifyErrors: VerifyError[];
	consumerErrors: VerifyError[];
}> {
	const scaffoldErrors: VerifyError[] = [];
	const handVerifyErrors: VerifyError[] = [];
	const consumerErrors: VerifyError[] = [];
	// One verdict per file: the 79 Crewops errors concentrated into a handful of
	// showcases, so cache the header probe rather than re-reading a file per error.
	const handVerifyCache = new Map<string, boolean>();
	for (const e of errors) {
		if (!isScaffoldPath(e.file, opts)) {
			consumerErrors.push(e);
			continue;
		}
		// In claude-ds territory: split the consumer-authored JSX showcase
		// (hand-verify) out of the claude-ds defect (scaffold). `@generated`
		// showcases stay scaffold — the header forbids hand-editing (ADR-0030).
		let isHandVerify = handVerifyCache.get(e.file);
		if (isHandVerify === undefined) {
			isHandVerify = await isHandVerifyError(cwd, e.file);
			handVerifyCache.set(e.file, isHandVerify);
		}
		if (isHandVerify) {
			handVerifyErrors.push(e);
		} else {
			scaffoldErrors.push(e);
		}
	}
	return { scaffoldErrors, handVerifyErrors, consumerErrors };
}

/**
 * True iff a scaffold-territory error belongs to ADR-0026 hand-verify: a
 * showcase/example companion the *consumer* authored — `.showcase.tsx`/
 * `.stories.tsx` lacking the `@generated by claude-ds` header. A file claude-ds
 * generated (header present) is never hand-verify: an error in it is a claude-ds
 * defect, since the header forbids editing and regeneration reproduces it
 * deterministically (ADR-0030). An unreadable candidate stays scaffold — we
 * never ask the operator to hand-verify a file we can't confirm they own.
 */
async function isHandVerifyError(cwd: string, file: string): Promise<boolean> {
	const normalized = file.replace(/\\/g, "/").replace(/^\.\//, "");
	if (!HAND_VERIFY_SUFFIXES.some((s) => normalized.endsWith(s))) return false;
	try {
		const fd = await readFile(join(cwd, normalized), "utf8");
		return !fd.slice(0, HEADER_PROBE_BYTES).trimStart().startsWith(GENERATED_HEADER_PREFIX);
	} catch {
		return false;
	}
}

function isScaffoldPath(file: string, opts: PartitionOpts): boolean {
	const normalized = file.replace(/\\/g, "/").replace(/^\.\//, "");
	if (opts.touchedFiles?.has(normalized)) return true;
	if (opts.managedFiles?.has(normalized)) return true;
	for (const root of opts.managedRoots) {
		const prefix = root.endsWith("/") ? root : root + "/";
		if (normalized.startsWith(prefix)) return true;
	}
	return false;
}

/**
 * Last `OUTPUT_TAIL_CHARS` of the combined stdout/stderr, trimmed. Keeps the
 * tail (where the failure summary lives), prefixed with an ellipsis when
 * truncated so the reader knows the head was dropped.
 */
function tailOf(stdout: string, stderr: string): string | undefined {
	const combined = `${stdout}${stderr}`.trim();
	if (combined === "") return undefined;
	if (combined.length <= OUTPUT_TAIL_CHARS) return combined;
	return `…${combined.slice(-OUTPUT_TAIL_CHARS)}`;
}

/**
 * Resolve the `CLAUDE_DS_VERIFY_TIMEOUT` env var (whole seconds) to
 * milliseconds, or `undefined` when unset / not a positive number — so a
 * typo'd value falls back to the default rather than silently disabling the
 * gate with a 0/NaN timeout.
 */
function envTimeoutMs(): number | undefined {
	const raw = process.env[TIMEOUT_ENV_VAR];
	if (raw === undefined || raw.trim() === "") return undefined;
	const seconds = Number(raw);
	if (!Number.isFinite(seconds) || seconds <= 0) return undefined;
	return Math.round(seconds * 1000);
}

async function exists(p: string): Promise<boolean> {
	try {
		await stat(p);
		return true;
	} catch {
		return false;
	}
}

/** Default subprocess executor — spawns the command and captures streams. */
const defaultExec: ExecFn = (cmd, args, { cwd, timeoutMs }) =>
	new Promise((resolve) => {
		const child = spawn(cmd, args, {
			cwd,
			stdio: ["ignore", "pipe", "pipe"],
			// Force non-TTY / no-color so tsc's output is byte-stable for the parser.
			env: { ...process.env, FORCE_COLOR: "0", NO_COLOR: "1", CI: "1" },
		});
		let stdout = "";
		let stderr = "";
		let timedOut = false;
		let settled = false;
		child.stdout.setEncoding("utf8");
		child.stderr.setEncoding("utf8");
		child.stdout.on("data", (chunk) => {
			stdout += chunk;
		});
		child.stderr.on("data", (chunk) => {
			stderr += chunk;
		});

		const timer = setTimeout(() => {
			timedOut = true;
			child.kill("SIGKILL");
		}, timeoutMs);

		const settle = (exitCode: number): void => {
			if (settled) return;
			settled = true;
			clearTimeout(timer);
			resolve({ exitCode, stdout, stderr, timedOut });
		};

		child.on("error", () => settle(127));
		child.on("close", (code, signal) => {
			const exit = code ?? (signal ? 124 : 1);
			settle(exit);
		});
	});
