// @generated by claude-ds — do not edit. Source: Button.tsx meta block.
//
// STALE on purpose: this companion was generated against an older Button that
// accepted `variant` / `size` props. The current Button (Button.tsx) takes only
// `{ label?: string }`, so these attributes no longer typecheck. Because the
// showcase is JSX-bearing it cannot be regenerated (ADR-0026) — `verify` must
// surface these as hand-verify errors, which is the cross-version defect the
// time-travel journey reproduces.
import React from "react";
import { Button } from "./Button";

export default function ButtonShowcase() {
  return (
    <main className="p-8">
      <h1 className="text-2xl font-bold mb-6">Button</h1>
      <section className="mb-10">
        <h2 className="text-xl font-semibold mb-4">Examples</h2>
        <div className="flex flex-wrap items-end gap-3">
          <div className="flex flex-col items-start gap-1">
            <Button label="click" variant="primary" size="lg" />
            <span className="text-xs text-muted-foreground">default</span>
          </div>
        </div>
      </section>
    </main>
  );
}
