import { spawnSync } from "node:child_process";
import { mkdir, mkdtemp, readFile, rm } from "node:fs/promises";
import { copyFileSync, mkdirSync } from "node:fs";
import { tmpdir } from "node:os";
import { join, resolve } from "node:path";
import { afterAll, beforeAll, describe, expect, it } from "vitest";
import { type CompileResult, compileEmitted } from "../../../../tests/helpers/compile-emitted";

/**
 * Compile-what-you-emit (PRD #546, issue #551).
 *
 * The generator integration suite next door asserts the *string content* of the
 * emitted showcase — which is how the Crewops breakage stayed green: those
 * assertions encode the generator's own beliefs back at itself. This suite adds
 * the missing oracle: it compiles the emitted `.showcase.tsx` against the real
 * fixture component, through the fixture's own tsconfig semantics, and asserts
 * the consumer's compiler accepts it.
 *
 * The fixture atom (`compile-what-you-emit/`) combines the five shapes that
 * broke Crewops. The generator's current output against it carries four
 * type-unsafe shapes — one per Crewops defect — that land here as `it.fails`
 * tripwires: each asserts the emitted showcase is free of that defect's
 * diagnostic, and is *expected to fail today*. When a later PRD #546 slice fixes
 * the generator/fixer, the tripwire passes — flipping the `it.fails` red — which
 * is the signal to drop the `.fails`.
 */

const SCRIPT = resolve("packs/next-react/files/scripts/generate-showcase-companion.ts");
const FIXTURE_ROOT = resolve("packs/next-react/tests/fixtures/compile-what-you-emit");
const ATOM_REL = "design-system/atoms/crewops-atom.tsx";
const SHOWCASE_REL = "design-system/atoms/crewops-atom.showcase.tsx";

/** A correct, hand-written showcase — the green baseline the oracle must pass. */
const GOOD_SHOWCASE = [
	`// @generated by claude-ds — do not edit. Source: crewops-atom.tsx meta block.`,
	`import React from "react";`,
	`import { CrewopsAtom } from "./crewops-atom";`,
	``,
	`export default function CrewopsAtomShowcase() {`,
	`  return (`,
	`    <main className="p-8">`,
	`      <CrewopsAtom tone="neutral" invalid={false} />`,
	`      <CrewopsAtom tone="accent" invalid={true} label="Active" />`,
	`    </main>`,
	`  );`,
	`}`,
	``,
].join("\n");

function messagesMatching(result: CompileResult, re: RegExp): string[] {
	return result.messages.filter((m) => re.test(m));
}

describe("compileEmitted harness", () => {
	it("accepts a correct showcase against the real fixture atom", () => {
		const result = compileEmitted([{ path: SHOWCASE_REL, content: GOOD_SHOWCASE }], FIXTURE_ROOT);
		expect(result.hasErrors, result.messages.join("\n")).toBe(false);
	});

	// The helper's own red test: a deliberately broken emission must surface a
	// diagnostic. Without this, a silently-inert oracle would pass everything.
	it("reports diagnostics for a deliberately broken emission", () => {
		const broken = GOOD_SHOWCASE.replace(`tone="neutral"`, `tone="bogus"`);
		const result = compileEmitted([{ path: SHOWCASE_REL, content: broken }], FIXTURE_ROOT);
		expect(result.hasErrors).toBe(true);
		expect(messagesMatching(result, /"bogus"/).length).toBeGreaterThan(0);
	});

	it("reads the fixture's jsx + paths semantics (boolean axis is boolean, not string)", () => {
		const stringBool = GOOD_SHOWCASE.replace(`invalid={false}`, `invalid="false"`);
		const result = compileEmitted([{ path: SHOWCASE_REL, content: stringBool }], FIXTURE_ROOT);
		expect(messagesMatching(result, /not assignable to type 'boolean/).length).toBeGreaterThan(0);
	});
});

describe("generator emits type-correct showcase for the Crewops-shape atom", () => {
	let result: CompileResult;

	beforeAll(async () => {
		// Run the real generator (as it ships) over a copy of the fixture atom,
		// then compile what it emitted against the real component.
		const dir = await mkdtemp(join(tmpdir(), "compile-what-you-emit-"));
		mkdirSync(join(dir, "design-system", "atoms"), { recursive: true });
		copyFileSync(join(FIXTURE_ROOT, ATOM_REL), join(dir, ATOM_REL));
		const r = spawnSync("node", ["--experimental-strip-types", SCRIPT], { cwd: dir, encoding: "utf8" });
		expect(r.status, `${r.stdout}\n${r.stderr}`).toBe(0);
		const emitted = await readFile(join(dir, SHOWCASE_REL), "utf8");
		await rm(dir, { recursive: true, force: true });
		result = compileEmitted([{ path: SHOWCASE_REL, content: emitted }], FIXTURE_ROOT);
	});

	// ── Crewops defect tripwires (one per defect; expected-fail today) ──────────
	// Each asserts the emitted showcase is FREE of the defect's diagnostic.
	// Today the generator emits the defect, the assertion throws, and `it.fails`
	// records the expected failure. A later PRD #546 slice makes the assertion
	// pass — flipping the tripwire red. That red is the prompt to remove `.fails`.

	it.fails("Defect 1 — no sub-element axis attributed to the exported component", () => {
		// Fixer wrote `density` (a markerVariants axis) into a meta example;
		// emitted `<CrewopsAtom density="roomy" />` — `density` is not a prop.
		expect(messagesMatching(result, /Property 'density'/), result.messages.join("\n")).toEqual([]);
	});

	it.fails("Defect 2 — boolean axis not emitted as a string", () => {
		// Emitted `<CrewopsAtom invalid="true" />` — a string where `boolean` is
		// required.
		expect(messagesMatching(result, /not assignable to type 'boolean/), result.messages.join("\n")).toEqual(
			[],
		);
	});

	it.fails("Defect 3 — dark:-leak residue not rendered into an example", () => {
		// Emitted `<CrewopsAtom tone="dark" />` — `dark` leaked from a `dark:`
		// class modifier and is outside the tone axis.
		expect(messagesMatching(result, /"dark"/), result.messages.join("\n")).toEqual([]);
	});

	it.fails("Defect 4 — multi-CVA latent bug masked by populated examples", () => {
		// Populated examples make CVA auto-expansion run; the regex parser spans
		// the cva() boundary into markerVariants, emitting phantom `variants` /
		// `pressed` props on `<CrewopsAtom>`.
		expect(
			messagesMatching(result, /Property '(variants|pressed)'/),
			result.messages.join("\n"),
		).toEqual([]);
	});
});

afterAll(() => {
	// no-op: temp dirs cleaned per-run above.
});
