import { describe, it, expect, beforeEach, afterEach } from "vitest";
import { mkdtemp, mkdir, writeFile, rm, readFile } from "node:fs/promises";
import { join } from "node:path";
import { tmpdir } from "node:os";
import { spawnSync } from "node:child_process";
import { resolve } from "node:path";
import { existsSync } from "node:fs";
import { copyFileSync, mkdirSync } from "node:fs";

const SCRIPT = resolve("packs/next-react/files/scripts/generate-showcase-companion.ts");

const FIXTURE_ATOM = resolve("packs/next-react/tests/fixtures/showcase-companion-atom-meta");
const FIXTURE_CVA = resolve("packs/next-react/tests/fixtures/showcase-companion-cva");
const FIXTURE_REF = resolve("packs/next-react/tests/fixtures/showcase-companion-reference");

async function fresh(): Promise<string> {
  return mkdtemp(join(tmpdir(), "int-gen-showcase-companion-"));
}

/** Copy a fixture source file into a temp dir maintaining relative path. */
function copyFixture(fixtureSrc: string, dest: string, relPath: string): void {
  const destPath = join(dest, relPath);
  mkdirSync(join(dest, relPath.split("/").slice(0, -1).join("/")), { recursive: true });
  copyFileSync(join(fixtureSrc, relPath), destPath);
}

describe("generate-showcase-companion.ts [integration]", () => {
  let dir: string;

  beforeEach(async () => {
    dir = await fresh();
  });

  afterEach(async () => {
    await rm(dir, { recursive: true, force: true });
  });

  // ── atom with explicit examples ────────────────────────────────────────────

  it("emits .showcase.tsx with @generated header for atom with explicit examples", async () => {
    const dsDir = join(dir, "design-system", "atoms");
    await mkdir(dsDir, { recursive: true });
    copyFixture(FIXTURE_ATOM, dir, "design-system/atoms/button.tsx");

    const r = spawnSync("node", ["--experimental-strip-types", SCRIPT], {
      cwd: dir,
      encoding: "utf8",
    });
    expect(r.status).toBe(0);

    const showcasePath = join(dsDir, "button.showcase.tsx");
    expect(existsSync(showcasePath)).toBe(true);

    const content = await readFile(showcasePath, "utf8");
    // @generated header must be present
    expect(content).toMatch(/^\/\/ @generated by claude-ds — do not edit\. Source: button\.tsx meta block\./);
    // Must import the component
    expect(content).toContain('import Button from "./button"');
    // Must render both examples
    expect(content).toContain("default");
    expect(content).toContain("disabled");
    // Props from examples must appear
    expect(content).toContain('label="Click me"');
  });

  it("emits .states.json with __generated marker for atom", async () => {
    const dsDir = join(dir, "design-system", "atoms");
    await mkdir(dsDir, { recursive: true });
    copyFixture(FIXTURE_ATOM, dir, "design-system/atoms/button.tsx");

    spawnSync("node", ["--experimental-strip-types", SCRIPT], {
      cwd: dir,
      encoding: "utf8",
    });

    const statesPath = join(dsDir, "button.states.json");
    expect(existsSync(statesPath)).toBe(true);

    const raw = await readFile(statesPath, "utf8");
    const parsed = JSON.parse(raw);
    // __generated key must be present
    expect(parsed).toHaveProperty("__generated");
    expect(typeof parsed.__generated).toBe("string");
    expect(parsed.__generated).toMatch(/@generated by claude-ds/);
    // states array must list examples
    expect(Array.isArray(parsed.states)).toBe(true);
    expect(parsed.states.length).toBeGreaterThan(0);
  });

  // ── CVA auto-expansion ─────────────────────────────────────────────────────

  it("auto-expands CVA cross-product and excludes skip[] entries", async () => {
    const dsDir = join(dir, "design-system", "atoms");
    await mkdir(dsDir, { recursive: true });
    copyFixture(FIXTURE_CVA, dir, "design-system/atoms/badge.tsx");

    const r = spawnSync("node", ["--experimental-strip-types", SCRIPT], {
      cwd: dir,
      encoding: "utf8",
    });
    expect(r.status).toBe(0);

    const showcasePath = join(dsDir, "badge.showcase.tsx");
    expect(existsSync(showcasePath)).toBe(true);

    const content = await readFile(showcasePath, "utf8");
    // Should contain CVA-expanded examples: size × tone = 3×2 = 6 combos, minus 1 skip = 5
    // Check some expected combos are present
    expect(content).toContain("size=sm_tone=primary");
    expect(content).toContain("size=md_tone=primary");
    expect(content).toContain("size=lg_tone=primary");
    expect(content).toContain("size=sm_tone=danger");
    expect(content).toContain("size=md_tone=danger");
    // Skipped combo must NOT be present
    expect(content).not.toContain("size=lg_tone=danger");
  });

  it("states.json for CVA component contains correct number of states (cross-product minus skip)", async () => {
    const dsDir = join(dir, "design-system", "atoms");
    await mkdir(dsDir, { recursive: true });
    copyFixture(FIXTURE_CVA, dir, "design-system/atoms/badge.tsx");

    spawnSync("node", ["--experimental-strip-types", SCRIPT], {
      cwd: dir,
      encoding: "utf8",
    });

    const raw = await readFile(join(dsDir, "badge.states.json"), "utf8");
    const parsed = JSON.parse(raw);
    // 3 sizes × 2 tones = 6 combos minus 1 skip = 5
    expect(parsed.states).toHaveLength(5);
  });

  // ── reference kind ─────────────────────────────────────────────────────────

  it("emits reference showcase that calls meta.render()", async () => {
    const refDir = join(dir, "design-system", "references");
    await mkdir(refDir, { recursive: true });
    copyFixture(FIXTURE_REF, dir, "design-system/references/tokens-page.tsx");

    const r = spawnSync("node", ["--experimental-strip-types", SCRIPT], {
      cwd: dir,
      encoding: "utf8",
    });
    expect(r.status).toBe(0);

    const showcasePath = join(refDir, "tokens-page.showcase.tsx");
    expect(existsSync(showcasePath)).toBe(true);

    const content = await readFile(showcasePath, "utf8");
    expect(content).toMatch(/^\/\/ @generated by claude-ds/);
    // Must import meta from component
    expect(content).toContain('import { meta } from "./tokens-page"');
    // Must call render()
    expect(content).toContain("meta.render()");
    // Must show the title
    expect(content).toContain("Design Tokens");
  });

  // ── no-meta graceful skip ──────────────────────────────────────────────────

  it("skips components with no meta export and exits 0", async () => {
    const dsDir = join(dir, "design-system", "atoms");
    await mkdir(dsDir, { recursive: true });
    // Component without a meta export
    await writeFile(
      join(dsDir, "plain.tsx"),
      `import React from "react";\nexport function Plain() { return <div />; }\n`
    );

    const r = spawnSync("node", ["--experimental-strip-types", SCRIPT], {
      cwd: dir,
      encoding: "utf8",
    });
    expect(r.status).toBe(0);
    // No showcase generated for it
    expect(existsSync(join(dsDir, "plain.showcase.tsx"))).toBe(false);
    // But GEN-000 warning emitted to stderr
    expect(r.stderr).toMatch(/GEN-000/);
  });

  // ── empty dir graceful ─────────────────────────────────────────────────────

  it("exits 0 when design-system dirs are absent", async () => {
    const r = spawnSync("node", ["--experimental-strip-types", SCRIPT], {
      cwd: dir,
      encoding: "utf8",
    });
    expect(r.status).toBe(0);
  });

  // ── header format ──────────────────────────────────────────────────────────

  it("header in .showcase.tsx includes the source filename", async () => {
    const dsDir = join(dir, "design-system", "atoms");
    await mkdir(dsDir, { recursive: true });
    copyFixture(FIXTURE_ATOM, dir, "design-system/atoms/button.tsx");

    spawnSync("node", ["--experimental-strip-types", SCRIPT], { cwd: dir, encoding: "utf8" });

    const content = await readFile(join(dsDir, "button.showcase.tsx"), "utf8");
    expect(content).toContain("Source: button.tsx meta block.");
  });
});

// ── Integrity check tests (GEN-001 / GEN-002) ────────────────────────────────
// These test the reconform integrity logic by invoking reconform directly.
// We construct minimal consumer projects with .claude-ds.json, pack manifest,
// and pre-seeded generated files.

import { fileURLToPath } from "node:url";
const RECONFORM_SCRIPT = resolve("dist/cli.js");
const PACK_DIR = resolve("packs/next-react");

async function seedIntegrityFixture(dir: string, showcaseContent: string, statesContent: string): Promise<void> {
  // .claude-ds.json
  await writeFile(join(dir, ".claude-ds.json"), JSON.stringify({ pack: "next-react", version: "v0.6.0", mode: "warn" }, null, 2));
  // Minimal design-system/contracts.md and tokens.json to avoid stub warning exit
  await mkdir(join(dir, "design-system", "atoms"), { recursive: true });
  await writeFile(join(dir, "design-system", "contracts.md"), "# Contracts\n" + "x\n".repeat(30));
  await writeFile(join(dir, "design-system", "tokens.json"), JSON.stringify({ color: { a: "#000" } }, null, 2) + "\n".repeat(30));
  // Component source with meta
  await writeFile(
    join(dir, "design-system", "atoms", "btn.tsx"),
    `import React from "react";\nexport function Btn() { return <button />; }\nexport const meta = { kind: "atom", examples: [{ name: "default", props: {} }], skip: [] };\n`
  );
  // Pre-seeded generated companions
  await writeFile(join(dir, "design-system", "atoms", "btn.showcase.tsx"), showcaseContent);
  await writeFile(join(dir, "design-system", "atoms", "btn.states.json"), statesContent);
}

describe("reconform integrity check (GEN-001 / GEN-002)", () => {
  let dir: string;

  beforeEach(async () => {
    dir = await fresh();
  });

  afterEach(async () => {
    await rm(dir, { recursive: true, force: true });
  });

  it("GEN-001: flags missing @generated header in .showcase.tsx", async () => {
    // Showcase without header
    const statesOk = JSON.stringify({ __generated: "@generated by claude-ds — do not edit. Source: btn.tsx meta block.", states: [] }, null, 2) + "\n";
    await seedIntegrityFixture(
      dir,
      `import React from "react";\nexport default function BtnShowcase() { return null; }\n`,
      statesOk
    );

    const r = spawnSync("node", [RECONFORM_SCRIPT, "reconform"], {
      cwd: dir,
      encoding: "utf8",
      input: "\n", // auto-skip any prompts
    });

    // Must mention GEN-001
    const combined = r.stdout + r.stderr;
    expect(combined).toMatch(/GEN-001/);
  });

  it("GEN-001: flags missing __generated marker in .states.json", async () => {
    const showcaseOk = `// @generated by claude-ds — do not edit. Source: btn.tsx meta block.\nimport React from "react";\nimport Btn from "./btn";\n\nexport default function BtnShowcase() {\n  return (\n    <main className="p-8">\n      <h1 className="text-2xl font-bold mb-6">Btn</h1>\n      <section>\n        <h3 className="text-sm font-medium mb-2">default</h3>\n        <Btn />\n      </section>\n    </main>\n  );\n}\n`;
    await seedIntegrityFixture(
      dir,
      showcaseOk,
      JSON.stringify([{ label: "default", props: {} }], null, 2) // no __generated key
    );

    const r = spawnSync("node", [RECONFORM_SCRIPT, "reconform"], {
      cwd: dir,
      encoding: "utf8",
      input: "\n",
    });

    const combined = r.stdout + r.stderr;
    expect(combined).toMatch(/GEN-001/);
  });

  it("GEN-002: flags drift when .showcase.tsx was hand-edited", async () => {
    // Correct header but content differs from what generator would produce
    const showcaseDrifted = `// @generated by claude-ds — do not edit. Source: btn.tsx meta block.\nimport React from "react";\nimport Btn from "./btn";\n\nexport default function BtnShowcase() {\n  // HAND EDIT: this line was added\n  return <div>CUSTOM</div>;\n}\n`;
    const statesOk = JSON.stringify({ __generated: "@generated by claude-ds — do not edit. Source: btn.tsx meta block.", states: [{ label: "default", props: {} }] }, null, 2) + "\n";
    await seedIntegrityFixture(dir, showcaseDrifted, statesOk);

    const r = spawnSync("node", [RECONFORM_SCRIPT, "reconform"], {
      cwd: dir,
      encoding: "utf8",
      input: "\n",
    });

    const combined = r.stdout + r.stderr;
    expect(combined).toMatch(/GEN-002/);
  });

  it("--fix: GEN-002 regenerates showcase to match generator output", async () => {
    const showcaseDrifted = `// @generated by claude-ds — do not edit. Source: btn.tsx meta block.\nimport React from "react";\nexport default function BtnShowcase() { return <div>DRIFTED</div>; }\n`;
    const statesOk = JSON.stringify({ __generated: "@generated by claude-ds — do not edit. Source: btn.tsx meta block.", states: [{ label: "default", props: {} }] }, null, 2) + "\n";
    await seedIntegrityFixture(dir, showcaseDrifted, statesOk);

    spawnSync("node", [RECONFORM_SCRIPT, "reconform", "--fix"], {
      cwd: dir,
      encoding: "utf8",
      input: "\n",
    });

    // After --fix, the showcase must be regenerated (no longer contain DRIFTED)
    const repaired = await readFile(join(dir, "design-system", "atoms", "btn.showcase.tsx"), "utf8");
    expect(repaired).not.toContain("DRIFTED");
    expect(repaired).toMatch(/^\/\/ @generated by claude-ds/);
  });

  it("clean project: no GEN violations when companions match regeneration", async () => {
    // Generate companions using the companion script, then verify reconform is clean
    const dsDir = join(dir, "design-system", "atoms");
    await mkdir(dsDir, { recursive: true });
    await writeFile(join(dir, ".claude-ds.json"), JSON.stringify({ pack: "next-react", version: "v0.6.0", mode: "warn" }, null, 2));
    await writeFile(join(dir, "design-system", "contracts.md"), "# Contracts\n" + "x\n".repeat(30));
    await writeFile(join(dir, "design-system", "tokens.json"), JSON.stringify({ color: { a: "#000" } }, null, 2) + "\n".repeat(30));
    await writeFile(
      join(dsDir, "btn.tsx"),
      `import React from "react";\nexport function Btn() { return <button />; }\nexport const meta = { kind: "atom", examples: [{ name: "default", props: {} }], skip: [] };\n`
    );

    // Generate companions first
    spawnSync("node", ["--experimental-strip-types", SCRIPT], { cwd: dir, encoding: "utf8" });

    // Now run reconform — should report no GEN violations
    const r = spawnSync("node", [RECONFORM_SCRIPT, "reconform"], {
      cwd: dir,
      encoding: "utf8",
      input: "\n",
    });

    const combined = r.stdout + r.stderr;
    expect(combined).toContain("integrity check: all generated files are clean");
    expect(combined).not.toMatch(/GEN-001/);
    expect(combined).not.toMatch(/GEN-002/);
  });
});
