import { describe, it, expect, beforeEach, afterEach } from "vitest";
import { mkdtemp, mkdir, writeFile, rm, readFile } from "node:fs/promises";
import { join } from "node:path";
import { tmpdir } from "node:os";
import { spawnSync } from "node:child_process";
import { resolve } from "node:path";
import { existsSync } from "node:fs";
import { copyFileSync, mkdirSync } from "node:fs";

const SCRIPT = resolve("packs/next-react/files/scripts/generate-showcase-companion.ts");

const FIXTURE_ATOM = resolve("packs/next-react/tests/fixtures/showcase-companion-atom-meta");
const FIXTURE_CVA = resolve("packs/next-react/tests/fixtures/showcase-companion-cva");
const FIXTURE_MULTI_CVA_STUBBED = resolve("packs/next-react/tests/fixtures/showcase-companion-multi-cva-stubbed");
const FIXTURE_REF = resolve("packs/next-react/tests/fixtures/showcase-companion-reference");
const FIXTURE_DEFAULT_EXPORT = resolve("packs/next-react/tests/fixtures/showcase-companion-default-export");

async function fresh(): Promise<string> {
  return mkdtemp(join(tmpdir(), "int-gen-showcase-companion-"));
}

/** Copy a fixture source file into a temp dir maintaining relative path. */
function copyFixture(fixtureSrc: string, dest: string, relPath: string): void {
  const destPath = join(dest, relPath);
  mkdirSync(join(dest, relPath.split("/").slice(0, -1).join("/")), { recursive: true });
  copyFileSync(join(fixtureSrc, relPath), destPath);
}

describe("generate-showcase-companion.ts [integration]", () => {
  let dir: string;

  beforeEach(async () => {
    dir = await fresh();
  });

  afterEach(async () => {
    await rm(dir, { recursive: true, force: true });
  });

  // ── atom with explicit examples ────────────────────────────────────────────

  it("emits .showcase.tsx with @generated header for atom with explicit examples", async () => {
    const dsDir = join(dir, "design-system", "atoms");
    await mkdir(dsDir, { recursive: true });
    copyFixture(FIXTURE_ATOM, dir, "design-system/atoms/button.tsx");

    const r = spawnSync("node", ["--experimental-strip-types", SCRIPT], {
      cwd: dir,
      encoding: "utf8",
    });
    expect(r.status).toBe(0);

    const showcasePath = join(dsDir, "button.showcase.tsx");
    expect(existsSync(showcasePath)).toBe(true);

    const content = await readFile(showcasePath, "utf8");
    // @generated header must be present
    expect(content).toMatch(/^\/\/ @generated by claude-ds — do not edit\. Source: button\.tsx meta block\./);
    // Must import the component — named import because fixture has no default export
    expect(content).toContain('import { Button } from "./button"');
    // Must render both examples
    expect(content).toContain("default");
    expect(content).toContain("disabled");
    // Props from examples must appear
    expect(content).toContain('label="Click me"');
  });

  it("emits .states.json with __generated marker for atom", async () => {
    const dsDir = join(dir, "design-system", "atoms");
    await mkdir(dsDir, { recursive: true });
    copyFixture(FIXTURE_ATOM, dir, "design-system/atoms/button.tsx");

    spawnSync("node", ["--experimental-strip-types", SCRIPT], {
      cwd: dir,
      encoding: "utf8",
    });

    const statesPath = join(dsDir, "button.states.json");
    expect(existsSync(statesPath)).toBe(true);

    const raw = await readFile(statesPath, "utf8");
    const parsed = JSON.parse(raw);
    // __generated key must be present
    expect(parsed).toHaveProperty("__generated");
    expect(typeof parsed.__generated).toBe("string");
    expect(parsed.__generated).toMatch(/@generated by claude-ds/);
    // states array must list examples
    expect(Array.isArray(parsed.states)).toBe(true);
    expect(parsed.states.length).toBeGreaterThan(0);
  });

  // ── CVA auto-expansion ─────────────────────────────────────────────────────

  it("auto-expands CVA cross-product and excludes skip[] entries", async () => {
    const dsDir = join(dir, "design-system", "atoms");
    await mkdir(dsDir, { recursive: true });
    copyFixture(FIXTURE_CVA, dir, "design-system/atoms/badge.tsx");

    const r = spawnSync("node", ["--experimental-strip-types", SCRIPT], {
      cwd: dir,
      encoding: "utf8",
    });
    expect(r.status).toBe(0);

    const showcasePath = join(dsDir, "badge.showcase.tsx");
    expect(existsSync(showcasePath)).toBe(true);

    const content = await readFile(showcasePath, "utf8");
    // Should contain CVA-expanded examples: size × tone = 3×2 = 6 combos, minus 1 skip = 5
    // New grouped structure: primary axis (size) rendered as group headings,
    // secondary axis values appear as labels under each button.
    // Group headings (title-cased primary values)
    expect(content).toContain("Sm");
    expect(content).toContain("Md");
    expect(content).toContain("Lg");
    // Secondary axis labels appear as spans
    expect(content).toContain("primary");
    expect(content).toContain("danger");
    // Skipped combo (size=lg, tone=danger) must NOT produce that tone label under Lg group
    // The Lg group should have primary but not danger
    const lgGroupIdx = content.indexOf(">Lg<");
    const nextGroupIdx = content.indexOf("<section", lgGroupIdx + 1);
    const lgSection = lgGroupIdx >= 0
      ? content.slice(lgGroupIdx, nextGroupIdx > lgGroupIdx ? nextGroupIdx : undefined)
      : "";
    expect(lgSection).not.toContain(">danger<");
  });

  it("states.json for CVA component contains correct number of states (cross-product minus skip)", async () => {
    const dsDir = join(dir, "design-system", "atoms");
    await mkdir(dsDir, { recursive: true });
    copyFixture(FIXTURE_CVA, dir, "design-system/atoms/badge.tsx");

    spawnSync("node", ["--experimental-strip-types", SCRIPT], {
      cwd: dir,
      encoding: "utf8",
    });

    const raw = await readFile(join(dsDir, "badge.states.json"), "utf8");
    const parsed = JSON.parse(raw);
    // 1 explicit default example + (3 sizes × 2 tones = 6 combos minus 1 skip = 5) CVA = 6 total
    expect(parsed.states).toHaveLength(6);
  });

  // ── reference kind ─────────────────────────────────────────────────────────

  it("emits reference showcase that calls meta.render()", async () => {
    const refDir = join(dir, "design-system", "references");
    await mkdir(refDir, { recursive: true });
    copyFixture(FIXTURE_REF, dir, "design-system/references/tokens-page.tsx");

    const r = spawnSync("node", ["--experimental-strip-types", SCRIPT], {
      cwd: dir,
      encoding: "utf8",
    });
    expect(r.status).toBe(0);

    const showcasePath = join(refDir, "tokens-page.showcase.tsx");
    expect(existsSync(showcasePath)).toBe(true);

    const content = await readFile(showcasePath, "utf8");
    expect(content).toMatch(/^\/\/ @generated by claude-ds/);
    // Must import meta from component
    expect(content).toContain('import { meta } from "./tokens-page"');
    // Must call render()
    expect(content).toContain("meta.render()");
    // Must show the title
    expect(content).toContain("Design Tokens");
  });

  // ── no-meta graceful skip ──────────────────────────────────────────────────

  it("skips components with no meta export and exits 0", async () => {
    const dsDir = join(dir, "design-system", "atoms");
    await mkdir(dsDir, { recursive: true });
    // Component without a meta export
    await writeFile(
      join(dsDir, "plain.tsx"),
      `import React from "react";\nexport function Plain() { return <div />; }\n`
    );

    const r = spawnSync("node", ["--experimental-strip-types", SCRIPT], {
      cwd: dir,
      encoding: "utf8",
    });
    expect(r.status).toBe(0);
    // No showcase generated for it
    expect(existsSync(join(dsDir, "plain.showcase.tsx"))).toBe(false);
    // But GEN-000 warning emitted to stderr
    expect(r.stderr).toMatch(/GEN-000/);
  });

  // ── empty dir graceful ─────────────────────────────────────────────────────

  it("exits 0 when design-system dirs are absent", async () => {
    const r = spawnSync("node", ["--experimental-strip-types", SCRIPT], {
      cwd: dir,
      encoding: "utf8",
    });
    expect(r.status).toBe(0);
  });

  // ── no @ts-nocheck ────────────────────────────────────────────────────────

  it("generated .showcase.tsx does not contain @ts-nocheck", async () => {
    const dsDir = join(dir, "design-system", "atoms");
    await mkdir(dsDir, { recursive: true });
    copyFixture(FIXTURE_ATOM, dir, "design-system/atoms/button.tsx");

    spawnSync("node", ["--experimental-strip-types", SCRIPT], { cwd: dir, encoding: "utf8" });

    const content = await readFile(join(dsDir, "button.showcase.tsx"), "utf8");
    expect(content).not.toContain("@ts-nocheck");
  });

  it("CVA-expanded .showcase.tsx does not contain @ts-nocheck", async () => {
    const dsDir = join(dir, "design-system", "atoms");
    await mkdir(dsDir, { recursive: true });
    copyFixture(FIXTURE_CVA, dir, "design-system/atoms/badge.tsx");

    spawnSync("node", ["--experimental-strip-types", SCRIPT], { cwd: dir, encoding: "utf8" });

    const content = await readFile(join(dsDir, "badge.showcase.tsx"), "utf8");
    expect(content).not.toContain("@ts-nocheck");
  });

  // ── header format ──────────────────────────────────────────────────────────

  it("header in .showcase.tsx includes the source filename", async () => {
    const dsDir = join(dir, "design-system", "atoms");
    await mkdir(dsDir, { recursive: true });
    copyFixture(FIXTURE_ATOM, dir, "design-system/atoms/button.tsx");

    spawnSync("node", ["--experimental-strip-types", SCRIPT], { cwd: dir, encoding: "utf8" });

    const content = await readFile(join(dsDir, "button.showcase.tsx"), "utf8");
    expect(content).toContain("Source: button.tsx meta block.");
  });

  // ── string-literal stripping (Bug 1) ──────────────────────────────────────

  it("CVA parser does not emit bogus Tailwind-modifier variant values (hover, active, etc.)", async () => {
    const dsDir = join(dir, "design-system", "atoms");
    await mkdir(dsDir, { recursive: true });
    // Component with Tailwind modifier strings inside CVA variant values
    await writeFile(
      join(dsDir, "button.tsx"),
      [
        `import React from "react";`,
        `import { cva } from "class-variance-authority";`,
        `const buttonVariants = cva("base", {`,
        `  variants: {`,
        `    intent: {`,
        `      primary: ["bg-primary text-primary-foreground", "hover:bg-primary/80", "active:bg-primary/70 active:translate-y-px", "aria-expanded:bg-primary/80"].join(" "),`,
        `      secondary: ["bg-secondary text-secondary-foreground", "hover:bg-border"].join(" "),`,
        `    },`,
        `    size: {`,
        `      sm: "h-7 gap-1 px-2.5 text-sm",`,
        `      default: "h-8 gap-1.5 px-3 text-sm",`,
        `    },`,
        `  },`,
        `  defaultVariants: { intent: "primary", size: "default" },`,
        `});`,
        `export function Button({ intent, size, ...props }: any) { return <button {...props} />; }`,
        `export const meta = { kind: "atom", examples: [{ name: "default", props: {} }], skip: [] };`,
      ].join("\n")
    );

    const r = spawnSync("node", ["--experimental-strip-types", SCRIPT], {
      cwd: dir,
      encoding: "utf8",
    });
    expect(r.status).toBe(0);

    const content = await readFile(join(dsDir, "button.showcase.tsx"), "utf8");
    // Must NOT contain bogus modifier-derived variant values
    expect(content).not.toContain('intent="hover"');
    expect(content).not.toContain('intent="active"');
    expect(content).not.toContain('intent="focus"');
    expect(content).not.toContain('intent="aria"');
    // Must contain exactly the 2 real intent groups and 2 real sizes
    expect(content).toContain(">Primary<");
    expect(content).toContain(">Secondary<");
  });

  // ── children fallback (Bug 2) ─────────────────────────────────────────────

  it("auto-generated non-icon combos get displayName as children", async () => {
    const dsDir = join(dir, "design-system", "atoms");
    await mkdir(dsDir, { recursive: true });
    await writeFile(
      join(dsDir, "btn.tsx"),
      [
        `import React from "react";`,
        `import { cva } from "class-variance-authority";`,
        `const v = cva("b", {`,
        `  variants: {`,
        `    intent: { primary: "p", secondary: "s" },`,
        `    size: { sm: "sm", icon: "ic" },`,
        `  },`,
        `  defaultVariants: { intent: "primary", size: "sm" },`,
        `});`,
        `export function Btn(props: any) { return <button {...props} />; }`,
        `export const meta = { kind: "atom", examples: [{ name: "default", props: {} }], skip: [] };`,
      ].join("\n")
    );

    spawnSync("node", ["--experimental-strip-types", SCRIPT], { cwd: dir, encoding: "utf8" });

    const content = await readFile(join(dsDir, "btn.showcase.tsx"), "utf8");
    // Non-icon size (sm) combos should have text children "Btn"
    expect(content).toContain(">Btn<");
    // Icon size combos should be self-closing (no children)
    expect(content).toContain('size="icon"');
    // Icon buttons should NOT have text children injected
    const iconComboIdx = content.indexOf('size="icon"');
    const afterIcon = content.slice(iconComboIdx, iconComboIdx + 80);
    expect(afterIcon).not.toContain(">Btn<");
  });

  // ── pretty label (Bug 3) ──────────────────────────────────────────────────

  it("grouped section headings use title-case, not underscore-joined debug keys", async () => {
    const dsDir = join(dir, "design-system", "atoms");
    await mkdir(dsDir, { recursive: true });
    await writeFile(
      join(dsDir, "badge.tsx"),
      [
        `import React from "react";`,
        `import { cva } from "class-variance-authority";`,
        `const v = cva("b", {`,
        `  variants: {`,
        `    tone: { primary: "p", danger: "d" },`,
        `    size: { sm: "s", lg: "l" },`,
        `  },`,
        `  defaultVariants: { tone: "primary", size: "sm" },`,
        `});`,
        `export function Badge(props: any) { return <span {...props} />; }`,
        `export const meta = { kind: "atom", examples: [{ name: "default", props: {} }], skip: [] };`,
      ].join("\n")
    );

    spawnSync("node", ["--experimental-strip-types", SCRIPT], { cwd: dir, encoding: "utf8" });

    const content = await readFile(join(dsDir, "badge.showcase.tsx"), "utf8");
    // Group headings must be title-cased primary values
    expect(content).toContain(">Primary<");
    expect(content).toContain(">Danger<");
    // Must NOT contain raw underscore combo keys as headings
    expect(content).not.toContain(">tone=primary_size=sm<");
    expect(content).not.toContain(">tone=danger_size=lg<");
  });

  // ── grouped CVA structure (Bug 4) ─────────────────────────────────────────

  it("CVA combos are grouped by first axis with secondary axis as row", async () => {
    const dsDir = join(dir, "design-system", "atoms");
    await mkdir(dsDir, { recursive: true });
    await writeFile(
      join(dsDir, "chip.tsx"),
      [
        `import React from "react";`,
        `import { cva } from "class-variance-authority";`,
        `const v = cva("c", {`,
        `  variants: {`,
        `    color: { red: "r", blue: "b" },`,
        `    size: { sm: "s", lg: "l" },`,
        `  },`,
        `  defaultVariants: { color: "red", size: "sm" },`,
        `});`,
        `export function Chip(props: any) { return <div {...props} />; }`,
        `export const meta = { kind: "atom", examples: [{ name: "default", props: {} }], skip: [] };`,
      ].join("\n")
    );

    spawnSync("node", ["--experimental-strip-types", SCRIPT], { cwd: dir, encoding: "utf8" });

    const content = await readFile(join(dsDir, "chip.showcase.tsx"), "utf8");
    // Should render a Variants section
    expect(content).toContain("Variants");
    // Each primary value gets its own section heading
    expect(content).toContain(">Red<");
    expect(content).toContain(">Blue<");
    // Buttons within each group are in a flex-wrap row
    expect(content).toContain("flex flex-wrap items-end gap-3");
  });

  // ── import style: named vs default export ────────────────────────────────

  it("named-export-only atom emits import { Name } from named import", async () => {
    const dsDir = join(dir, "design-system", "atoms");
    await mkdir(dsDir, { recursive: true });
    // Component with only a named export (no export default).
    // Uses a non-stub example (has a non-empty prop) so the import is emitted.
    await writeFile(
      join(dsDir, "app-shell.tsx"),
      [
        `import React from "react";`,
        `export function AppShell({ children }: { children?: React.ReactNode }) {`,
        `  return <div>{children}</div>;`,
        `}`,
        `export const meta = { kind: "atom", examples: [{ name: "with-child", props: { children: "hello" } }], skip: [] };`,
      ].join("\n")
    );

    const r = spawnSync("node", ["--experimental-strip-types", SCRIPT], {
      cwd: dir,
      encoding: "utf8",
    });
    expect(r.status).toBe(0);

    const content = await readFile(join(dsDir, "app-shell.showcase.tsx"), "utf8");
    // Must use named import because there is no default export
    expect(content).toContain('import { AppShell } from "./app-shell"');
    // Must NOT use default import
    expect(content).not.toMatch(/import AppShell from/);
  });

  it("default-export atom emits default import", async () => {
    const dsDir = join(dir, "design-system", "atoms");
    await mkdir(dsDir, { recursive: true });
    copyFixture(FIXTURE_DEFAULT_EXPORT, dir, "design-system/atoms/card.tsx");

    const r = spawnSync("node", ["--experimental-strip-types", SCRIPT], {
      cwd: dir,
      encoding: "utf8",
    });
    expect(r.status).toBe(0);

    const content = await readFile(join(dsDir, "card.showcase.tsx"), "utf8");
    // Must use default import because fixture has export default function Card
    expect(content).toContain('import Card from "./card"');
    // Must NOT use named import
    expect(content).not.toMatch(/import \{ Card \} from/);
  });

  // ── reference prose wrap (Bug 5) ─────────────────────────────────────────

  it("reference showcase wraps content in prose div", async () => {
    const refDir = join(dir, "design-system", "references");
    await mkdir(refDir, { recursive: true });
    copyFixture(FIXTURE_REF, dir, "design-system/references/tokens-page.tsx");

    spawnSync("node", ["--experimental-strip-types", SCRIPT], { cwd: dir, encoding: "utf8" });

    const content = await readFile(join(refDir, "tokens-page.showcase.tsx"), "utf8");
    expect(content).toContain('className="prose prose-neutral dark:prose-invert max-w-none"');
  });
});

// ── Integrity check tests (GEN-001 / GEN-002) ────────────────────────────────
// These test the reconform integrity logic by invoking reconform directly.
// We construct minimal consumer projects with .claude-ds.json, pack manifest,
// and pre-seeded generated files.

import { fileURLToPath } from "node:url";
const RECONFORM_SCRIPT = resolve("dist/cli.js");
const PACK_DIR = resolve("packs/next-react");

async function seedIntegrityFixture(dir: string, showcaseContent: string, statesContent: string): Promise<void> {
  // .claude-ds.json
  await writeFile(join(dir, ".claude-ds.json"), JSON.stringify({ pack: "next-react", version: "v0.6.0", mode: "warn" }, null, 2));
  // Minimal design-system/contracts.md and tokens.json to avoid stub warning exit
  await mkdir(join(dir, "design-system", "atoms"), { recursive: true });
  await writeFile(join(dir, "design-system", "contracts.md"), "# Contracts\n" + "x\n".repeat(30));
  await writeFile(join(dir, "design-system", "tokens.json"), JSON.stringify({ color: { a: "#000" } }, null, 2) + "\n".repeat(30));
  // Component source with meta
  await writeFile(
    join(dir, "design-system", "atoms", "btn.tsx"),
    `import React from "react";\nexport function Btn() { return <button />; }\nexport const meta = { kind: "atom", examples: [{ name: "default", props: {} }], skip: [] };\n`
  );
  // Pre-seeded generated companions
  await writeFile(join(dir, "design-system", "atoms", "btn.showcase.tsx"), showcaseContent);
  await writeFile(join(dir, "design-system", "atoms", "btn.states.json"), statesContent);
}

describe("reconform integrity check (GEN-001 / GEN-002)", () => {
  let dir: string;

  beforeEach(async () => {
    dir = await fresh();
  });

  afterEach(async () => {
    await rm(dir, { recursive: true, force: true });
  });

  it("GEN-001: flags missing @generated header in .showcase.tsx", async () => {
    // Showcase without header
    const statesOk = JSON.stringify({ __generated: "@generated by claude-ds — do not edit. Source: btn.tsx meta block.", states: [] }, null, 2) + "\n";
    await seedIntegrityFixture(
      dir,
      `import React from "react";\nexport default function BtnShowcase() { return null; }\n`,
      statesOk
    );

    const r = spawnSync("node", [RECONFORM_SCRIPT, "reconform"], {
      cwd: dir,
      encoding: "utf8",
      input: "\n", // auto-skip any prompts
    });

    // Must mention GEN-001
    const combined = r.stdout + r.stderr;
    expect(combined).toMatch(/GEN-001/);
  });

  it("GEN-001: flags missing __generated marker in .states.json", async () => {
    const showcaseOk = `// @generated by claude-ds — do not edit. Source: btn.tsx meta block.\nimport React from "react";\nimport Btn from "./btn";\n\nexport default function BtnShowcase() {\n  return (\n    <main className="p-8">\n      <h1 className="text-2xl font-bold mb-6">Btn</h1>\n      <section>\n        <h3 className="text-sm font-medium mb-2">default</h3>\n        <Btn />\n      </section>\n    </main>\n  );\n}\n`;
    await seedIntegrityFixture(
      dir,
      showcaseOk,
      JSON.stringify([{ label: "default", props: {} }], null, 2) // no __generated key
    );

    const r = spawnSync("node", [RECONFORM_SCRIPT, "reconform"], {
      cwd: dir,
      encoding: "utf8",
      input: "\n",
    });

    const combined = r.stdout + r.stderr;
    expect(combined).toMatch(/GEN-001/);
  });

  it("GEN-002: flags drift when .showcase.tsx was hand-edited", async () => {
    // Correct header but content differs from what generator would produce
    const showcaseDrifted = `// @generated by claude-ds — do not edit. Source: btn.tsx meta block.\nimport React from "react";\nimport Btn from "./btn";\n\nexport default function BtnShowcase() {\n  // HAND EDIT: this line was added\n  return <div>CUSTOM</div>;\n}\n`;
    const statesOk = JSON.stringify({ __generated: "@generated by claude-ds — do not edit. Source: btn.tsx meta block.", states: [{ label: "default", props: {} }] }, null, 2) + "\n";
    await seedIntegrityFixture(dir, showcaseDrifted, statesOk);

    const r = spawnSync("node", [RECONFORM_SCRIPT, "reconform"], {
      cwd: dir,
      encoding: "utf8",
      input: "\n",
    });

    const combined = r.stdout + r.stderr;
    expect(combined).toMatch(/GEN-002/);
  });

  it("--fix: GEN-002 regenerates showcase to match generator output", async () => {
    const showcaseDrifted = `// @generated by claude-ds — do not edit. Source: btn.tsx meta block.\nimport React from "react";\nexport default function BtnShowcase() { return <div>DRIFTED</div>; }\n`;
    const statesOk = JSON.stringify({ __generated: "@generated by claude-ds — do not edit. Source: btn.tsx meta block.", states: [{ label: "default", props: {} }] }, null, 2) + "\n";
    await seedIntegrityFixture(dir, showcaseDrifted, statesOk);

    spawnSync("node", [RECONFORM_SCRIPT, "reconform", "--fix"], {
      cwd: dir,
      encoding: "utf8",
      input: "\n",
    });

    // After --fix, the showcase must be regenerated (no longer contain DRIFTED)
    const repaired = await readFile(join(dir, "design-system", "atoms", "btn.showcase.tsx"), "utf8");
    expect(repaired).not.toContain("DRIFTED");
    expect(repaired).toMatch(/^\/\/ @generated by claude-ds/);
  });

  it("clean project: no GEN violations when companions match regeneration", async () => {
    // Generate companions using the companion script, then verify reconform is clean
    const dsDir = join(dir, "design-system", "atoms");
    await mkdir(dsDir, { recursive: true });
    await writeFile(join(dir, ".claude-ds.json"), JSON.stringify({ pack: "next-react", version: "v0.6.0", mode: "warn" }, null, 2));
    await writeFile(join(dir, "design-system", "contracts.md"), "# Contracts\n" + "x\n".repeat(30));
    await writeFile(join(dir, "design-system", "tokens.json"), JSON.stringify({ color: { a: "#000" } }, null, 2) + "\n".repeat(30));
    await writeFile(
      join(dsDir, "btn.tsx"),
      `import React from "react";\nexport function Btn() { return <button />; }\nexport const meta = { kind: "atom", examples: [{ name: "default", props: {} }], skip: [] };\n`
    );

    // Generate companions first
    spawnSync("node", ["--experimental-strip-types", SCRIPT], { cwd: dir, encoding: "utf8" });

    // Now run reconform — should report no GEN violations
    const r = spawnSync("node", [RECONFORM_SCRIPT, "reconform"], {
      cwd: dir,
      encoding: "utf8",
      input: "\n",
    });

    const combined = r.stdout + r.stderr;
    expect(combined).toContain("integrity check: all generated files are clean");
    expect(combined).not.toMatch(/GEN-001/);
    expect(combined).not.toMatch(/GEN-002/);
  });
});

// ── Error boundary + stub-meta tests ────────────────────────────────────────

describe("error boundary and stub-meta placeholder", () => {
  let dir: string;

  beforeEach(async () => {
    dir = await fresh();
  });

  afterEach(async () => {
    await rm(dir, { recursive: true, force: true });
  });

  // ── Task 1: error boundary import is emitted in page.tsx ──────────────────

  it("page.tsx imports ShowcaseBoundary from _showcase-boundary", async () => {
    const pagePath = resolve("packs/next-react/files/app/design/[...slug]/page.tsx");
    const content = await readFile(pagePath, "utf8");
    expect(content).toContain('import { ShowcaseBoundary }');
    expect(content).toContain('_showcase-boundary');
  });

  it("page.tsx wraps <Showcase /> in <ShowcaseBoundary>", async () => {
    const pagePath = resolve("packs/next-react/files/app/design/[...slug]/page.tsx");
    const content = await readFile(pagePath, "utf8");
    expect(content).toContain('<ShowcaseBoundary');
    expect(content).toContain('<Showcase />');
    // Boundary must appear before Showcase (wraps it)
    expect(content.indexOf('<ShowcaseBoundary')).toBeLessThan(content.indexOf('<Showcase />'));
  });

  // ── Task 2: stub-meta produces placeholder card ───────────────────────────

  it("stub meta (name=default, empty props, no CVA) emits placeholder — no component import", async () => {
    const dsDir = join(dir, "design-system", "atoms");
    await mkdir(dsDir, { recursive: true });
    await writeFile(
      join(dsDir, "stub-atom.tsx"),
      [
        `import React from "react";`,
        `export function StubAtom({ items }: { items: string[] }) { return <ul>{items.map(i => <li key={i}>{i}</li>)}</ul>; }`,
        `export const meta = { kind: "atom", examples: [{ name: "default", props: {} }], skip: [] };`,
      ].join("\n")
    );

    const r = spawnSync("node", ["--experimental-strip-types", SCRIPT], {
      cwd: dir,
      encoding: "utf8",
    });
    expect(r.status).toBe(0);

    const content = await readFile(join(dsDir, "stub-atom.showcase.tsx"), "utf8");
    // Must have @generated header
    expect(content).toMatch(/^\/\/ @generated by claude-ds/);
    // Must contain placeholder text
    expect(content).toContain("No examples defined");
    expect(content).toContain("meta.examples");
    // Must NOT import or render the component
    expect(content).not.toContain('import { StubAtom }');
    expect(content).not.toContain('import StubAtom');
    expect(content).not.toContain('<StubAtom');
  });

  // ── Task 2: non-stub meta still renders component ─────────────────────────

  it("non-stub meta (non-empty props) renders component normally", async () => {
    const dsDir = join(dir, "design-system", "atoms");
    await mkdir(dsDir, { recursive: true });
    await writeFile(
      join(dsDir, "real-atom.tsx"),
      [
        `import React from "react";`,
        `export function RealAtom({ label }: { label: string }) { return <span>{label}</span>; }`,
        `export const meta = { kind: "atom", examples: [{ name: "filled", props: { label: "hello" } }], skip: [] };`,
      ].join("\n")
    );

    const r = spawnSync("node", ["--experimental-strip-types", SCRIPT], {
      cwd: dir,
      encoding: "utf8",
    });
    expect(r.status).toBe(0);

    const content = await readFile(join(dsDir, "real-atom.showcase.tsx"), "utf8");
    // Must render the component
    expect(content).toContain('import { RealAtom }');
    expect(content).toContain('<RealAtom');
    // Must NOT show placeholder
    expect(content).not.toContain("No examples defined");
  });

  it("stub meta with CVA variants renders normally (not placeholder)", async () => {
    const dsDir = join(dir, "design-system", "atoms");
    await mkdir(dsDir, { recursive: true });
    await writeFile(
      join(dsDir, "cva-atom.tsx"),
      [
        `import React from "react";`,
        `import { cva } from "class-variance-authority";`,
        `const v = cva("b", {`,
        `  variants: { intent: { primary: "p", secondary: "s" } },`,
        `  defaultVariants: { intent: "primary" },`,
        `});`,
        `export function CvaAtom(props: any) { return <div {...props} />; }`,
        // stub meta but CVA exists — should render normally
        `export const meta = { kind: "atom", examples: [{ name: "default", props: {} }], skip: [] };`,
      ].join("\n")
    );

    const r = spawnSync("node", ["--experimental-strip-types", SCRIPT], {
      cwd: dir,
      encoding: "utf8",
    });
    expect(r.status).toBe(0);

    const content = await readFile(join(dsDir, "cva-atom.showcase.tsx"), "utf8");
    // Should render component (CVA expanded combos)
    expect(content).toContain('import { CvaAtom }');
    expect(content).toContain('<CvaAtom');
    // Must NOT show placeholder
    expect(content).not.toContain("No examples defined");
  });

  // ── multi-CVA file with examples:[] emits placeholder (regression for #62) ──

  it("multi-CVA file with examples:[] emits placeholder card, not malformed JSX", async () => {
    const dsDir = join(dir, "design-system", "atoms");
    await mkdir(dsDir, { recursive: true });
    copyFixture(FIXTURE_MULTI_CVA_STUBBED, dir, "design-system/atoms/badge.tsx");

    const r = spawnSync("node", ["--experimental-strip-types", SCRIPT], {
      cwd: dir,
      encoding: "utf8",
    });
    expect(r.status).toBe(0);

    const content = await readFile(join(dsDir, "badge.showcase.tsx"), "utf8");
    // Must have @generated header
    expect(content).toMatch(/^\/\/ @generated by claude-ds/);
    // Must contain placeholder card marker
    expect(content).toContain("No examples defined");
    expect(content).toContain("meta.examples");
    // Must NOT contain CVA-expanded variants= attributes (would be malformed JSX)
    expect(content).not.toContain("variants=");
    // Must NOT render the component as JSX
    expect(content).not.toContain("<Badge");
  });
});

// ── v0.7.0 hand-off contract: full-variant matrix + states + analyzer hook ──

describe("v0.7.0 hand-off contract (issue #60)", () => {
  let dir: string;

  beforeEach(async () => {
    dir = await fresh();
  });

  afterEach(async () => {
    await rm(dir, { recursive: true, force: true });
  });

  /** Set up a Crewops-shaped fixture: one CVA atom with states + optional analyzer. */
  async function seedCrewopsFixture(opts: { withAnalyzer: boolean }): Promise<string> {
    const dsDir = join(dir, "design-system", "atoms");
    await mkdir(dsDir, { recursive: true });
    await writeFile(
      join(dsDir, "button.tsx"),
      [
        `import React from "react";`,
        `import { cva } from "class-variance-authority";`,
        `const v = cva("b", {`,
        `  variants: {`,
        `    intent: { primary: "p", secondary: "s", destructive: "d" },`,
        `    size: { sm: "s", md: "m", lg: "l" },`,
        `  },`,
        `  defaultVariants: { intent: "primary", size: "md" },`,
        `});`,
        `export function Button(props: any) { return <button {...props} />; }`,
        `export const meta = {`,
        `  kind: "atom",`,
        `  examples: [{ name: "default", props: { children: "Click" } }],`,
        `  skip: [],`,
        `  states: {`,
        `    loading: { name: "loading-default", props: { loading: true, children: "Loading" } },`,
        `    longText: { name: "long-text", props: { children: "A very long label that wraps" } },`,
        `  },`,
        `};`,
      ].join("\n")
    );
    if (opts.withAnalyzer) {
      const scriptsDir = join(dir, "scripts");
      await mkdir(scriptsDir, { recursive: true });
      // Stub analyzer: returns one literal hit for Button intent=primary, marks size dynamic.
      await writeFile(
        join(scriptsDir, "analyze-component-usage.ts"),
        [
          `export default async function analyze(_files: string[]) {`,
          `  const m = new Map();`,
          `  const literal = new Map();`,
          `  const intent = new Map();`,
          `  intent.set("primary", 3);`,
          `  literal.set("intent", intent);`,
          `  m.set("Button", { literal, dynamicProps: new Set(["size"]) });`,
          `  return m;`,
          `}`,
        ].join("\n")
      );
      // Add an app file so the analyzer has something to scan
      const appDir = join(dir, "app");
      await mkdir(appDir, { recursive: true });
      await writeFile(join(appDir, "page.tsx"), `export default function P() { return null; }\n`);
    }
    return join(dsDir, "button.showcase.tsx");
  }

  it("(a) generated showcase has no @ts-nocheck", async () => {
    const showcasePath = await seedCrewopsFixture({ withAnalyzer: false });
    const r = spawnSync("node", ["--experimental-strip-types", SCRIPT], {
      cwd: dir,
      encoding: "utf8",
    });
    expect(r.status).toBe(0);
    const content = await readFile(showcasePath, "utf8");
    expect(content).not.toContain("@ts-nocheck");
  });

  it("(b) full CVA variant matrix rendered (3 intents × 3 sizes = 9 combos)", async () => {
    const showcasePath = await seedCrewopsFixture({ withAnalyzer: false });
    spawnSync("node", ["--experimental-strip-types", SCRIPT], { cwd: dir, encoding: "utf8" });
    const content = await readFile(showcasePath, "utf8");
    // All 3 primary-axis (intent) groups present as headings
    expect(content).toContain(">Primary<");
    expect(content).toContain(">Secondary<");
    expect(content).toContain(">Destructive<");
    // All 9 cross-product combos present in states.json
    const states = JSON.parse(
      await readFile(join(dir, "design-system", "atoms", "button.states.json"), "utf8")
    );
    // 1 explicit + 9 CVA combos = 10
    expect(states.states.length).toBeGreaterThanOrEqual(9);
  });

  it("(c) meta.states.loading produces a Loading row in output", async () => {
    const showcasePath = await seedCrewopsFixture({ withAnalyzer: false });
    spawnSync("node", ["--experimental-strip-types", SCRIPT], { cwd: dir, encoding: "utf8" });
    const content = await readFile(showcasePath, "utf8");
    expect(content).toContain(">States<");
    expect(content).toContain(">Loading<");
    expect(content).toContain("loading-default");
    expect(content).toContain("loading");
    // longText row also present
    expect(content).toContain(">Long text<");
    expect(content).toContain("long-text");
  });

  it("(d) with stub analyzer present, tag column appears in output", async () => {
    const showcasePath = await seedCrewopsFixture({ withAnalyzer: true });
    const r = spawnSync("node", ["--experimental-strip-types", SCRIPT], {
      cwd: dir,
      encoding: "utf8",
    });
    expect(r.status).toBe(0);
    const content = await readFile(showcasePath, "utf8");
    // At least one usage tag glyph must appear (used/dynamic/unused)
    const hasTag = content.includes("✓") || content.includes("⚠") || content.includes("✗");
    expect(hasTag).toBe(true);
  });

  it("(d-neg) without analyzer file, no tag glyphs are emitted", async () => {
    const showcasePath = await seedCrewopsFixture({ withAnalyzer: false });
    spawnSync("node", ["--experimental-strip-types", SCRIPT], { cwd: dir, encoding: "utf8" });
    const content = await readFile(showcasePath, "utf8");
    expect(content).not.toContain("✓");
    expect(content).not.toContain("⚠");
    expect(content).not.toContain("✗");
  });
});

// ── v0.7.8 showcase format finalization (issue #65) ──────────────────────────

describe("v0.7.8 showcase format finalization (issue #65)", () => {
  let dir: string;

  beforeEach(async () => {
    dir = await fresh();
  });

  afterEach(async () => {
    await rm(dir, { recursive: true, force: true });
  });

  /** Seed an atom whose CVA matches a name from explicit examples (overlap intent). */
  async function seedButtonWithIconAndStates(opts: { withAnalyzer: boolean }): Promise<string> {
    const dsDir = join(dir, "design-system", "atoms");
    await mkdir(dsDir, { recursive: true });
    await writeFile(
      join(dsDir, "button.tsx"),
      [
        `import React from "react";`,
        `import { cva } from "class-variance-authority";`,
        `const v = cva("b", {`,
        `  variants: {`,
        `    intent: { primary: "p", secondary: "s" },`,
        `    size: { sm: "sm", md: "md", icon: "ic", "icon-sm": "ics" },`,
        `  },`,
        `  defaultVariants: { intent: "primary", size: "md" },`,
        `});`,
        `export function Button(props: any) { return <button {...props} />; }`,
        `export const meta = {`,
        `  kind: "atom",`,
        `  examples: [{ name: "intent=primary_size=md", props: { children: "Click" } }],`,
        `  skip: [],`,
        `  states: {`,
        `    disabled: { name: "disabled", props: { children: "Disabled" } },`,
        `    hover:    { name: "hover",    props: { children: "Hover" } },`,
        `    focus:    { name: "focus",    props: { children: "Focus" } },`,
        `    pressed:  { name: "pressed",  props: { children: "Pressed" } },`,
        `    expanded: { name: "expanded", props: { children: "Expanded" } },`,
        `    invalid:  { name: "invalid",  props: { children: "Invalid" } },`,
        `  },`,
        `};`,
      ].join("\n")
    );
    if (opts.withAnalyzer) {
      const scriptsDir = join(dir, "scripts");
      await mkdir(scriptsDir, { recursive: true });
      await writeFile(
        join(scriptsDir, "analyze-component-usage.ts"),
        [
          `export default async function analyze(_files: string[]) {`,
          `  const m = new Map();`,
          `  const literal = new Map();`,
          `  const intent = new Map();`,
          // primary is in CVA → goes to Used row.
          `  intent.set("primary", 8);`,
          // "ghost" is NOT in CVA → goes to Unknown row.
          `  intent.set("ghost", 2);`,
          `  literal.set("intent", intent);`,
          `  m.set("Button", { literal, dynamicProps: new Set() });`,
          `  return m;`,
          `}`,
        ].join("\n")
      );
      const appDir = join(dir, "app");
      await mkdir(appDir, { recursive: true });
      await writeFile(join(appDir, "page.tsx"), `export default function P() { return null; }\n`);
    }
    return join(dsDir, "button.showcase.tsx");
  }

  it("(#1) Variants grid renders the full CVA matrix even when names overlap with Examples", async () => {
    const showcasePath = await seedButtonWithIconAndStates({ withAnalyzer: false });
    const r = spawnSync("node", ["--experimental-strip-types", SCRIPT], {
      cwd: dir,
      encoding: "utf8",
    });
    expect(r.status).toBe(0);
    const content = await readFile(showcasePath, "utf8");
    // explicit example name collides with intent=primary, size=md; the combo must
    // still render in the Variants grid (no dedup).
    const variantsIdx = content.indexOf(">Variants<");
    expect(variantsIdx).toBeGreaterThan(-1);
    const variantsBlock = content.slice(variantsIdx);
    expect(variantsBlock).toContain('intent="primary" size="md"');
    expect(variantsBlock).toContain('intent="secondary" size="md"');
  });

  it("(#2) icon* size cells inject the lucide Square placeholder", async () => {
    const showcasePath = await seedButtonWithIconAndStates({ withAnalyzer: false });
    spawnSync("node", ["--experimental-strip-types", SCRIPT], { cwd: dir, encoding: "utf8" });
    const content = await readFile(showcasePath, "utf8");
    // Square import is emitted from lucide-react
    expect(content).toContain('import { Square } from "lucide-react";');
    // Square is rendered inside both icon and icon-sm cells
    expect(content).toMatch(/size="icon"[\s\S]*?<Square/);
    expect(content).toMatch(/size="icon-sm"[\s\S]*?<Square/);
  });

  it("(#3) per-cell ✓/⚠/✗ tags are dropped from the Variants grid", async () => {
    const showcasePath = await seedButtonWithIconAndStates({ withAnalyzer: true });
    spawnSync("node", ["--experimental-strip-types", SCRIPT], { cwd: dir, encoding: "utf8" });
    const content = await readFile(showcasePath, "utf8");
    // The variant grid never carries glyph spans on per-cell labels.
    const variantsIdx = content.indexOf(">Variants<");
    const usageIdx = content.indexOf(">Usage<");
    expect(variantsIdx).toBeGreaterThan(-1);
    expect(usageIdx).toBeGreaterThan(-1);
    const variantsBlock = content.slice(variantsIdx);
    // glyphs may live only in the Usage block (which sits above Variants)
    expect(variantsBlock).not.toContain("✓");
    expect(variantsBlock).not.toContain("✗");
    expect(variantsBlock).not.toContain("⚠");
    // sanity: Usage block sits above Variants
    expect(usageIdx).toBeLessThan(variantsIdx);
  });

  it("(#3) Usage block renders ✓ Used (in CVA) and ✗ Unknown (not in CVA) rows", async () => {
    const showcasePath = await seedButtonWithIconAndStates({ withAnalyzer: true });
    spawnSync("node", ["--experimental-strip-types", SCRIPT], { cwd: dir, encoding: "utf8" });
    const content = await readFile(showcasePath, "utf8");
    expect(content).toContain(">Usage<");
    // ✓ Used: intent=primary (8) — value is in CVA
    expect(content).toMatch(/✓[\s\S]*?Used[\s\S]*?intent="primary" \(8\)/);
    // ✗ Unknown: intent=ghost (2) — value NOT in CVA
    expect(content).toMatch(/✗[\s\S]*?Unknown at callsites[\s\S]*?intent="ghost" \(2\)/);
    // Dead-in-CVA row is deferred — no ⚠ row in default config
    expect(content).not.toContain("⚠");
  });

  it("(#4) States section renders a row per declared state with force mechanism", async () => {
    const showcasePath = await seedButtonWithIconAndStates({ withAnalyzer: false });
    spawnSync("node", ["--experimental-strip-types", SCRIPT], { cwd: dir, encoding: "utf8" });
    const content = await readFile(showcasePath, "utf8");
    // Section heading present
    expect(content).toContain(">States<");
    // Disabled row uses the disabled attribute
    expect(content).toMatch(/>Disabled<[\s\S]*?disabled[\s\S]*?>Disabled</);
    // Hover row wraps in .force-hover
    expect(content).toMatch(/>Hover<[\s\S]*?force-hover/);
    // Focus row wraps in .force-focus
    expect(content).toMatch(/>Focus<[\s\S]*?force-focus/);
    // aria-* attributes on pressed / expanded / invalid
    expect(content).toMatch(/>Pressed<[\s\S]*?aria-pressed="true"/);
    expect(content).toMatch(/>Expanded<[\s\S]*?aria-expanded="true"/);
    expect(content).toMatch(/>Invalid<[\s\S]*?aria-invalid="true"/);
  });

  it("(#4) no States section emitted when meta.states declares no rows", async () => {
    const dsDir = join(dir, "design-system", "atoms");
    await mkdir(dsDir, { recursive: true });
    await writeFile(
      join(dsDir, "tag.tsx"),
      [
        `import React from "react";`,
        `import { cva } from "class-variance-authority";`,
        `const v = cva("t", { variants: { tone: { neutral: "n" } } });`,
        `export function Tag(props: any) { return <span {...props} />; }`,
        `export const meta = { kind: "atom", examples: [{ name: "default", props: {} }] };`,
      ].join("\n")
    );
    spawnSync("node", ["--experimental-strip-types", SCRIPT], { cwd: dir, encoding: "utf8" });
    const content = await readFile(join(dsDir, "tag.showcase.tsx"), "utf8");
    expect(content).not.toContain(">States<");
  });
});

// ── AST-based meta extractor integration tests (issue #61 cycle 2) ───────────

const FIXTURE_AST_EXTRACTOR = resolve("packs/next-react/tests/fixtures/ast-extractor-fixture");

describe("AST-based meta extractor (A3)", () => {
  let dir: string;

  beforeEach(async () => {
    dir = await fresh();
  });

  afterEach(async () => {
    await rm(dir, { recursive: true, force: true });
  });

  it("emits arrow function source verbatim in column.cell props", async () => {
    const dsDir = join(dir, "design-system", "atoms");
    await mkdir(dsDir, { recursive: true });
    // Copy fixture source + sibling fixture file
    copyFixture(FIXTURE_AST_EXTRACTOR, dir, "design-system/atoms/data-grid.tsx");
    copyFixture(FIXTURE_AST_EXTRACTOR, dir, "design-system/atoms/grid-fixtures.ts");

    const r = spawnSync("node", ["--experimental-strip-types", SCRIPT], {
      cwd: dir,
      encoding: "utf8",
    });
    expect(r.status).toBe(0);

    const content = await readFile(join(dsDir, "data-grid.showcase.tsx"), "utf8");
    // @generated header
    expect(content).toMatch(/^\/\/ @generated by claude-ds/);
    // Arrow function in columns.cell must be emitted verbatim (not dropped or stringified)
    expect(content).toContain("(row: GridRow) => row.name");
    expect(content).toContain("(row: GridRow) => row.id");
  });

  it("inlines imported sibling fixture values (sampleRows)", async () => {
    const dsDir = join(dir, "design-system", "atoms");
    await mkdir(dsDir, { recursive: true });
    copyFixture(FIXTURE_AST_EXTRACTOR, dir, "design-system/atoms/data-grid.tsx");
    copyFixture(FIXTURE_AST_EXTRACTOR, dir, "design-system/atoms/grid-fixtures.ts");

    spawnSync("node", ["--experimental-strip-types", SCRIPT], { cwd: dir, encoding: "utf8" });

    const content = await readFile(join(dsDir, "data-grid.showcase.tsx"), "utf8");
    // sampleRows from grid-fixtures.ts should be inlined as array literal
    // Serializer emits unquoted keys for simple identifiers: id: "r1"
    expect(content).toContain('"r1"');
    expect(content).toContain("Alpha");
    // All 3 rows inlined
    expect(content).toContain('"r2"');
    expect(content).toContain('"r3"');
  });

  it("emits states.json with empty state props from states block", async () => {
    const dsDir = join(dir, "design-system", "atoms");
    await mkdir(dsDir, { recursive: true });
    copyFixture(FIXTURE_AST_EXTRACTOR, dir, "design-system/atoms/data-grid.tsx");
    copyFixture(FIXTURE_AST_EXTRACTOR, dir, "design-system/atoms/grid-fixtures.ts");

    spawnSync("node", ["--experimental-strip-types", SCRIPT], { cwd: dir, encoding: "utf8" });

    // states.json should carry the empty state
    const statesContent = await readFile(join(dsDir, "data-grid.states.json"), "utf8");
    const states = JSON.parse(statesContent);
    // examples list (not states block in states.json — states.json only has examples[])
    expect(states).toHaveProperty("__generated");
    expect(Array.isArray(states.states)).toBe(true);
    // Showcase should NOT say "No examples defined" (it has real examples)
    const showcaseContent = await readFile(join(dsDir, "data-grid.showcase.tsx"), "utf8");
    expect(showcaseContent).not.toContain("No examples defined");
  });

  // ── carries refs + use-client (data-table style composite) ─────────────────

  const FIXTURE_CARRIES_REFS = resolve(
    "packs/next-react/tests/fixtures/showcase-companion-carries-refs"
  );

  it("mirrors 'use client' from the source onto the generated showcase", async () => {
    copyFixture(FIXTURE_CARRIES_REFS, dir, "design-system/composites/data-table.tsx");
    copyFixture(FIXTURE_CARRIES_REFS, dir, "design-system/_fixtures/job-fixtures.ts");

    const r = spawnSync("node", ["--experimental-strip-types", SCRIPT], {
      cwd: dir,
      encoding: "utf8",
    });
    expect(r.status).toBe(0);

    const content = await readFile(
      join(dir, "design-system/composites/data-table.showcase.tsx"),
      "utf8"
    );
    expect(content.startsWith('"use client";')).toBe(true);
  });

  it("carries import for value identifiers referenced inside inlined arrow bodies", async () => {
    copyFixture(FIXTURE_CARRIES_REFS, dir, "design-system/composites/data-table.tsx");
    copyFixture(FIXTURE_CARRIES_REFS, dir, "design-system/_fixtures/job-fixtures.ts");

    spawnSync("node", ["--experimental-strip-types", SCRIPT], { cwd: dir, encoding: "utf8" });

    const content = await readFile(
      join(dir, "design-system/composites/data-table.showcase.tsx"),
      "utf8"
    );
    // The cell arrow `(j) => JOB_STATUS_LABEL[j.status]` was inlined as part
    // of jobColumns; the generator must add an import for JOB_STATUS_LABEL
    // from the same relative path the source used.
    expect(content).toContain("JOB_STATUS_LABEL");
    expect(content).toMatch(
      /import\s*\{[^}]*JOB_STATUS_LABEL[^}]*\}\s*from\s*"\.\.\/_fixtures\/job-fixtures"/
    );
  });

  it("emits a const declaration for source-local identifiers referenced in unevaluated expressions (jobColumns.map)", async () => {
    copyFixture(FIXTURE_CARRIES_REFS, dir, "design-system/composites/data-table.tsx");
    copyFixture(FIXTURE_CARRIES_REFS, dir, "design-system/_fixtures/job-fixtures.ts");

    spawnSync("node", ["--experimental-strip-types", SCRIPT], { cwd: dir, encoding: "utf8" });

    const content = await readFile(
      join(dir, "design-system/composites/data-table.showcase.tsx"),
      "utf8"
    );
    // The `sortable` example uses `jobColumns.map(c => ...)` which we keep as
    // raw source. `jobColumns` is local to data-table.tsx (not exported), so
    // it must be inlined as a const at the top of the showcase.
    // (Cluster 2: rawSource preserves the type annotation, so `=` may be
    //  preceded by `: DataTableColumn<…>[]` — match just the name.)
    expect(content).toMatch(/const\s+jobColumns\b/);
    expect(content).toContain("jobColumns.map");
  });

  it("re-emits `import type` for types declared in the source component module", async () => {
    // DataTableColumn is `export interface` in data-table.tsx (not imported from
    // anywhere). When jobColumns carries its `: DataTableColumn<JobFixture>[]`
    // annotation, the showcase must add `import type { DataTableColumn } from "./data-table"`.
    copyFixture(FIXTURE_CARRIES_REFS, dir, "design-system/composites/data-table.tsx");
    copyFixture(FIXTURE_CARRIES_REFS, dir, "design-system/_fixtures/job-fixtures.ts");

    spawnSync("node", ["--experimental-strip-types", SCRIPT], { cwd: dir, encoding: "utf8" });

    const content = await readFile(
      join(dir, "design-system/composites/data-table.showcase.tsx"),
      "utf8"
    );
    expect(content).toMatch(
      /import\s+type\s*\{[^}]*DataTableColumn[^}]*\}\s*from\s*"\.\/data-table"/
    );
  });

  it("does not emit 'No examples defined' when functions are present in props", async () => {
    const dsDir = join(dir, "design-system", "atoms");
    await mkdir(dsDir, { recursive: true });
    copyFixture(FIXTURE_AST_EXTRACTOR, dir, "design-system/atoms/data-grid.tsx");
    copyFixture(FIXTURE_AST_EXTRACTOR, dir, "design-system/atoms/grid-fixtures.ts");

    spawnSync("node", ["--experimental-strip-types", SCRIPT], { cwd: dir, encoding: "utf8" });

    const content = await readFile(join(dsDir, "data-grid.showcase.tsx"), "utf8");
    expect(content).not.toContain("No examples defined");
    // All 3 examples should be present
    expect(content).toContain("default");
    expect(content).toContain("loading");
    expect(content).toContain("with-transform");
  });

  // ── type-import carry (Cluster 2) ───────────────────────────────────────────

  const FIXTURE_TYPE_IMPORT_CARRY = resolve(
    "packs/next-react/tests/fixtures/showcase-companion-type-import-carry"
  );

  it("re-emits `import type` for type-only imports referenced in example callbacks", async () => {
    copyFixture(FIXTURE_TYPE_IMPORT_CARRY, dir, "design-system/atoms/filter-button.tsx");
    copyFixture(FIXTURE_TYPE_IMPORT_CARRY, dir, "design-system/_fixtures/handler-types.ts");

    spawnSync("node", ["--experimental-strip-types", SCRIPT], { cwd: dir, encoding: "utf8" });

    const content = await readFile(
      join(dir, "design-system/atoms/filter-button.showcase.tsx"),
      "utf8"
    );
    // The `(item: Foo) => ...` callback references Foo which is `import type`.
    // The generator must re-emit it as `import type { Foo }`.
    expect(content).toMatch(/import\s+type\s*\{[^}]*Foo[^}]*\}\s*from/);
    // The annotation itself must survive in the inlined callback
    expect(content).toContain(": Foo");
  });

  // ── typed-local inline (Cluster 2) ─────────────────────────────────────────

  const FIXTURE_TYPED_LOCAL_INLINE = resolve(
    "packs/next-react/tests/fixtures/showcase-companion-typed-local-inline"
  );

  it("inlines typed local const with annotation preserved and carries transitive type-import", async () => {
    copyFixture(FIXTURE_TYPED_LOCAL_INLINE, dir, "design-system/composites/item-list.tsx");
    copyFixture(FIXTURE_TYPED_LOCAL_INLINE, dir, "design-system/_fixtures/item-types.ts");

    spawnSync("node", ["--experimental-strip-types", SCRIPT], { cwd: dir, encoding: "utf8" });

    const content = await readFile(
      join(dir, "design-system/composites/item-list.showcase.tsx"),
      "utf8"
    );
    // The const `itemColumns: ItemColumn<Item>[]` annotation must survive — rawSource
    // preserves the TS type annotation rather than stripping it to a serialized value.
    expect(content).toMatch(/const\s+itemColumns\s*:/);
    // Arrow-fn params inside the local (render: (row) => ...) must not be stripped
    expect(content).toContain("itemColumns");
    // `Item` is a type-only import transitively referenced via the annotation on
    // itemColumns. It must be carried as `import type`.
    expect(content).toMatch(/import\s+type\s*\{[^}]*Item[^}]*\}\s*from/);
  });
});

// ── JSX-attribute / auto-children regression tests (#66, #67, #68, #73) ──────

describe("JSX attribute / children emission regressions", () => {
  let dir: string;

  beforeEach(async () => {
    dir = await fresh();
  });

  afterEach(async () => {
    await rm(dir, { recursive: true, force: true });
  });

  // ── #66 — boolean CVA axis emits {true}/{false} not "true"/"false" ────────
  it("#66 boolean CVA axis emits JSX expression form, not string", async () => {
    const dsDir = join(dir, "design-system", "atoms");
    await mkdir(dsDir, { recursive: true });
    await writeFile(
      join(dsDir, "tag.tsx"),
      [
        `import React from "react";`,
        `import { cva } from "class-variance-authority";`,
        `const v = cva("t", {`,
        `  variants: {`,
        `    tone: { neutral: "n", primary: "p" },`,
        `    selected: { true: "sel", false: "unsel" },`,
        `  },`,
        `  defaultVariants: { tone: "neutral", selected: false },`,
        `});`,
        `export function Tag(props: { tone?: "neutral" | "primary"; selected?: boolean; children?: React.ReactNode }) { return <span {...props} />; }`,
        `export const meta = { kind: "atom", examples: [{ name: "default", props: {} }], skip: [] };`,
      ].join("\n")
    );
    const r = spawnSync("node", ["--experimental-strip-types", SCRIPT], { cwd: dir, encoding: "utf8" });
    expect(r.status).toBe(0);
    const content = await readFile(join(dsDir, "tag.showcase.tsx"), "utf8");
    // Must emit JSX-expression form for boolean values
    expect(content).toContain("selected={true}");
    expect(content).toContain("selected={false}");
    // Must NOT emit string form
    expect(content).not.toContain('selected="true"');
    expect(content).not.toContain('selected="false"');
  });

  // ── #67 — boolean-shaped aria attr in CVA emits {true} not "true" ─────────
  it("#67 boolean-shaped aria-invalid axis emits JSX expression", async () => {
    const dsDir = join(dir, "design-system", "atoms");
    await mkdir(dsDir, { recursive: true });
    await writeFile(
      join(dsDir, "input-x.tsx"),
      [
        `import React from "react";`,
        `import { cva } from "class-variance-authority";`,
        `const v = cva("i", {`,
        `  variants: {`,
        `    size: { sm: "s", md: "m" },`,
        `    "aria-invalid": { true: "inv", false: "ok" },`,
        `  },`,
        `  defaultVariants: { size: "md", "aria-invalid": false },`,
        `});`,
        `export function InputX(props: any) { return <input {...props} />; }`,
        `export const meta = { kind: "atom", examples: [{ name: "default", props: {} }], skip: [] };`,
      ].join("\n")
    );
    const r = spawnSync("node", ["--experimental-strip-types", SCRIPT], { cwd: dir, encoding: "utf8" });
    expect(r.status).toBe(0);
    const content = await readFile(join(dsDir, "input-x.showcase.tsx"), "utf8");
    expect(content).toContain("aria-invalid={true}");
    expect(content).toContain("aria-invalid={false}");
    expect(content).not.toContain('aria-invalid="true"');
    expect(content).not.toContain('aria-invalid="false"');
  });

  // ── #68 — childless component renders self-closing, not text fallback ────
  it("#68 component without children prop renders self-closing", async () => {
    const dsDir = join(dir, "design-system", "atoms");
    await mkdir(dsDir, { recursive: true });
    await writeFile(
      join(dsDir, "brand-mark.tsx"),
      [
        `import React from "react";`,
        `import { cva } from "class-variance-authority";`,
        `const v = cva("b", {`,
        `  variants: {`,
        `    size: { sm: "s", md: "m" },`,
        `  },`,
        `  defaultVariants: { size: "md" },`,
        `});`,
        // No children in props type — only size
        `export function BrandMark({ size }: { size?: "sm" | "md" }) { return <svg data-size={size} />; }`,
        `export const meta = { kind: "atom", examples: [{ name: "default", props: {} }], skip: [] };`,
      ].join("\n")
    );
    const r = spawnSync("node", ["--experimental-strip-types", SCRIPT], { cwd: dir, encoding: "utf8" });
    expect(r.status).toBe(0);
    const content = await readFile(join(dsDir, "brand-mark.showcase.tsx"), "utf8");
    // Must NOT stuff displayName as text child
    expect(content).not.toContain(">BrandMark</BrandMark>");
    // Must emit self-closing form for at least one CVA combo
    expect(content).toMatch(/<BrandMark\s+size="sm"\s*\/>/);
  });

  // ── #73 — embedded escaped quotes JSX-encode (use {"..."} expression) ────
  it("#73 embedded escaped quotes in meta string emit valid JSX attribute", async () => {
    const dsDir = join(dir, "design-system", "atoms");
    await mkdir(dsDir, { recursive: true });
    await writeFile(
      join(dsDir, "echo.tsx"),
      [
        `import React from "react";`,
        `export function Echo(props: { phrase?: string }) { return <span>{props.phrase}</span>; }`,
        `export const meta = { kind: "atom", examples: [{ name: "with-quotes", props: { phrase: "say \\"hi\\"" } }], skip: [] };`,
      ].join("\n")
    );
    const r = spawnSync("node", ["--experimental-strip-types", SCRIPT], { cwd: dir, encoding: "utf8" });
    expect(r.status).toBe(0);
    const content = await readFile(join(dsDir, "echo.showcase.tsx"), "utf8");
    // Must NOT contain broken double-escaped attribute form
    expect(content).not.toContain('phrase="\\"hi\\""');
    expect(content).not.toContain('phrase="\\"');
    // Must contain valid form: either JSX expression {"say \"hi\""} or &quot;-encoded
    const hasExprForm = /phrase=\{"say \\"hi\\""\}/.test(content);
    const hasEntityForm = content.includes('phrase="say &quot;hi&quot;"');
    expect(hasExprForm || hasEntityForm).toBe(true);
  });
});
