// @generated by claude-ds — do not edit. Source: SearchBox.tsx meta block.
//
// STALE on purpose: generated against an older SearchBox that accepted a
// `placeholder` prop. The current SearchBox (SearchBox.tsx) takes only
// `{ initial?: string }`, so `placeholder` no longer typechecks. JSX-bearing →
// non-regenerable (ADR-0026); `verify` reports it as a hand-verify error.
import React from "react";
import { SearchBox } from "./SearchBox";

export default function SearchBoxShowcase() {
  return (
    <main className="p-8">
      <h1 className="text-2xl font-bold mb-6">SearchBox</h1>
      <section className="mb-10">
        <h2 className="text-xl font-semibold mb-4">Examples</h2>
        <div className="flex flex-wrap items-end gap-3">
          <div className="flex flex-col items-start gap-1">
            <SearchBox initial="" placeholder="Search…" />
            <span className="text-xs text-muted-foreground">default</span>
          </div>
        </div>
      </section>
    </main>
  );
}
