#!/usr/bin/env node --experimental-strip-types
/**
 * build-manifest.ts — Generates design-system/manifest.json AND
 * design-system/manifest.generated.ts.
 *
 * manifest.json — JSON index of every component bundle found in
 *   design-system/{atoms,composites,references,icons,hooks,utils}/.
 *   Shape:
 *     { generated: "<ISO>",
 *       components: [{ name, tier, kind, path, path_no_ext, has_showcase, has_states, has_test }] }
 *
 * manifest.generated.ts — Static TypeScript module with one named import per
 *   .showcase.tsx file. All imports are RELATIVE to design-system/ so they
 *   resolve correctly regardless of the consumer's tsconfig @/* alias
 *   (works in both app/ and src/app/ Next.js layouts). The catch-all
 *   /design/[...slug] page imports from this module instead of using a
 *   dynamic @/ import, which fixes build errors in src/app consumers (#52).
 *
 * `kind` is parsed from `export const meta = { kind: "..." }` in each .tsx.
 * When meta is missing or unparseable, kind is inferred from the directory
 * (atoms→atom, composites→composite, references→reference) and a stderr
 * warning is printed. Cleanup path is `reconform --backfill-meta`.
 *
 * Exit 0 success, 1 self-error.
 */

import { readdirSync, existsSync, readFileSync, writeFileSync } from "node:fs";
import { join, basename, extname } from "node:path";

const TIERS: Record<string, string> = {
  atoms: "atom",
  composites: "composite",
};

type ComponentKind = "atom" | "composite" | "reference";

const DIR_KIND: Record<string, ComponentKind> = {
  atoms: "atom",
  composites: "composite",
  references: "reference",
};

const SCAN_DIRS = ["atoms", "composites", "references", "icons", "hooks", "utils"];

interface ComponentEntry {
  name: string;
  tier: string;
  kind?: ComponentKind;
  path: string;
  path_no_ext: string;
  has_showcase: boolean;
  has_states: boolean;
  has_test: boolean;
}

function parseKind(source: string): ComponentKind | null {
  const m = source.match(/export\s+const\s+meta[^=]*=\s*\{[^}]*kind\s*:\s*["']([^"']+)["']/);
  if (!m) return null;
  const k = m[1];
  return k === "atom" || k === "composite" || k === "reference" ? k : null;
}

function scanDir(dsRoot: string, dirName: string): ComponentEntry[] {
  const dir = join(dsRoot, dirName);
  if (!existsSync(dir)) return [];

  let entries: string[];
  try {
    entries = readdirSync(dir);
  } catch {
    return [];
  }

  const tier = TIERS[dirName] ?? dirName;
  const inferredKind = DIR_KIND[dirName];
  const tsxFiles = entries.filter(
    (f) => f.endsWith(".tsx") && !f.endsWith(".showcase.tsx") && !f.endsWith(".test.tsx")
  );

  return tsxFiles.map((f) => {
    const name = basename(f, extname(f));
    const base = join(dir, name);
    const path = `design-system/${dirName}/${f}`;
    const path_no_ext = `design-system/${dirName}/${name}`;

    let kind: ComponentKind | undefined;
    if (inferredKind) {
      let parsed: ComponentKind | null = null;
      try {
        parsed = parseKind(readFileSync(join(dir, f), "utf8"));
      } catch {
        parsed = null;
      }
      if (parsed) {
        kind = parsed;
      } else {
        process.stderr.write(
          `${path}:0: MFST-002: meta.kind missing or unparseable; inferring "${inferredKind}" from directory. Run reconform --backfill-meta to fix.\n`
        );
        kind = inferredKind;
      }
    }

    return {
      name,
      tier,
      ...(kind ? { kind } : {}),
      path,
      path_no_ext,
      has_showcase: existsSync(`${base}.showcase.tsx`),
      has_states: existsSync(`${base}.states.json`),
      has_test: existsSync(`${base}.test.tsx`),
    };
  });
}

/**
 * Emit design-system/manifest.generated.ts — a static module with one import
 * per .showcase.tsx, exported as a Record keyed by "section/name".
 *
 * Imports are RELATIVE to design-system/ so they work in both app/ and
 * src/app/ consumer layouts without any @/ alias dependency (#52).
 */
function emitGeneratedModule(dsRoot: string, components: ComponentEntry[]): void {
  const withShowcase = components
    .filter((c) => c.has_showcase)
    .sort((a, b) => a.path_no_ext.localeCompare(b.path_no_ext));

  const lines: string[] = [
    "// !! DO NOT EDIT — generated by scripts/build-manifest.ts !!",
    "// Re-run `npm run ds:build-manifest` to update.",
    "import type React from \"react\";",
    "",
  ];

  // Collect import identifiers: path_no_ext is "design-system/atoms/Button"
  // The relative path from design-system/ is "./atoms/Button.showcase"
  const imports: Array<{ id: string; rel: string; key: string }> = [];
  for (const c of withShowcase) {
    // path_no_ext: "design-system/atoms/Button" → strip "design-system/" prefix
    const rel = "./" + c.path_no_ext.replace(/^design-system\//, "") + ".showcase";
    // key: "atoms/button" (section/name, lower-cased for URL slug matching)
    const key = c.path_no_ext.replace(/^design-system\//, "");
    // identifier: safe JS name from path ("atoms/Button" → "atoms_Button_showcase")
    const id = key.replace(/[^a-zA-Z0-9]/g, "_") + "_showcase";
    imports.push({ id, rel, key });
  }

  for (const { id, rel } of imports) {
    lines.push(`import ${id} from "${rel}";`);
  }

  lines.push("");
  lines.push("/** Showcase components keyed by \"section/ComponentName\" slug. */");
  lines.push("export const showcases: Record<string, React.ComponentType> = {");
  for (const { id, key } of imports) {
    lines.push(`  "${key}": ${id},`);
  }
  lines.push("};");
  lines.push("");

  const outPath = join(dsRoot, "manifest.generated.ts");
  try {
    writeFileSync(outPath, lines.join("\n"), "utf8");
  } catch (err) {
    process.stderr.write(`${outPath}:0: MFST-001: failed to write manifest.generated.ts: ${err}\n`);
    process.exit(1);
  }

  console.log(`build-manifest: wrote ${imports.length} showcase(s) to ${outPath}`);
}

function main(): void {
  const cwd = process.cwd();
  const dsRoot = join(cwd, "design-system");

  if (!existsSync(dsRoot)) {
    process.stderr.write(`${dsRoot}:0: MFST-000: design-system/ directory not found\n`);
    process.exit(1);
  }

  const components: ComponentEntry[] = [];
  for (const dir of SCAN_DIRS) {
    components.push(...scanDir(dsRoot, dir));
  }

  const manifest = {
    generated: new Date().toISOString(),
    components,
  };

  const outPath = join(dsRoot, "manifest.json");
  try {
    writeFileSync(outPath, JSON.stringify(manifest, null, 2) + "\n", "utf8");
  } catch (err) {
    process.stderr.write(`${outPath}:0: MFST-001: failed to write manifest: ${err}\n`);
    process.exit(1);
  }

  console.log(`build-manifest: wrote ${components.length} component(s) to ${outPath}`);

  emitGeneratedModule(dsRoot, components);
}

main();
