#!/usr/bin/env node --experimental-strip-types
/**
 * generate-showcase.ts — Generates the app/_design/ route tree from design-system/manifest.json.
 *
 * Emits:
 *   app/_design/page.tsx              — index of all components in manifest
 *   app/_design/[component]/page.tsx  — per-component render (imports .tsx + .showcase.tsx + .states.json)
 *   app/_design/tokens/page.tsx       — token visualizer from design-system/tokens.json
 *   app/_design/motion/page.tsx       — motion tokens / animation examples
 *
 * Usage: node --experimental-strip-types scripts/generate-showcase.ts
 *        (or: tsx scripts/generate-showcase.ts)
 *
 * Exit 0 success, 1 self-error.
 */

import { existsSync, mkdirSync, readFileSync, writeFileSync } from "node:fs";
import { join, dirname } from "node:path";

interface ManifestComponent {
  name: string;
  tier: string;
  path: string;
  has_showcase: boolean;
  has_states: boolean;
  has_snapshot: boolean;
  has_test: boolean;
}

interface Manifest {
  generated: string;
  components: ManifestComponent[];
}

function ensureDir(filePath: string): void {
  mkdirSync(dirname(filePath), { recursive: true });
}

function write(filePath: string, content: string): void {
  ensureDir(filePath);
  writeFileSync(filePath, content, "utf8");
}

// ── page templates ──────────────────────────────────────────────────────────

function indexPage(components: ManifestComponent[]): string {
  const rows = components
    .map(
      (c) =>
        `      <li key="${c.name}">` +
        `<a href={\`/_design/${c.name}\`} className="underline">${c.name}</a>` +
        ` <span className="text-xs text-muted-foreground">{/* ${c.tier} */}</span>` +
        `</li>`
    )
    .join("\n");

  return `// GENERATED by scripts/generate-showcase.ts — do not edit by hand.
// Re-run "npm run generate:showcase" (or let post-write-design.sh do it) to refresh.
import React from "react";
import Link from "next/link";

export default function DesignIndexPage() {
  return (
    <main className="p-8">
      <h1 className="text-2xl font-bold mb-4">Design System — Component Index</h1>
      <nav>
        <ul className="space-y-2">
${rows}
          <li>
            <Link href="/_design/tokens" className="underline">
              Tokens
            </Link>
          </li>
          <li>
            <Link href="/_design/motion" className="underline">
              Motion
            </Link>
          </li>
        </ul>
      </nav>
    </main>
  );
}
`;
}

function componentPage(component: ManifestComponent): string {
  // Derive relative import path from app/_design/[component]/ back to design-system/
  // In a Next.js project the design-system sits at the repo root; we use a path alias
  // @/design-system (standard Next.js convention) if available, else a relative path.
  const tierDir = component.path.split("/").slice(0, 2).join("/"); // e.g. design-system/atoms
  const importBase = `@/${tierDir}/${component.name}`;

  const showcaseImport = component.has_showcase
    ? `import ${component.name}Showcase from "${importBase}.showcase";`
    : "";
  const statesImport = component.has_states
    ? `import states from "${importBase}.states.json";`
    : "";

  const showcaseSection = component.has_showcase
    ? `
      <section className="mt-8">
        <h2 className="text-lg font-semibold mb-2">Showcase</h2>
        <${component.name}Showcase />
      </section>`
    : "";

  const statesSection = component.has_states
    ? `
      <section className="mt-8">
        <h2 className="text-lg font-semibold mb-2">States</h2>
        <pre className="bg-muted rounded p-4 text-sm overflow-auto">
          {JSON.stringify(states, null, 2)}
        </pre>
      </section>`
    : "";

  return `// GENERATED by scripts/generate-showcase.ts — do not edit by hand.
import React from "react";
import ${component.name} from "${importBase}";
${showcaseImport}
${statesImport}

export default function ${component.name}ShowcasePage() {
  return (
    <main className="p-8">
      <h1 className="text-2xl font-bold mb-2">${component.name}</h1>
      <p className="text-sm text-muted-foreground mb-6">Tier: ${component.tier}</p>

      <section>
        <h2 className="text-lg font-semibold mb-2">Component</h2>
        <div className="border rounded p-4">
          <${component.name} />
        </div>
      </section>
${showcaseSection}
${statesSection}
    </main>
  );
}
`;
}

function tokensPage(tokensJson: unknown): string {
  const pretty = JSON.stringify(tokensJson, null, 2);
  // Escape backticks for template literal safety
  const escaped = pretty.replace(/`/g, "\\`").replace(/\$/g, "\\$");

  return `// GENERATED by scripts/generate-showcase.ts — do not edit by hand.
import React from "react";

const tokens = ${pretty} as const;

type TokenEntry = { name: string; value: string };

function flattenTokens(obj: Record<string, unknown>, prefix = ""): TokenEntry[] {
  return Object.entries(obj).flatMap(([key, val]) => {
    const name = prefix ? \`\${prefix}.\${key}\` : key;
    if (val && typeof val === "object" && !Array.isArray(val)) {
      return flattenTokens(val as Record<string, unknown>, name);
    }
    return [{ name, value: String(val) }];
  });
}

export default function TokensPage() {
  const entries = flattenTokens(tokens as unknown as Record<string, unknown>);
  return (
    <main className="p-8">
      <h1 className="text-2xl font-bold mb-6">Design Tokens</h1>
      <table className="w-full text-sm border-collapse">
        <thead>
          <tr className="text-left border-b">
            <th className="pb-2 pr-4">Token</th>
            <th className="pb-2 pr-4">Value</th>
            <th className="pb-2">Preview</th>
          </tr>
        </thead>
        <tbody>
          {entries.map((t) => (
            <tr key={t.name} className="border-b">
              <td className="py-1 pr-4 font-mono">{t.name}</td>
              <td className="py-1 pr-4 font-mono text-muted-foreground">{t.value}</td>
              <td className="py-1">
                {t.name.includes("color") || t.name.includes("Color") ? (
                  <span
                    className="inline-block w-6 h-6 rounded border"
                    style={{ backgroundColor: t.value }}
                  />
                ) : null}
              </td>
            </tr>
          ))}
        </tbody>
      </table>
    </main>
  );
}
`;
}

function motionPage(tokensJson: unknown): string {
  // Extract motion-related tokens (keys containing "duration", "easing", "motion", "transition", "animation")
  const MOTION_KEYS = ["duration", "easing", "motion", "transition", "animation", "timing"];
  const motionFilter = (key: string) =>
    MOTION_KEYS.some((k) => key.toLowerCase().includes(k));

  function extractMotion(
    obj: Record<string, unknown>,
    prefix = ""
  ): Array<{ name: string; value: string }> {
    return Object.entries(obj).flatMap(([key, val]) => {
      const name = prefix ? `${prefix}.${key}` : key;
      if (val && typeof val === "object" && !Array.isArray(val)) {
        return extractMotion(val as Record<string, unknown>, name);
      }
      if (motionFilter(name)) {
        return [{ name, value: String(val) }];
      }
      return [];
    });
  }

  const tokensObj =
    tokensJson && typeof tokensJson === "object" && !Array.isArray(tokensJson)
      ? (tokensJson as Record<string, unknown>)
      : {};

  const motionEntries = extractMotion(tokensObj);
  const entriesJson = JSON.stringify(motionEntries, null, 2);

  return `// GENERATED by scripts/generate-showcase.ts — do not edit by hand.
import React from "react";

const MOTION_TOKENS = ${entriesJson} as const;

export default function MotionPage() {
  return (
    <main className="p-8">
      <h1 className="text-2xl font-bold mb-6">Motion Tokens</h1>
      {MOTION_TOKENS.length === 0 ? (
        <p className="text-muted-foreground">
          No motion tokens found in design-system/tokens.json.
          Add keys containing "duration", "easing", "motion", "transition", or "animation".
        </p>
      ) : (
        <>
          <table className="w-full text-sm border-collapse mb-8">
            <thead>
              <tr className="text-left border-b">
                <th className="pb-2 pr-4">Token</th>
                <th className="pb-2">Value</th>
              </tr>
            </thead>
            <tbody>
              {MOTION_TOKENS.map((t) => (
                <tr key={t.name} className="border-b">
                  <td className="py-1 pr-4 font-mono">{t.name}</td>
                  <td className="py-1 font-mono text-muted-foreground">{t.value}</td>
                </tr>
              ))}
            </tbody>
          </table>

          <section>
            <h2 className="text-lg font-semibold mb-4">Animation Demo</h2>
            <div className="flex gap-4 flex-wrap">
              {MOTION_TOKENS.filter((t) => t.name.toLowerCase().includes("duration")).map((t) => (
                <div
                  key={t.name}
                  className="border rounded p-4 text-center"
                  style={{ animationDuration: t.value }}
                >
                  <div
                    className="w-8 h-8 bg-primary rounded animate-spin mx-auto mb-2"
                    style={{ animationDuration: t.value }}
                  />
                  <code className="text-xs">{t.name}</code>
                  <p className="text-xs text-muted-foreground">{t.value}</p>
                </div>
              ))}
            </div>
          </section>
        </>
      )}
    </main>
  );
}
`;
}

// ── main ────────────────────────────────────────────────────────────────────

function main(): void {
  const cwd = process.cwd();
  const manifestPath = join(cwd, "design-system", "manifest.json");
  const tokensPath = join(cwd, "design-system", "tokens.json");
  const designDir = join(cwd, "app", "_design");

  if (!existsSync(manifestPath)) {
    process.stderr.write(
      `${manifestPath}:0: SHOWCASE-000: design-system/manifest.json not found — run npm run ds:build-manifest first\n`
    );
    process.exit(1);
  }

  let manifest: Manifest;
  try {
    manifest = JSON.parse(readFileSync(manifestPath, "utf8")) as Manifest;
  } catch (err) {
    process.stderr.write(
      `${manifestPath}:0: SHOWCASE-001: failed to parse manifest.json: ${err}\n`
    );
    process.exit(1);
  }

  const components: ManifestComponent[] = manifest.components ?? [];

  let tokensJson: unknown = {};
  if (existsSync(tokensPath)) {
    try {
      tokensJson = JSON.parse(readFileSync(tokensPath, "utf8"));
    } catch {
      // non-fatal — tokens page will just show empty
    }
  }

  // 1. Index page
  const indexPath = join(designDir, "page.tsx");
  write(indexPath, indexPage(components));
  console.log(`generate-showcase: wrote ${indexPath}`);

  // 2. Per-component pages
  for (const component of components) {
    const compPath = join(designDir, component.name, "page.tsx");
    write(compPath, componentPage(component));
    console.log(`generate-showcase: wrote ${compPath}`);
  }

  // 3. Tokens page
  const tokensPagePath = join(designDir, "tokens", "page.tsx");
  write(tokensPagePath, tokensPage(tokensJson));
  console.log(`generate-showcase: wrote ${tokensPagePath}`);

  // 4. Motion page
  const motionPagePath = join(designDir, "motion", "page.tsx");
  write(motionPagePath, motionPage(tokensJson));
  console.log(`generate-showcase: wrote ${motionPagePath}`);

  const total = 2 + components.length + 2; // index + components + tokens + motion — actually 4 fixed + components
  console.log(
    `generate-showcase: done — ${components.length} component page(s) + index + tokens + motion`
  );
}

main();
