#!/usr/bin/env node --experimental-strip-types
// NOTE (v0.7.6+): `meta.examples: []` is an authoritative stub signal — generator emits a placeholder card and skips CVA auto-expansion.
/**
 * generate-showcase-companion.ts — Generates per-component .showcase.tsx
 * from the `meta` export in each design-system component source file.
 *
 * Emits for each .tsx under design-system/{atoms,composites,references}/:
 *   <name>.showcase.tsx    — JSX that renders all examples (with @generated header)
 *
 * For kind "atom" | "composite": renders each examples[] entry with props spread.
 *   If cva() is detected in source, also auto-expands the CVA variant cross-product.
 *   Suppresses combos listed in skip[].
 * For kind "reference": renders meta.render() call.
 *
 * Usage: node --experimental-strip-types scripts/generate-showcase-companion.ts
 *        (or: tsx scripts/generate-showcase-companion.ts)
 *
 * Exit 0 success, 1 self-error.
 */

import { existsSync, mkdirSync, readFileSync, readdirSync, statSync, writeFileSync } from "node:fs";
import { join, dirname, basename, resolve as resolvePath } from "node:path";
import { createRequire } from "node:module";
import { fileURLToPath } from "node:url";
import type * as TS from "typescript";

// ── typescript loader (optional — falls back to regex parseMeta if absent) ────
// Resolved at runtime from the script's own location so it works when the
// script is copied into consumer projects that may lack "typescript" in
// their own node_modules. We walk up from the script directory looking for
// a resolvable "typescript" package.
let tsRuntime: typeof TS | null = null;
(function loadTypescript() {
  // Try each candidate directory from script location upward
  const scriptDir = dirname(fileURLToPath(import.meta.url));
  let dir = scriptDir;
  for (let i = 0; i < 12; i++) {
    try {
      const req = createRequire(join(dir, "package.json"));
      tsRuntime = req("typescript") as typeof TS;
      return;
    } catch {
      const parent = dirname(dir);
      if (parent === dir) break;
      dir = parent;
    }
  }
  // Last resort: absolute require (works if typescript is in PATH's node_modules)
  try {
    const req = createRequire(import.meta.url);
    tsRuntime = req("typescript") as typeof TS;
  } catch {
    // tsRuntime stays null; extractMetaFromAST will return null and regex fallback takes over
  }
})();

// Non-null accessor for AST functions. They are only reachable when tsRuntime
// loaded successfully (extractMetaFromAST guards with `if (!tsRuntime) return null`
// before any AST helper runs), so this throw is defensive — present to satisfy
// the type checker, not expected to fire at runtime.
function getTS(): typeof TS {
  if (!tsRuntime) throw new Error("typescript not resolvable — AST path unavailable");
  return tsRuntime;
}

// ── header constants ──────────────────────────────────────────────────────────

function showcaseHeader(sourceName: string): string {
  return `// @generated by claude-ds — do not edit. Source: ${sourceName} meta block.`;
}

// ── helpers ───────────────────────────────────────────────────────────────────

function toPascalCase(name: string): string {
  return name
    .split(/[-_\s]+/)
    .filter(Boolean)
    .map((segment) => segment.charAt(0).toUpperCase() + segment.slice(1))
    .join("");
}

function ensureDir(filePath: string): void {
  mkdirSync(dirname(filePath), { recursive: true });
}

function write(filePath: string, content: string): void {
  ensureDir(filePath);
  writeFileSync(filePath, content, "utf8");
}

/**
 * Detect whether a source file has a default export.
 * Strips line/block comments and string literals first to avoid false positives
 * from "export default" appearing in comments or string values.
 */
function hasDefaultExport(source: string): boolean {
  // Strip block comments
  let stripped = source.replace(/\/\*[\s\S]*?\*\//g, "");
  // Strip line comments
  stripped = stripped.replace(/\/\/[^\n]*/g, "");
  // Strip string literals
  stripped = stripped
    .replace(/"(?:[^"\\]|\\.)*"/g, '""')
    .replace(/'(?:[^'\\]|\\.)*'/g, "''")
    .replace(/`(?:[^`\\]|\\.)*`/g, "``");
  return /^\s*export\s+default\s+/m.test(stripped);
}

/**
 * Strip all string literals (double-quoted, single-quoted, template literals)
 * from a block of source text. Used before scanning for CVA variant keys so
 * that Tailwind modifier prefixes like `hover:`, `focus:`, `aria-expanded:`
 * inside class strings are not mistaken for variant names.
 */
function stripStringLiterals(text: string): string {
  // Replace double-quoted strings
  let result = text.replace(/"(?:[^"\\]|\\.)*"/g, '""');
  // Replace single-quoted strings
  result = result.replace(/'(?:[^'\\]|\\.)*'/g, "''");
  // Replace template literals (simple, non-nested)
  result = result.replace(/`(?:[^`\\]|\\.)*`/g, "``");
  return result;
}

/**
 * Generate a human-readable label from a combo key like "intent=primary_size=sm".
 * Output: "Primary · sm"  (title-case first axis value, keep remaining as-is)
 */
function prettyLabel(comboKey: string): string {
  return comboKey
    .split("_")
    .map((part) => {
      const eqIdx = part.indexOf("=");
      const value = eqIdx >= 0 ? part.slice(eqIdx + 1) : part;
      // Title-case the first character
      return value.charAt(0).toUpperCase() + value.slice(1);
    })
    .join(" · ");
}

// ── meta parsing ──────────────────────────────────────────────────────────────

interface Example {
  name: string;
  props: Record<string, unknown>;
}

interface MetaAtomComposite {
  kind: "atom" | "composite";
  fixtures?: Record<string, unknown>;
  examples: Example[];
  skip?: string[];
}

interface MetaReference {
  kind: "reference";
  title: string;
}

type ParsedMeta = MetaAtomComposite | MetaReference;

// ── AST-based meta extractor (A3) ────────────────────────────────────────────

/**
 * Marker for function source text extracted via AST. The JSX serializer
 * recognises this and emits the raw source inside `{...}` instead of
 * JSON-encoding a string.
 */
interface FnMarker {
  __fn: string;
}
function isFnMarker(v: unknown): v is FnMarker {
  return typeof v === "object" && v !== null && "__fn" in v && typeof (v as FnMarker).__fn === "string";
}

/**
 * A reference that must be carried from the source file into the generated
 * showcase because a captured FnMarker (arrow body, .map() call, conditional, etc.)
 * references it as a free identifier.
 *
 * - "import": re-emit the same value import in the showcase (paths are identical
 *   because showcase sits beside the source).
 * - "type-import": re-emit as `import type { … }` — type-only imports are never
 *   runtime values but must be present for TypeScript annotations to compile.
 * - "local": inline the full VariableStatement verbatim (rawSource) so type
 *   annotations on the const (and any nested arrow bodies) survive in the showcase.
 */
type CarriedRef =
  | { kind: "import"; localName: string; exportedName: string; rawSpec: string }
  | { kind: "type-import"; localName: string; exportedName: string; rawSpec: string }
  | { kind: "local"; name: string; rawSource: string };

/** Resolve `@/` import prefixes using tsconfig.json paths, falling back to `./src`. */
function resolveAtPrefix(importPath: string, consumerRoot: string): string {
  try {
    const tsconfigPath = join(consumerRoot, "tsconfig.json");
    if (existsSync(tsconfigPath)) {
      const raw = JSON.parse(readFileSync(tsconfigPath, "utf8")) as {
        compilerOptions?: { paths?: Record<string, string[]> };
      };
      const paths = raw.compilerOptions?.paths ?? {};
      // Sort longest pattern first so more-specific prefixes (e.g. "@/design-system/*")
      // beat shorter ones (e.g. "@/*") when both would match.
      const sortedEntries = Object.entries(paths).sort(([a], [b]) => b.length - a.length);
      for (const [pattern, targets] of sortedEntries) {
        const prefix = pattern.replace(/\/\*$/, "/");
        if (importPath.startsWith(prefix) && targets[0]) {
          const mapped = targets[0].replace(/\/\*$/, "/").replace(/^\.\//, "");
          const result = importPath.replace(prefix, mapped + "/").replace(/\/+/g, "/");
          // Strip any accidental leading "/" that would be misread as a filesystem root.
          // e.g. when targets[0] = "./*" the replacement produces "/foo" instead of "foo".
          return result.startsWith("/") ? result.slice(1) : result;
        }
      }
    }
  } catch {
    // ignore
  }
  // Default: @/ → ./src/
  return importPath.replace(/^@\//, "src/");
}

/**
 * Given an absolute file path, try to find the shortest `@/…` alias specifier
 * that refers to it under the consumer's tsconfig path mappings.
 * Returns `null` if no alias covers the file.
 */
function filePathToAlias(absoluteFilePath: string, consumerRoot: string): string | null {
  try {
    const tsconfigPath = join(consumerRoot, "tsconfig.json");
    if (!existsSync(tsconfigPath)) return null;
    const raw = JSON.parse(readFileSync(tsconfigPath, "utf8")) as {
      compilerOptions?: { paths?: Record<string, string[]> };
    };
    const paths = raw.compilerOptions?.paths ?? {};
    // Sort longest target first so more-specific aliases win.
    const sortedEntries = Object.entries(paths).sort(([, a], [, b]) => b[0].length - a[0].length);
    // Canonicalise inputs: resolve both through node:path.resolve so that
    // symlinked prefixes (e.g. /tmp → /private/tmp on macOS) don't cause
    // false-negative prefix checks.
    const canonicalFile = resolvePath(absoluteFilePath);
    const canonicalRoot = resolvePath(consumerRoot);
    for (const [pattern, targets] of sortedEntries) {
      if (!pattern.includes("*") || !targets[0]) continue;
      const aliasPrefix = pattern.replace(/\/\*$/, "/");
      if (!aliasPrefix.startsWith("@/")) continue; // only @/ aliases
      // Resolve the target glob to an absolute directory
      const targetRelDir = targets[0].replace(/\/\*$/, "").replace(/^\.\//, "");
      const targetAbsDir = targetRelDir ? resolvePath(canonicalRoot, targetRelDir) : canonicalRoot;
      // Strip any trailing "/" for normalised comparison
      const normalTarget = targetAbsDir.replace(/\/$/, "");
      if (canonicalFile.startsWith(normalTarget + "/")) {
        const rest = canonicalFile.slice(normalTarget.length + 1);
        // Drop known TS extensions — the alias specifier shouldn't include them
        const noExt = rest.replace(/\.(tsx?|d\.ts)$/, "");
        return aliasPrefix + noExt;
      }
    }
  } catch {
    // ignore
  }
  return null;
}


/**
 * Translate a TS AST node into a plain-JS value suitable for the JSX emitter.
 * Functions become `{ __fn: "<source text>" }` markers.
 * Identifier references are resolved by walking `localScope` first, then
 * single-hop importing from sibling files.
 */
function astNodeToValue(
  node: TS.Node,
  sourceFile: TS.SourceFile,
  localScope: Map<string, TS.Node>,
  importScope: Map<string, { filePath: string; exportName: string; rawSpec: string }>,
  consumerRoot: string,
  carried: Map<string, CarriedRef>,
  depth = 0,
  typeImportScope: Map<string, { exportName: string; rawSpec: string }> = new Map()
): unknown {
  if (depth > 20) return null; // guard against deep cycles
  const ts = getTS();

  // Helper: capture an AST sub-tree as a raw-source FnMarker AND collect any
  // free identifiers it references so the showcase can carry imports/locals.
  const emitFn = (n: TS.Node): FnMarker => {
    const raw = sourceFile.text.slice(n.getStart(sourceFile), n.end).trim();
    collectRefsFromNode(n, sourceFile, localScope, importScope, typeImportScope, new Set(), carried, consumerRoot);
    return { __fn: raw };
  };

  if (ts.isStringLiteral(node)) return node.text;
  if (ts.isNumericLiteral(node)) return Number(node.text);
  if (node.kind === ts.SyntaxKind.TrueKeyword) return true;
  if (node.kind === ts.SyntaxKind.FalseKeyword) return false;
  if (node.kind === ts.SyntaxKind.NullKeyword) return null;
  if (node.kind === ts.SyntaxKind.UndefinedKeyword) return undefined;

  // Template literals — only plain (no substitutions) → string
  if (ts.isNoSubstitutionTemplateLiteral(node)) return node.text;
  if (ts.isTemplateExpression(node)) {
    process.stderr.write(
      `generate-showcase-companion [AST]: template literal with substitutions — dropping example\n`
    );
    return null;
  }

  // Arrow functions / function expressions → capture as source text
  if (ts.isArrowFunction(node) || ts.isFunctionExpression(node)) {
    return emitFn(node);
  }

  // Identifier — resolve from local scope or import scope
  if (ts.isIdentifier(node)) {
    const name = node.text;
    // `undefined` in value position is parsed as an Identifier by TypeScript,
    // not as UndefinedKeyword (which only appears in type positions). Handle it
    // explicitly so props like `reference: undefined` round-trip correctly instead
    // of being dropped with an "unresolved identifier" warning and rendered as null.
    if (name === "undefined") return undefined;
    if (localScope.has(name)) {
      return astNodeToValue(localScope.get(name)!, sourceFile, localScope, importScope, consumerRoot, carried, depth + 1, typeImportScope);
    }
    if (importScope.has(name)) {
      const imp = importScope.get(name)!;
      return resolveImportedValue(imp.filePath, imp.exportName, consumerRoot, carried, depth + 1);
    }
    // unknown identifier — skip with warning
    process.stderr.write(
      `generate-showcase-companion [AST]: unresolved identifier "${name}" — dropping value\n`
    );
    return null;
  }

  // Array literal
  if (ts.isArrayLiteralExpression(node)) {
    const result: unknown[] = [];
    for (const el of node.elements) {
      if (ts.isSpreadElement(el)) {
        // Try to expand spread by evaluating the expression
        const spread = astNodeToValue(el.expression, sourceFile, localScope, importScope, consumerRoot, carried, depth + 1, typeImportScope);
        if (Array.isArray(spread)) {
          result.push(...spread);
          continue;
        }
        // Non-array spread (e.g. fn marker from .map()) — emit as fn marker for whole array
        process.stderr.write(
          `generate-showcase-companion [AST]: spread element in array could not be expanded — skipping\n`
        );
        continue;
      }
      result.push(astNodeToValue(el, sourceFile, localScope, importScope, consumerRoot, carried, depth + 1, typeImportScope));
    }
    return result;
  }

  // Object literal
  if (ts.isObjectLiteralExpression(node)) {
    const result: Record<string, unknown> = {};
    for (const prop of node.properties) {
      if (ts.isPropertyAssignment(prop)) {
        const key = ts.isStringLiteral(prop.name)
          ? prop.name.text
          : ts.isIdentifier(prop.name)
          ? prop.name.text
          : null;
        if (key === null) {
          process.stderr.write(
            `generate-showcase-companion [AST]: computed property key — skipping\n`
          );
          continue;
        }
        result[key] = astNodeToValue(prop.initializer, sourceFile, localScope, importScope, consumerRoot, carried, depth + 1, typeImportScope);
      } else if (ts.isShorthandPropertyAssignment(prop)) {
        const name = prop.name.text;
        result[name] = astNodeToValue(prop.name, sourceFile, localScope, importScope, consumerRoot, carried, depth + 1, typeImportScope);
      } else if (ts.isSpreadAssignment(prop)) {
        const spread = astNodeToValue(prop.expression, sourceFile, localScope, importScope, consumerRoot, carried, depth + 1, typeImportScope);
        if (typeof spread === "object" && spread !== null && !Array.isArray(spread) && !isFnMarker(spread)) {
          Object.assign(result, spread);
        } else {
          process.stderr.write(
            `generate-showcase-companion [AST]: spread in object — skipping\n`
          );
        }
      } else if (ts.isMethodDeclaration(prop) || ts.isGetAccessorDeclaration(prop)) {
        const key = ts.isIdentifier(prop.name) ? prop.name.text : null;
        if (key) {
          result[key] = emitFn(prop);
        }
      }
    }
    return result;
  }

  // Property access — e.g. `contact.phoneE164` where `contact` is a module-scope
  // const object literal. Resolve the target, then index by the property name.
  // Issue #71: previously fell through to the "unhandled node kind" branch and
  // emitted null, breaking non-nullable prop types in the generated showcase.
  if (ts.isPropertyAccessExpression(node)) {
    const target = astNodeToValue(node.expression, sourceFile, localScope, importScope, consumerRoot, carried, depth + 1, typeImportScope);
    const key = node.name.text;
    if (target && typeof target === "object" && !Array.isArray(target) && !isFnMarker(target)) {
      const obj = target as Record<string, unknown>;
      if (key in obj) return obj[key];
    }
    // Couldn't resolve — emit the expression verbatim as a fn marker so the
    // showcase at least carries the reference. collectRefsFromNode will pull
    // in any free identifiers (e.g. the target `contact`).
    return emitFn(node);
  }

  // Element access — e.g. `acmeNotifications[0]` where the target is a known
  // module-scope const array. Resolve target + index; fall back to verbatim
  // emission if either side can't be evaluated. Issue #72.
  if (ts.isElementAccessExpression(node)) {
    const target = astNodeToValue(node.expression, sourceFile, localScope, importScope, consumerRoot, carried, depth + 1, typeImportScope);
    const index = astNodeToValue(node.argumentExpression, sourceFile, localScope, importScope, consumerRoot, carried, depth + 1, typeImportScope);
    if (Array.isArray(target) && typeof index === "number" && Number.isInteger(index) && index >= 0 && index < target.length) {
      return target[index];
    }
    if (target && typeof target === "object" && !Array.isArray(target) && !isFnMarker(target) && typeof index === "string") {
      const obj = target as Record<string, unknown>;
      if (index in obj) return obj[index];
    }
    return emitFn(node);
  }

  // `new Foo(...)` — emit verbatim as a fn marker. Most commonly `new Date("...")`.
  // Issue #72: previously fell through to "unhandled node kind" and dropped to null.
  if (ts.isNewExpression(node)) {
    return emitFn(node);
  }

  // Call expressions — e.g. `jobColumns.map(...)` or `acmeJobs.slice(...)`
  if (ts.isCallExpression(node)) {
    // Try to evaluate simple identifier.method() calls for known array methods
    const expr = node.expression;
    if (ts.isPropertyAccessExpression(expr)) {
      const objNode = expr.expression;
      const method = expr.name.text;
      const obj = astNodeToValue(objNode, sourceFile, localScope, importScope, consumerRoot, carried, depth + 1, typeImportScope);
      if (Array.isArray(obj)) {
        if (method === "slice" && node.arguments.length <= 2) {
          const args = node.arguments.map((a) => astNodeToValue(a, sourceFile, localScope, importScope, consumerRoot, carried, depth + 1, typeImportScope)) as number[];
          return obj.slice(args[0], args[1]);
        }
        if (method === "map" && node.arguments.length === 1) {
          const mapper = node.arguments[0];
          if (ts.isArrowFunction(mapper) || ts.isFunctionExpression(mapper)) {
            // Can't evaluate the mapper in a JS-free context; emit raw call as fn marker
            return emitFn(node);
          }
        }
        if (method === "concat" && node.arguments.length > 0) {
          return emitFn(node);
        }
      }
    }
    // fallback: emit as a function marker (raw call expression)
    return emitFn(node);
  }

  // Binary expressions, conditional, etc. — emit as fn marker
  if (
    ts.isBinaryExpression(node) ||
    ts.isConditionalExpression(node) ||
    ts.isPrefixUnaryExpression(node)
  ) {
    return emitFn(node);
  }

  // AsExpression (type cast) — unwrap and recurse
  if (ts.isAsExpression(node)) {
    return astNodeToValue(node.expression, sourceFile, localScope, importScope, consumerRoot, carried, depth + 1, typeImportScope);
  }

  // ParenthesizedExpression — unwrap
  if (ts.isParenthesizedExpression(node)) {
    return astNodeToValue(node.expression, sourceFile, localScope, importScope, consumerRoot, carried, depth + 1, typeImportScope);
  }

  // JSX elements (<Foo />, <Foo>...</Foo>) — emit as raw source FnMarker so the
  // showcase can splice them as JSX expressions. Identifiers inside the JSX
  // (tag names, imported components like <Send />) get collected into carried so
  // the showcase emits the necessary imports.
  if (
    ts.isJsxElement(node) ||
    ts.isJsxSelfClosingElement(node) ||
    ts.isJsxFragment(node)
  ) {
    return emitFn(node);
  }

  // Anything else — warn and drop
  process.stderr.write(
    `generate-showcase-companion [AST]: unhandled node kind ${ts.SyntaxKind[node.kind]} — dropping value\n`
  );
  return null;
}

/**
 * Resolve a named export from an imported file (single-hop).
 *
 * Note: `carried` belongs to the META file's scope, not this imported file's.
 * If an FnMarker captured from an imported file references identifiers, those
 * references resolve in the imported file's import graph — not the meta file's.
 * We do not currently follow them (cross-file ref carry is out of scope); the
 * existing "unresolved identifier" warning surfaces these cases.
 */
function resolveImportedValue(
  filePath: string,
  exportName: string,
  consumerRoot: string,
  carried: Map<string, CarriedRef>,
  depth: number
): unknown {
  const ts = getTS();
  if (!existsSync(filePath)) return null;
  let src: string;
  try {
    src = readFileSync(filePath, "utf8");
  } catch {
    return null;
  }
  const sf = ts.createSourceFile(filePath, src, ts.ScriptTarget.Latest, true, ts.ScriptKind.TSX);
  const { localScope: scope, importScope } = buildScopes(sf, dirname(filePath), consumerRoot);

  // Use an isolated carried map during evaluation. Refs from the fixture file's
  // internal evaluation are only merged back into the meta's carried map when
  // the resolved value contains FnMarkers — meaning those identifiers will
  // appear verbatim in the emitted showcase and must be imported.
  // Refs collected for fully-concrete values (primitives / plain objects with no
  // FnMarkers) are discarded because the showcase serialises those inline and
  // never references the fixture-internal identifiers directly.
  const isolatedCarried = new Map<string, CarriedRef>();

  let result: unknown = null;

  for (const stmt of sf.statements) {
    if (ts.isVariableStatement(stmt)) {
      for (const decl of stmt.declarationList.declarations) {
        if (ts.isIdentifier(decl.name) && decl.name.text === exportName && decl.initializer) {
          result = astNodeToValue(decl.initializer, sf, scope, importScope, consumerRoot, isolatedCarried, depth + 1);
          break;
        }
      }
    }
    if (result !== null) break;
    if (ts.isExportDeclaration(stmt) && stmt.exportClause && ts.isNamedExports(stmt.exportClause)) {
      for (const spec of stmt.exportClause.elements) {
        if (spec.name.text === exportName) {
          const localName = spec.propertyName?.text ?? spec.name.text;
          if (scope.has(localName)) {
            result = astNodeToValue(scope.get(localName)!, sf, scope, importScope, consumerRoot, isolatedCarried, depth + 1);
            break;
          }
        }
      }
    }
    if (result !== null) break;
  }

  // Merge isolated refs into the caller's carried map only when the resolved
  // value is a non-FnMarker container (object or array) that itself contains
  // nested FnMarkers. In that case the FnMarker source text appears verbatim
  // in the emitted showcase, so the identifiers it references must be imported.
  //
  // When the top-level result is a FnMarker (the fixture export itself is an
  // unevaluatable call/expression), the caller's property-access or identifier
  // handler will discard this intermediate value and call its own emitFn on the
  // original source expression — collecting the correct refs from the meta
  // file's scope instead. Merging fixture-internal refs in that case would
  // introduce phantom imports (e.g. internal helper functions, transitive
  // fixture imports that the showcase never directly references).
  const resultIsFnMarkerContainer =
    !isFnMarker(result) && containsFnMarker(result);
  if (resultIsFnMarkerContainer) {
    for (const [name, ref] of isolatedCarried.entries()) {
      if (!carried.has(name)) carried.set(name, ref);
    }
  }

  return result;
}

/**
 * Walk an AST sub-tree and collect free identifier references that need to be
 * carried into the generated showcase. Called whenever we capture an arrow,
 * function, call expression, or other unevaluated expression as an FnMarker.
 *
 * `bound` is the set of names introduced by enclosing function parameters and
 * inner `const`/`let` declarations — these are skipped.
 *
 * Recursion: for local refs, we resolve the initializer via astNodeToValue so
 * its value is serialized AND any nested FnMarkers inside the local also get
 * their refs collected (carried recursively).
 */
function collectRefsFromNode(
  node: TS.Node,
  sourceFile: TS.SourceFile,
  localScope: Map<string, TS.Node>,
  importScope: Map<string, { filePath: string; exportName: string; rawSpec: string }>,
  typeImportScope: Map<string, { exportName: string; rawSpec: string }>,
  bound: Set<string>,
  carried: Map<string, CarriedRef>,
  consumerRoot: string
): void {
  const ts = getTS();
  // Identifier — candidate reference
  if (ts.isIdentifier(node)) {
    const name = node.text;
    if (bound.has(name) || carried.has(name)) return;
    // React is implicitly imported by the showcase, JSX globals don't need carry
    if (name === "React" || name === "undefined" || name === "null") return;
    if (importScope.has(name)) {
      const imp = importScope.get(name)!;
      // Normalise the specifier so it resolves from the showcase output directory.
      // When the import came from a fixture file (transitive resolution), `imp.rawSpec`
      // is relative to the fixture file's directory — not the showcase's. Prefer the
      // `@/` alias form (always valid from any directory in the consumer project);
      // fall back to the original spec only for bare-specifiers (filePath === "").
      const rawSpec = imp.filePath
        ? (filePathToAlias(imp.filePath, consumerRoot) ?? imp.rawSpec)
        : imp.rawSpec;
      carried.set(name, {
        kind: "import",
        localName: name,
        exportedName: imp.exportName,
        rawSpec,
      });
      return;
    }
    if (typeImportScope.has(name)) {
      const imp = typeImportScope.get(name)!;
      carried.set(name, {
        kind: "type-import",
        localName: name,
        exportedName: imp.exportName,
        rawSpec: imp.rawSpec,
      });
      return;
    }
    if (localScope.has(name)) {
      // Walk up from the initializer's parent to find the enclosing VariableStatement
      // and slice the full text (annotation + initializer + semicolon) as rawSource.
      const initNode = localScope.get(name)!;
      // initNode is the initializer; parent is VariableDeclaration
      let stmtNode: TS.Node = initNode;
      while (stmtNode && !ts.isVariableStatement(stmtNode)) {
        stmtNode = stmtNode.parent;
      }
      const rawSource = stmtNode
        ? sourceFile.text.slice(stmtNode.getStart(sourceFile), stmtNode.getEnd())
        : sourceFile.text.slice(initNode.getStart(sourceFile), initNode.getEnd());
      // Reserve the slot before recursing so cycles terminate.
      carried.set(name, { kind: "local", name, rawSource: "" });
      carried.set(name, { kind: "local", name, rawSource });
      // Also collect refs (value + type) from the VariableDeclaration so transitive
      // identifiers (e.g. DataTableColumn, JobFixture in a typed local) are carried.
      const declNode = stmtNode ?? initNode;
      collectRefsFromNode(declNode, sourceFile, localScope, importScope, typeImportScope, bound, carried, consumerRoot);
      return;
    }
    return;
  }

  // Skip identifier on the RHS of a non-computed property access (`.foo`)
  if (ts.isPropertyAccessExpression(node)) {
    collectRefsFromNode(node.expression, sourceFile, localScope, importScope, typeImportScope, bound, carried, consumerRoot);
    return;
  }

  // Functions: extend bound with parameter names + walk type annotations
  if (
    ts.isArrowFunction(node) ||
    ts.isFunctionExpression(node) ||
    ts.isFunctionDeclaration(node) ||
    ts.isMethodDeclaration(node) ||
    ts.isGetAccessorDeclaration(node) ||
    ts.isSetAccessorDeclaration(node)
  ) {
    const innerBound = new Set(bound);
    for (const p of node.parameters) {
      collectBindingNames(p.name, innerBound);
      // Walk type annotation on each parameter
      if (p.type) collectRefsFromTypeNode(p.type, sourceFile, typeImportScope, carried);
    }
    if (node.body) {
      collectRefsFromNode(node.body, sourceFile, localScope, importScope, typeImportScope, innerBound, carried, consumerRoot);
    }
    return;
  }

  // Variable declarations: walk type annotation positions
  if (ts.isVariableDeclaration(node)) {
    if (node.type) collectRefsFromTypeNode(node.type, sourceFile, typeImportScope, carried);
    if (node.initializer) {
      collectRefsFromNode(node.initializer, sourceFile, localScope, importScope, typeImportScope, bound, carried, consumerRoot);
    }
    return;
  }

  // Object literal: keys are not references, but values are.
  if (ts.isObjectLiteralExpression(node)) {
    for (const prop of node.properties) {
      if (ts.isPropertyAssignment(prop)) {
        if (prop.name && ts.isComputedPropertyName(prop.name)) {
          collectRefsFromNode(prop.name.expression, sourceFile, localScope, importScope, typeImportScope, bound, carried, consumerRoot);
        }
        collectRefsFromNode(prop.initializer, sourceFile, localScope, importScope, typeImportScope, bound, carried, consumerRoot);
      } else if (ts.isShorthandPropertyAssignment(prop)) {
        collectRefsFromNode(prop.name, sourceFile, localScope, importScope, typeImportScope, bound, carried, consumerRoot);
      } else if (ts.isSpreadAssignment(prop)) {
        collectRefsFromNode(prop.expression, sourceFile, localScope, importScope, typeImportScope, bound, carried, consumerRoot);
      } else {
        // method / get / set — re-enter the function path
        collectRefsFromNode(prop, sourceFile, localScope, importScope, typeImportScope, bound, carried, consumerRoot);
      }
    }
    return;
  }

  // Block / source file: variable declarations bind names within
  if (ts.isBlock(node) || ts.isSourceFile(node)) {
    const innerBound = new Set(bound);
    const isFileScope = ts.isSourceFile(node);
    ts.forEachChild(node, (child) => {
      if (ts.isVariableStatement(child)) {
        for (const decl of child.declarationList.declarations) {
          collectBindingNames(decl.name, innerBound);
        }
      } else if (ts.isFunctionDeclaration(child) && child.name) {
        // #70: at file scope, sibling function declarations must NOT be treated
        // as bound — meta JSX referencing them (e.g. <CardHeader />) needs an
        // import emitted in the showcase. buildScopes registers them in
        // importScope with rawSpec="./<basename>" so the carry path picks them
        // up as free identifiers. Inside nested blocks they remain bound.
        if (!isFileScope) innerBound.add(child.name.text);
      }
    });
    ts.forEachChild(node, (child) => {
      collectRefsFromNode(child, sourceFile, localScope, importScope, typeImportScope, innerBound, carried, consumerRoot);
    });
    return;
  }

  // Default: recurse into children
  ts.forEachChild(node, (child) => {
    collectRefsFromNode(child, sourceFile, localScope, importScope, typeImportScope, bound, carried, consumerRoot);
  });
}

/**
 * Walk a TypeScript type node and carry any identifiers that resolve to
 * the typeImportScope. Handles TypeReference, Array, Union, Intersection,
 * TypeLiteral (property types), and generic type arguments.
 */
function collectRefsFromTypeNode(
  node: TS.TypeNode,
  sourceFile: TS.SourceFile,
  typeImportScope: Map<string, { exportName: string; rawSpec: string }>,
  carried: Map<string, CarriedRef>
): void {
  const ts = getTS();
  if (ts.isTypeReferenceNode(node)) {
    // The type name can be a qualified name (A.B) — only the leftmost identifier matters
    let typeName: TS.EntityName = node.typeName;
    while (ts.isQualifiedName(typeName)) typeName = typeName.left;
    const name = typeName.text;
    if (!carried.has(name) && typeImportScope.has(name)) {
      const imp = typeImportScope.get(name)!;
      carried.set(name, {
        kind: "type-import",
        localName: name,
        exportedName: imp.exportName,
        rawSpec: imp.rawSpec,
      });
    }
    // Recurse into generic type arguments (e.g. DataTableColumn<JobFixture>[])
    if (node.typeArguments) {
      for (const arg of node.typeArguments) collectRefsFromTypeNode(arg, sourceFile, typeImportScope, carried);
    }
    return;
  }
  if (ts.isArrayTypeNode(node)) {
    collectRefsFromTypeNode(node.elementType, sourceFile, typeImportScope, carried);
    return;
  }
  if (ts.isUnionTypeNode(node) || ts.isIntersectionTypeNode(node)) {
    for (const t of node.types) collectRefsFromTypeNode(t, sourceFile, typeImportScope, carried);
    return;
  }
  if (ts.isTypeLiteralNode(node)) {
    for (const member of node.members) {
      if (ts.isPropertySignature(member) && member.type) {
        collectRefsFromTypeNode(member.type, sourceFile, typeImportScope, carried);
      }
    }
    return;
  }
  if (ts.isParenthesizedTypeNode(node)) {
    collectRefsFromTypeNode(node.type, sourceFile, typeImportScope, carried);
    return;
  }
}

/** Collect identifier names from a binding pattern (`{a, b: {c}}`, `[x, ...rest]`, plain `x`). */
function collectBindingNames(name: TS.BindingName, set: Set<string>): void {
  const ts = getTS();
  if (ts.isIdentifier(name)) {
    set.add(name.text);
    return;
  }
  if (ts.isObjectBindingPattern(name) || ts.isArrayBindingPattern(name)) {
    for (const el of name.elements) {
      if (ts.isBindingElement(el)) collectBindingNames(el.name, set);
    }
  }
}

/** Build local variable scope + import scope maps from a source file. */
function buildScopes(
  sf: TS.SourceFile,
  dir: string,
  consumerRoot: string
): {
  localScope: Map<string, TS.Node>;
  importScope: Map<string, { filePath: string; exportName: string; rawSpec: string }>;
  typeImportScope: Map<string, { exportName: string; rawSpec: string }>;
} {
  const ts = getTS();
  const localScope = new Map<string, TS.Node>();
  const importScope = new Map<string, { filePath: string; exportName: string; rawSpec: string }>();
  // Type-only imports: registered separately so they never pollute astNodeToValue
  // (type imports are not runtime values), but are available to collectRefsFromNode
  // when walking type-annotation positions.
  const typeImportScope = new Map<string, { exportName: string; rawSpec: string }>();

  // Types declared in the source file itself are reachable from the showcase via
  // `./<basename>` (the same module the runtime component is imported from). Pre-seed
  // typeImportScope so the existing carry path emits an `import type` line for them.
  // Without this, a hoisted local like `const cols: DataTableColumn<…>[] = …` carries
  // its rawSource into the showcase but the `DataTableColumn` annotation cannot resolve.
  const sourceBasename = basename(sf.fileName).replace(/\.(tsx|ts)$/, "");
  const localTypeSpec = `./${sourceBasename}`;
  for (const stmt of sf.statements) {
    if ((ts.isTypeAliasDeclaration(stmt) || ts.isInterfaceDeclaration(stmt)) && stmt.name) {
      // Only register types that are actually exported — non-exported types cannot be
      // imported by the generated showcase, so carrying them produces a TS error (#defect3).
      const isExported = !!stmt.modifiers?.some((m) => m.kind === ts.SyntaxKind.ExportKeyword);
      if (isExported) {
        typeImportScope.set(stmt.name.text, { exportName: stmt.name.text, rawSpec: localTypeSpec });
      }
    }
  }

  // #70: register top-level function declarations as imports from the local
  // module so meta JSX referencing siblings like <CardHeader /> gets imports
  // emitted via the carry mechanism. The file's primary component is also
  // registered here; emitAtomCompositeShowcase de-duplicates against the
  // explicit display-name import line below.
  for (const stmt of sf.statements) {
    if (ts.isFunctionDeclaration(stmt) && stmt.name) {
      const isExported = !!stmt.modifiers?.some((m) => m.kind === ts.SyntaxKind.ExportKeyword);
      if (!isExported) continue;
      importScope.set(stmt.name.text, {
        filePath: sf.fileName,
        exportName: stmt.name.text,
        rawSpec: localTypeSpec,
      });
    }
  }

  // Defect #4: function declarations exported via `export { Foo, Bar }` block
  // (no `export` keyword on the function itself) are not caught by the #70 pass
  // above. Build a set of non-exported function declaration names, then resolve
  // them through any `export { ... }` statement in the file.
  const nonExportedFnNames = new Set<string>();
  for (const stmt of sf.statements) {
    if (ts.isFunctionDeclaration(stmt) && stmt.name) {
      const isDirectlyExported = !!stmt.modifiers?.some((m) => m.kind === ts.SyntaxKind.ExportKeyword);
      if (!isDirectlyExported) nonExportedFnNames.add(stmt.name.text);
    }
  }
  if (nonExportedFnNames.size > 0) {
    for (const stmt of sf.statements) {
      if (
        ts.isExportDeclaration(stmt) &&
        !stmt.moduleSpecifier && // only re-export blocks within the same file
        stmt.exportClause &&
        ts.isNamedExports(stmt.exportClause)
      ) {
        for (const spec of stmt.exportClause.elements) {
          const localName = spec.propertyName?.text ?? spec.name.text;
          if (nonExportedFnNames.has(localName)) {
            importScope.set(spec.name.text, {
              filePath: sf.fileName,
              exportName: spec.name.text,
              rawSpec: localTypeSpec,
            });
          }
        }
      }
    }
  }

  for (const stmt of sf.statements) {
    // Variable declarations: const foo = ...
    if (ts.isVariableStatement(stmt)) {
      const isExportedStmt = !!stmt.modifiers?.some((m) => m.kind === ts.SyntaxKind.ExportKeyword);
      for (const decl of stmt.declarationList.declarations) {
        if (ts.isIdentifier(decl.name) && decl.initializer) {
          // Defect #2: exported consts whose initializer is React.forwardRef(…) or
          // React.memo(…) are callable components — they must be carried as imports
          // from the source file, not inlined verbatim. Inlining would copy the full
          // forwardRef body into the showcase (including any non-exported local types
          // it references), causing TS errors.
          if (isExportedStmt && ts.isCallExpression(decl.initializer)) {
            const callee = decl.initializer.expression;
            const isWrappedComponent =
              (ts.isPropertyAccessExpression(callee) &&
                ts.isIdentifier(callee.expression) &&
                callee.expression.text === "React" &&
                (callee.name.text === "forwardRef" || callee.name.text === "memo")) ||
              (ts.isIdentifier(callee) &&
                (callee.text === "forwardRef" || callee.text === "memo"));
            if (isWrappedComponent) {
              importScope.set(decl.name.text, {
                filePath: sf.fileName,
                exportName: decl.name.text,
                rawSpec: localTypeSpec,
              });
              continue; // do NOT also add to localScope
            }
          }
          localScope.set(decl.name.text, decl.initializer);
        }
      }
    }
    // Import declarations: import { x, y } from "./path" or from "bare-pkg"
    if (ts.isImportDeclaration(stmt) && ts.isStringLiteral(stmt.moduleSpecifier)) {
      const rawSpec = stmt.moduleSpecifier.text;
      const isBareSpecifier = !rawSpec.startsWith(".") && !rawSpec.startsWith("@/");

      // Bare-specifier imports (e.g. "lucide-react", "react"): register in importScope
      // with filePath="" so collectRefsFromNode can carry them into the showcase import
      // block. resolveImportedValue short-circuits on non-existent paths (harmless).
      if (isBareSpecifier) {
        const clause = stmt.importClause;
        if (!clause) continue;
        const bindings = clause.namedBindings;
        if (bindings && ts.isNamedImports(bindings)) {
          for (const spec of bindings.elements) {
            const localName = spec.name.text;
            const exportedName = spec.propertyName?.text ?? spec.name.text;
            if (spec.isTypeOnly || clause.isTypeOnly) {
              typeImportScope.set(localName, { exportName: exportedName, rawSpec });
            } else {
              importScope.set(localName, { filePath: "", exportName: exportedName, rawSpec });
            }
          }
        }
        continue;
      }

      let resolved = rawSpec;
      if (rawSpec.startsWith("@/")) {
        resolved = resolveAtPrefix(rawSpec, consumerRoot);
        // Make absolute from consumerRoot
        if (!resolvePath(resolved).startsWith("/")) {
          resolved = join(consumerRoot, resolved);
        }
      } else {
        resolved = join(dir, resolved);
      }

      // Try extensions
      const candidates = [resolved, resolved + ".ts", resolved + ".tsx", resolved + "/index.ts", resolved + "/index.tsx"];
      const found = candidates.find((c) => existsSync(c));
      if (!found) continue;

      const clause = stmt.importClause;
      if (!clause) continue;
      const bindings = clause.namedBindings;
      if (bindings && ts.isNamedImports(bindings)) {
        for (const spec of bindings.elements) {
          const localName = spec.name.text;
          const exportedName = spec.propertyName?.text ?? spec.name.text;
          if (spec.isTypeOnly || clause.isTypeOnly) {
            // Type-only: register in typeImportScope only — never as a runtime value
            typeImportScope.set(localName, { exportName: exportedName, rawSpec });
          } else {
            importScope.set(localName, { filePath: found, exportName: exportedName, rawSpec });
          }
        }
      }
    }
  }

  return { localScope, importScope, typeImportScope };
}

/**
 * AST-based meta extractor (option A3). Parses the .tsx source file with
 * `ts.createSourceFile()` — no module loading, no CJS/ESM bridge issues.
 * Works in any consumer regardless of `"type"` in their package.json.
 *
 * Functions are captured as `{ __fn: "<source text>" }` markers so the
 * JSX serializer can emit them as raw JS expressions.
 */
function extractMetaFromAST(filePath: string): {
  meta: ParsedMeta;
  carried: Map<string, CarriedRef>;
  useClient: boolean;
} | null {
  if (!tsRuntime) return null; // typescript not available — fall back to regex parseMeta
  const ts = tsRuntime;

  let source: string;
  try {
    source = readFileSync(filePath, "utf8");
  } catch {
    return null;
  }

  const sf = ts.createSourceFile(filePath, source, ts.ScriptTarget.Latest, true, ts.ScriptKind.TSX);
  const consumerRoot = findConsumerRoot(dirname(filePath));
  const { localScope, importScope, typeImportScope } = buildScopes(sf, dirname(filePath), consumerRoot);
  const carried = new Map<string, CarriedRef>();
  const useClient = hasUseClientDirective(source);

  // Find `export const meta = { ... }` or `export const meta: Meta = { ... }`
  let metaInit: TS.ObjectLiteralExpression | null = null;
  for (const stmt of sf.statements) {
    if (!ts.isVariableStatement(stmt)) continue;
    const hasExport = stmt.modifiers?.some((m) => m.kind === ts.SyntaxKind.ExportKeyword);
    if (!hasExport) continue;
    for (const decl of stmt.declarationList.declarations) {
      if (!ts.isIdentifier(decl.name) || decl.name.text !== "meta") continue;
      if (decl.initializer && ts.isObjectLiteralExpression(decl.initializer)) {
        metaInit = decl.initializer;
        break;
      }
    }
    if (metaInit) break;
  }

  if (!metaInit) return null;

  const metaObj = astNodeToValue(metaInit, sf, localScope, importScope, consumerRoot, carried, 0, typeImportScope) as Record<string, unknown> | null;
  if (!metaObj || typeof metaObj !== "object") return null;

  const kind = metaObj.kind as "atom" | "composite" | "reference" | undefined;
  if (kind === "reference") {
    return {
      meta: { kind: "reference", title: typeof metaObj.title === "string" ? metaObj.title : "Reference" },
      carried,
      useClient,
    };
  }
  if (kind !== "atom" && kind !== "composite") return null;

  const examples: Example[] = Array.isArray(metaObj.examples)
    ? (metaObj.examples as unknown[]).map((e) => {
        const obj = (e ?? {}) as Record<string, unknown>;
        return {
          name: typeof obj.name === "string" ? obj.name : "unnamed",
          props: (obj.props && typeof obj.props === "object" ? obj.props : {}) as Record<string, unknown>,
        };
      })
    : [];

  const skip: string[] = Array.isArray(metaObj.skip)
    ? (metaObj.skip as unknown[]).filter((s): s is string => typeof s === "string")
    : [];

  return { meta: { kind, examples, skip }, carried, useClient };
}

/**
 * #69: detect a namespace-only export — a top-level `export const <Name> = { ... }`
 * whose initializer is a plain object literal (not a function/arrow/call/forwardRef).
 * The generator emits `<Name ... />` JSX assuming Name is callable; when it is not,
 * the showcase crashes at render. We fail loud at generation time so authors fix
 * the source rather than ship a stale .showcase.tsx.
 *
 * Returns true when displayName refers to a non-callable object literal export AND
 * no callable declaration of the same name exists in the file.
 */
function isNamespaceOnlyExport(filePath: string, displayName: string): boolean {
  if (!tsRuntime) return false;
  const ts = tsRuntime;
  let source: string;
  try {
    source = readFileSync(filePath, "utf8");
  } catch {
    return false;
  }
  const sf = ts.createSourceFile(filePath, source, ts.ScriptTarget.Latest, true, ts.ScriptKind.TSX);
  let hasCallableDecl = false;
  let hasObjectLiteralExport = false;
  for (const stmt of sf.statements) {
    // function Name(...) — callable
    if (ts.isFunctionDeclaration(stmt) && stmt.name?.text === displayName) {
      hasCallableDecl = true;
    }
    // class Name {} — callable (via JSX)
    if (ts.isClassDeclaration(stmt) && stmt.name?.text === displayName) {
      hasCallableDecl = true;
    }
    if (ts.isVariableStatement(stmt)) {
      const hasExport = stmt.modifiers?.some((m) => m.kind === ts.SyntaxKind.ExportKeyword);
      for (const decl of stmt.declarationList.declarations) {
        if (!ts.isIdentifier(decl.name) || decl.name.text !== displayName) continue;
        const init = decl.initializer;
        if (!init) continue;
        // Arrow / function expr / call (forwardRef, memo) — treat as callable
        if (
          ts.isArrowFunction(init) ||
          ts.isFunctionExpression(init) ||
          ts.isCallExpression(init)
        ) {
          hasCallableDecl = true;
        } else if (hasExport && ts.isObjectLiteralExpression(init)) {
          hasObjectLiteralExport = true;
        }
      }
    }
  }
  return hasObjectLiteralExport && !hasCallableDecl;
}

/**
 * Detect a `"use client"` (or `'use client'`) directive at the top of the source,
 * ignoring leading whitespace, BOM, and leading comments.
 */
function hasUseClientDirective(source: string): boolean {
  let s = source.replace(/^﻿/, "");
  // Strip leading whitespace + comments
  // Bounded loop avoids unbounded scanning on pathological input.
  for (let i = 0; i < 200; i++) {
    s = s.replace(/^\s+/, "");
    if (s.startsWith("//")) {
      const nl = s.indexOf("\n");
      s = nl < 0 ? "" : s.slice(nl + 1);
      continue;
    }
    if (s.startsWith("/*")) {
      const end = s.indexOf("*/");
      if (end < 0) break;
      s = s.slice(end + 2);
      continue;
    }
    break;
  }
  return /^["']use client["'];?/.test(s);
}

/** Walk up from a dir to find a package.json, returning that dir as consumer root. */
function findConsumerRoot(startDir: string): string {
  let dir = startDir;
  for (let i = 0; i < 10; i++) {
    if (existsSync(join(dir, "package.json"))) return dir;
    const parent = dirname(dir);
    if (parent === dir) break;
    dir = parent;
  }
  return startDir;
}

/**
 * Regex-based meta extraction from source. Fallback for when `tsx/esm/api`
 * is unavailable or fails to import the source (e.g. module-level side
 * effects from `next/navigation` or similar). Works for JSON-compatible
 * meta values only — functions and JSX in meta are dropped.
 */
function parseMeta(source: string): ParsedMeta | null {
  // Find 'export const meta' and grab the kind
  const kindMatch = source.match(/export\s+const\s+meta[^=]*=\s*\{[^}]*kind\s*:\s*["']([^"']+)["']/);
  if (!kindMatch) return null;

  const kind = kindMatch[1] as "atom" | "composite" | "reference";

  if (kind === "reference") {
    // Extract title
    const titleMatch = source.match(/kind\s*:\s*["']reference["'][^}]*title\s*:\s*["']([^"']+)["']/s)
      ?? source.match(/title\s*:\s*["']([^"']+)["'][^}]*kind\s*:\s*["']reference["']/s);
    const title = titleMatch ? titleMatch[1] : "Reference";
    return { kind: "reference", title };
  }

  // atom | composite — extract examples[] and skip[]
  const examples = parseExamples(source);
  const skip = parseSkip(source);
  return { kind, examples, skip };
}

const REGEX_UNDEFINED_SENTINEL = "__DS_UNDEFINED__";

function parseExamples(source: string): Example[] {
  // Find examples array in meta
  const examplesMatch = source.match(/examples\s*:\s*(\[[\s\S]*?\])\s*(?:,|\})/);
  if (!examplesMatch) return [];

  try {
    // Replace JS-style property shorthand, functions, etc. with JSON-safe equivalents.
    // We support: name: "string", props: { key: "val", key2: 123, key3: true/false/null }
    const raw = examplesMatch[1];
    // Attempt JSON.parse after light sanitization.
    // `undefined` is replaced with a sentinel string rather than `null` so we can
    // distinguish "prop explicitly cleared to undefined" (→ omit from JSX) from
    // "prop intentionally set to null" (→ emit `={null}`).
    const sanitized = raw
      .replace(/\/\/[^\n]*/g, "") // remove line comments
      .replace(/,\s*([\]}])/g, "$1") // trailing commas
      .replace(/([{,]\s*)(\w+)\s*:/g, '$1"$2":') // unquoted keys
      .replace(/:\s*undefined\b/g, `:"${REGEX_UNDEFINED_SENTINEL}"`) // undefined → sentinel
      .replace(/:\s*'([^']*)'/g, ':"$1"'); // single-quoted strings → double-quoted
    const parsed = JSON.parse(sanitized);
    if (!Array.isArray(parsed)) return [];
    return parsed.map((e: unknown) => {
      const obj = e as Record<string, unknown>;
      const rawProps = typeof obj.props === "object" && obj.props !== null
        ? (obj.props as Record<string, unknown>)
        : {};
      // Drop sentinel props — they were `undefined` in source and must be omitted
      // from generated JSX rather than emitted as null.
      const props: Record<string, unknown> = {};
      for (const [k, v] of Object.entries(rawProps)) {
        if (v !== REGEX_UNDEFINED_SENTINEL) props[k] = v;
      }
      return {
        name: typeof obj.name === "string" ? obj.name : "unnamed",
        props,
      };
    });
  } catch {
    return [];
  }
}

function parseSkip(source: string): string[] {
  const skipMatch = source.match(/skip\s*:\s*(\[[\s\S]*?\])\s*(?:,|\})/);
  if (!skipMatch) return [];
  try {
    const raw = skipMatch[1]
      .replace(/\/\/[^\n]*/g, "")
      .replace(/,\s*\]/g, "]")
      .replace(/'/g, '"');
    const parsed = JSON.parse(raw);
    return Array.isArray(parsed) ? parsed.filter((s) => typeof s === "string") : [];
  } catch {
    return [];
  }
}

// ── CVA parsing ───────────────────────────────────────────────────────────────

interface CvaConfig {
  variants: Record<string, string[]>;
  defaultVariants: Record<string, string>;
}

/**
 * Parse cva() call from source to extract variant keys and values.
 * Pattern: cva(base, { variants: { size: { sm: "...", md: "..." }, tone: { ... } }, defaultVariants: { ... } })
 *
 * LATENT BUG (multi-CVA files): the broad-fallback regex in this function and
 * extractVariantKeys() spans across cva() call boundaries in source files that
 * contain more than one cva() call (e.g. badge.tsx with badgeVariants and
 * dotVariants). This causes variant axes from the second CVA to bleed into the
 * first, producing malformed <Component variants="..."> JSX. The stub-signal
 * short-circuit in isStubMeta() (examples.length === 0) masks this for every
 * current consumer because those files all carry empty examples arrays. The
 * correct repair — rewriting parseCva as an AST pass returning
 * Map<cvaVarName, CvaConfig> paired with per-component JSX-body walking — is
 * deferred to the per-component CVA-targeting follow-up issue.
 */
function parseCva(source: string): CvaConfig | null {
  if (!source.includes("cva(")) return null;

  // Extract variants block from cva() call
  const variantsMatch = source.match(/cva\s*\([^)]*\{\s*variants\s*:\s*(\{[\s\S]*?\})\s*(?:,\s*defaultVariants|\})\s*\)/);
  if (!variantsMatch) {
    // Try a broader match for multi-line cva definitions
    const broadMatch = source.match(/variants\s*:\s*\{([\s\S]*?)\}\s*(?:,\s*(?:defaultVariants|compoundVariants)|\s*\}\s*\))/);
    if (!broadMatch) return null;

    try {
      const varBlock = `{${broadMatch[1]}}`;
      const variants = extractVariantKeys(varBlock, source);
      const defaultVariants = extractDefaultVariants(source);
      if (Object.keys(variants).length === 0) return null;
      return { variants, defaultVariants };
    } catch {
      return null;
    }
  }

  try {
    const variants = extractVariantKeys(variantsMatch[1], source);
    const defaultVariants = extractDefaultVariants(source);
    return { variants, defaultVariants };
  } catch {
    return null;
  }
}

function extractVariantKeys(variantsBlock: string, _source: string): Record<string, string[]> {
  const result: Record<string, string[]> = {};
  // Strip string literals first so Tailwind modifier prefixes (hover:, focus:, etc.)
  // inside class value strings are not mistaken for variant keys.
  const stripped = stripStringLiterals(variantsBlock);

  // Match each variant key and its value object. Variant axis names can be
  // bare identifiers (`intent`) or quoted strings (`"aria-invalid"`). After
  // stripStringLiterals the quoted-key text became `""`, so we must scan the
  // ORIGINAL block for quoted-keyed axes — but locate their value object via
  // brace-matching on the stripped block (so Tailwind modifier prefixes inside
  // class strings stay neutralised).
  const variantHits: Array<{ variantName: string; strippedValuesBlock: string }> = [];

  // (a) bare-identifier axes from stripped block
  const variantRe = /(\w+)\s*:\s*\{([^}]*)\}/g;
  let m: RegExpExecArray | null;
  while ((m = variantRe.exec(stripped)) !== null) {
    variantHits.push({ variantName: m[1], strippedValuesBlock: m[2] });
  }

  // (b) quoted-identifier axes (e.g. "aria-invalid") — scan original, then
  //     slice the stripped block at the same offset to get the cleaned values.
  const quotedAxisRe = /["']([A-Za-z_$][\w$-]*)["']\s*:\s*\{/g;
  let qa: RegExpExecArray | null;
  while ((qa = quotedAxisRe.exec(variantsBlock)) !== null) {
    const variantName = qa[1];
    if (variantHits.some((h) => h.variantName === variantName)) continue;
    // Brace-match starting at the `{` position to extract the values block.
    const openIdx = variantsBlock.indexOf("{", qa.index + qa[0].length - 1);
    if (openIdx < 0) continue;
    let depth = 0;
    let endIdx = -1;
    for (let i = openIdx; i < variantsBlock.length; i++) {
      const ch = variantsBlock[i];
      if (ch === "{") depth++;
      else if (ch === "}") {
        depth--;
        if (depth === 0) {
          endIdx = i;
          break;
        }
      }
    }
    if (endIdx < 0) continue;
    // Use stripped version of that slice so Tailwind modifiers don't leak
    const rawSlice = variantsBlock.slice(openIdx + 1, endIdx);
    const strippedValuesBlock = stripStringLiterals(rawSlice);
    variantHits.push({ variantName, strippedValuesBlock });
  }

  for (const { variantName, strippedValuesBlock } of variantHits) {
    // For value keys we need BOTH unquoted identifiers (from stripped block) AND
    // quoted identifiers like "icon-sm" (which were removed by stripping).
    // Locate the original values block for this variant name (try bare then quoted).
    const origVariantReBare = new RegExp(`(?:^|[{,\\s])${variantName}\\s*:\\s*\\{([^}]*)\\}`);
    const origVariantReQuoted = new RegExp(`["']${variantName}["']\\s*:\\s*\\{([^}]*)\\}`);
    const origMatch = variantsBlock.match(origVariantReBare) ?? variantsBlock.match(origVariantReQuoted);
    const origValuesBlock = origMatch ? origMatch[1] : strippedValuesBlock;

    const valueKeys: string[] = [];

    // Unquoted keys from the stripped block (no Tailwind modifier leakage)
    const keyRe = /(\w+)\s*:/g;
    let km: RegExpExecArray | null;
    while ((km = keyRe.exec(strippedValuesBlock)) !== null) {
      valueKeys.push(km[1]);
    }

    // Quoted keys from the original block (e.g. "icon-sm": ..., 'icon-lg': ...)
    const quotedKeyRe = /["']([^"']+)["']\s*:/g;
    let qm: RegExpExecArray | null;
    while ((qm = quotedKeyRe.exec(origValuesBlock)) !== null) {
      if (!valueKeys.includes(qm[1])) {
        valueKeys.push(qm[1]);
      }
    }

    if (valueKeys.length > 0) {
      result[variantName] = valueKeys;
    }
  }
  return result;
}

function extractDefaultVariants(source: string): Record<string, string> {
  const dvMatch = source.match(/defaultVariants\s*:\s*\{([^}]*)\}/);
  if (!dvMatch) return {};
  const result: Record<string, string> = {};
  const kvRe = /(\w+)\s*:\s*["']?(\w+)["']?/g;
  let m: RegExpExecArray | null;
  while ((m = kvRe.exec(dvMatch[1])) !== null) {
    result[m[1]] = m[2];
  }
  return result;
}

/** Generate the full cross-product of CVA variants, minus skipped combos. */
function cvaCartesian(config: CvaConfig, skip: string[]): Array<{ name: string; props: Record<string, string> }> {
  const variantNames = Object.keys(config.variants);
  if (variantNames.length === 0) return [];

  const values = variantNames.map((k) => config.variants[k]);

  // Cartesian product
  function product(arrays: string[][]): string[][] {
    return arrays.reduce<string[][]>(
      (acc, cur) => acc.flatMap((a) => cur.map((b) => [...a, b])),
      [[]]
    );
  }

  const combos = product(values);

  return combos
    .map((combo) => {
      const props: Record<string, string> = {};
      const nameParts: string[] = [];
      variantNames.forEach((vk, i) => {
        props[vk] = combo[i];
        nameParts.push(`${vk}=${combo[i]}`);
      });
      return { name: nameParts.join("_"), props };
    })
    .filter((c) => !skip.includes(c.name));
}

// ── stub-meta detection ───────────────────────────────────────────────────────

/**
 * Returns true when meta.examples signals "not showcased yet".
 *
 * Two cases:
 *  1. examples.length === 0 — explicit empty array is an authoritative stub
 *     signal regardless of whether CVA is present. Multi-CVA files with empty
 *     examples must emit a placeholder, not auto-expand (which produces malformed
 *     JSX when the broad-fallback regex spans cva boundaries).
 *  2. examples.length === 1, name === "default", empty props, AND no CVA — the
 *     original default-stub convention; still honoured for backward compat.
 */
function isStubMeta(examples: Example[], cvaConfig: CvaConfig | null): boolean {
  if (examples.length === 0) return true; // explicit empty array wins unconditionally
  if (cvaConfig !== null) return false; // CVA expansion will produce real combos
  if (examples.length !== 1) return false;
  const only = examples[0];
  return only.name === "default" && Object.keys(only.props).length === 0;
}

// ── showcase emitters ─────────────────────────────────────────────────────────

/**
 * Determine if a size value name refers to an icon-only slot.
 * Names starting with "icon" (e.g. "icon", "icon-sm", "icon-lg") qualify.
 */
function isIconSize(sizeValue: string): boolean {
  return sizeValue.startsWith("icon");
}

/**
 * Build the JSX children string for an auto-generated CVA combo. Returns one of:
 *   - "" — no children (self-close); used when explicit children are passed via props
 *   - `<Square aria-hidden="true" className="h-4 w-4" />` — icon-only sizes
 *   - the displayName as a text node — text-bearing sizes
 *
 * When the icon placeholder is emitted, `lucide-react` `Square` must be imported
 * by the showcase; emitAtomCompositeShowcase tracks this and emits the import
 * conditionally.
 */
function autoChildren(props: Record<string, string>, displayName: string, acceptsChildren = true): string {
  if ("children" in props) return ""; // explicit children present
  const sizeVal = props["size"] ?? "";
  if (isIconSize(sizeVal)) return `<Square aria-hidden="true" className="h-4 w-4" />`;
  // #68: components without a `children` prop should self-close, not stuff
  // displayName as a text node (which fails the prop type and breaks tsc).
  if (!acceptsChildren) return "";
  return displayName;
}

/**
 * Heuristic: does the source declare a `children` prop on its primary component?
 * We don't run a full type-check — instead we look for common shapes:
 *   - destructure: `function Foo({ children, ... }: ...)` or `({ children })`
 *   - prop type: `children?: ...` or `children: ...` in a type/interface
 *   - PropsWithChildren / React.PropsWithChildren wrapper
 *   - spread-props pattern (`(props: any)` or `...rest`): assume children-accepting
 *     because it forwards to a DOM element.
 *
 * Returns true on any match. Used by autoChildren so childless components
 * (e.g. BrandMark) emit self-closing JSX instead of `<BrandMark>BrandMark</BrandMark>`.
 */
function componentAcceptsChildren(source: string): boolean {
  // Strip comments + string literals to avoid matches inside docstrings.
  const cleaned = stripStringLiterals(
    source.replace(/\/\*[\s\S]*?\*\//g, "").replace(/\/\/[^\n]*/g, "")
  );
  if (/\bchildren\s*[?:]/.test(cleaned)) return true;
  if (/\{\s*[^}]*\bchildren\b[^}]*\}\s*:/.test(cleaned)) return true;
  if (/PropsWithChildren\b/.test(cleaned)) return true;
  // Spread-props patterns commonly forward children to an underlying element.
  if (/\(\s*\{[^}]*\.\.\.[A-Za-z_$][\w$]*[^}]*\}\s*:/.test(cleaned)) return true;
  if (/\(\s*props\s*:\s*any\b/.test(cleaned)) return true;
  return false;
}

interface UsageInfo {
  literal: Map<string, Map<string, number>>;
  dynamicProps: Set<string>;
}
type UsageMap = Map<string, UsageInfo>;

/**
 * Recursively serialize a JS value into a valid JS expression string for
 * embedding inside a JSX `={...}` attribute brace. Unlike JSON.stringify
 * this preserves functions captured via AST extraction as `{ __fn: "..." }`
 * markers (issue #61 cycle 2 — AST-based extraction).
 *
 * React elements (objects with $$typeof) are emitted as `null` with a
 * comment — meta should keep header JSX out of the value tree.
 */
function serializeJSValue(v: unknown): string {
  if (v === null) return "null";
  if (v === undefined) return "undefined";
  if (typeof v === "string") return JSON.stringify(v);
  if (typeof v === "number") return Number.isFinite(v) ? String(v) : "null";
  if (typeof v === "boolean") return v ? "true" : "false";
  if (typeof v === "function") return `(${(v as () => unknown).toString()})`;
  // AST function marker — emit raw source text
  if (isFnMarker(v)) return v.__fn;
  if (Array.isArray(v)) {
    return `[${v.map((x) => serializeJSValue(x)).join(", ")}]`;
  }
  if (typeof v === "object") {
    const obj = v as Record<string | symbol, unknown>;
    if ((obj as { $$typeof?: symbol }).$$typeof) {
      return "null /* React element in meta — not serializable; use a render escape-hatch */";
    }
    const entries = Object.entries(obj).map(([k, val]) => {
      const keyStr = /^[A-Za-z_$][\w$]*$/.test(k) ? k : JSON.stringify(k);
      return `${keyStr}: ${serializeJSValue(val)}`;
    });
    return `{ ${entries.join(", ")} }`;
  }
  return "null";
}

/** Returns true if the value (or any nested value) contains an FnMarker. */
function containsFnMarker(v: unknown): boolean {
  if (isFnMarker(v)) return true;
  if (Array.isArray(v)) return v.some(containsFnMarker);
  if (typeof v === "object" && v !== null) {
    return Object.values(v as Record<string, unknown>).some(containsFnMarker);
  }
  return false;
}

function renderPropsAttr(props: Record<string, unknown>): string {
  return Object.entries(props)
    .flatMap(([k, v]) => {
      // Props explicitly set to `undefined` (e.g. `reference: undefined` to clear
      // a spread) are omitted from the JSX attribute list entirely. Emitting
      // `reference={undefined}` or `reference={null}` widens the value past the
      // declared optional type and causes tsc errors for non-nullable prop types.
      if (v === undefined) return [];
      // Plain string with no fn markers → use JSON.stringify shorthand.
      // If the string contains a double-quote, JSON.stringify produces an
      // attribute value like "say \"hi\"" which JSX rejects. Emit as a
      // braced JS expression in that case so the string survives intact (#73).
      if (typeof v === "string" && !containsFnMarker(v)) {
        if (v.includes('"')) return [`${k}={${JSON.stringify(v)}}`];
        return [`${k}=${JSON.stringify(v)}`];
      }
      if (typeof v === "boolean") return [v ? k : `${k}={false}`];
      // Use serializeJSValue which handles FnMarker at any nesting depth
      return [`${k}={${serializeJSValue(v)}}`];
    })
    .join(" ");
}

/**
 * Levenshtein-1 distance check: returns true when `a` and `b` differ by exactly
 * one single-character insertion, deletion, or substitution. Used to detect
 * API-drift props (e.g. `variant` when the CVA key is `intent`).
 */
function isLevenshtein1(a: string, b: string): boolean {
  if (Math.abs(a.length - b.length) > 1) return false;
  if (a === b) return false;
  if (a.length === b.length) {
    // Substitution
    let diffs = 0;
    for (let i = 0; i < a.length; i++) {
      if (a[i] !== b[i] && ++diffs > 1) return false;
    }
    return diffs === 1;
  }
  // Insertion / deletion — ensure shorter is `s`, longer is `l`
  const [s, l] = a.length < b.length ? [a, b] : [b, a];
  let si = 0;
  let li = 0;
  let skipped = false;
  while (si < s.length && li < l.length) {
    if (s[si] !== l[li]) {
      if (skipped) return false;
      skipped = true;
      li++;
    } else {
      si++;
      li++;
    }
  }
  return true;
}

/**
 * Build the top-of-page Usage block from analyzer output cross-referenced with
 * the component's CVA config. Two rows:
 *   ✓ Used — (prop, value) pairs found in callsites that exist in the CVA, with counts
 *   ✗ Unknown at callsites — prop names that exactly match or are Levenshtein-1 close
 *     to a CVA variant name but carry a value the CVA doesn't declare. HTML attributes
 *     (className, type, aria-*, data-*, title, etc.) and non-CVA props are excluded.
 *
 * Returns "" when no analyzer was registered for the component or when both rows
 * would be empty.
 */
function emitUsageBlock(usage: UsageInfo | undefined, cvaConfig: CvaConfig | null): string {
  if (!usage) return "";
  const cvaVariantNames = cvaConfig ? Object.keys(cvaConfig.variants) : [];
  const used: string[] = [];
  const unknown: string[] = [];
  for (const [prop, valueMap] of usage.literal.entries()) {
    const cvaValues = cvaConfig?.variants[prop] ?? null;
    // A prop qualifies for the Unknown row only when its name is either:
    //   (a) an exact CVA variant name but carries a value outside that variant's enum, OR
    //   (b) Levenshtein-1 distance from a CVA variant name (API-drift detection)
    // This excludes className, type, aria-*, data-*, title, and other HTML pass-throughs.
    const isExactCvaVariant = cvaValues !== null;
    const isNearCvaVariant = !isExactCvaVariant && cvaVariantNames.some((v) => isLevenshtein1(prop, v));
    for (const [value, count] of valueMap.entries()) {
      if (count <= 0) continue;
      const label = `${prop}="${value}" (${count})`;
      if (isExactCvaVariant && cvaValues!.includes(value)) {
        used.push(label);
      } else if (isExactCvaVariant || isNearCvaVariant) {
        // Exact variant name with a value outside the enum, OR a near-miss variant name
        unknown.push(label);
      }
      // else: not a CVA variant at all — skip (HTML passthrough / unrelated prop)
    }
  }
  if (used.length === 0 && unknown.length === 0) return "";
  const usedRow = used.length > 0
    ? `        <div className="flex flex-wrap items-baseline gap-2 text-sm"><span aria-hidden="true">✓</span><span className="font-medium">Used</span><span className="text-muted-foreground">${used.join(" · ")}</span></div>`
    : "";
  const unknownRow = unknown.length > 0
    ? `        <div className="flex flex-wrap items-baseline gap-2 text-sm"><span aria-hidden="true">✗</span><span className="font-medium">Unknown at callsites</span><span className="text-muted-foreground">${unknown.join(" · ")}</span></div>`
    : "";
  return [
    `      <section className="mb-8 rounded-md border border-border bg-muted/30 p-4">`,
    `        <h2 className="text-sm font-semibold uppercase tracking-wide text-muted-foreground mb-2">Usage</h2>`,
    usedRow,
    unknownRow,
    `      </section>`,
  ].filter(Boolean).join("\n");
}

/**
 * Render carried refs as a block of source text to inject at the top of the
 * showcase: grouped imports by raw spec + `const` declarations for each local.
 * Order: imports first, then locals (so locals can reference imports).
 */
function renderCarriedRefs(carried: Map<string, CarriedRef>): string {
  if (carried.size === 0) return "";
  const importsBySpec = new Map<string, { plain: Set<string>; aliased: Map<string, string> }>();
  const typeImportsBySpec = new Map<string, { plain: Set<string>; aliased: Map<string, string> }>();
  // Collect locals as {name, rawSource} so we can topologically sort them before
  // emitting — discovery order has dependents before dependencies (the ref-walking
  // code finds `b` first, then recurses into `b` to find `a`), which would produce
  // TS2448 "used before declaration" when `b`'s rawSource references `a`.
  const localMap = new Map<string, string>(); // name → rawSource
  for (const [name, ref] of carried.entries()) {
    if (ref.kind === "import") {
      let group = importsBySpec.get(ref.rawSpec);
      if (!group) {
        group = { plain: new Set(), aliased: new Map() };
        importsBySpec.set(ref.rawSpec, group);
      }
      if (ref.localName === ref.exportedName) group.plain.add(ref.localName);
      else group.aliased.set(ref.localName, ref.exportedName);
    } else if (ref.kind === "type-import") {
      let group = typeImportsBySpec.get(ref.rawSpec);
      if (!group) {
        group = { plain: new Set(), aliased: new Map() };
        typeImportsBySpec.set(ref.rawSpec, group);
      }
      if (ref.localName === ref.exportedName) group.plain.add(ref.localName);
      else group.aliased.set(ref.localName, ref.exportedName);
    } else {
      // "local": collect for topological ordering below.
      localMap.set(name, ref.rawSource);
    }
  }

  // Topological sort of local consts so that dependencies are emitted before
  // dependents. Build a simple adjacency list: for each local, which other carried
  // locals does its rawSource reference? We detect references by scanning the
  // rawSource for each other local name as a word-boundary identifier match.
  // Kahn's algorithm (stable — preserves original order among independents).
  const localNames = Array.from(localMap.keys());
  const localNameSet = new Set(localNames);
  // inDegree[i] = number of locals that `localNames[i]` depends on (that are also carried)
  const inDegree = new Map<string, number>();
  // dependents[dep] = list of locals that reference dep
  const dependents = new Map<string, string[]>();
  for (const name of localNames) {
    inDegree.set(name, 0);
    dependents.set(name, []);
  }
  for (const name of localNames) {
    const src = localMap.get(name)!;
    for (const dep of localNames) {
      if (dep === name) continue;
      // Check if `name`'s rawSource contains `dep` as a standalone identifier.
      // Use word-boundary regex to avoid partial matches (e.g. "aColumn" matching "a").
      const re = new RegExp(`\\b${dep.replace(/[.*+?^${}()|[\]\\]/g, "\\$&")}\\b`);
      if (re.test(src)) {
        // `name` depends on `dep` — dep must come before name
        inDegree.set(name, (inDegree.get(name) ?? 0) + 1);
        dependents.get(dep)!.push(name);
      }
    }
  }
  const sorted: string[] = [];
  // Queue: all locals with no dependencies on other carried locals
  const queue: string[] = localNames.filter((n) => inDegree.get(n) === 0);
  while (queue.length > 0) {
    const name = queue.shift()!;
    sorted.push(name);
    for (const dependent of dependents.get(name) ?? []) {
      const newDegree = (inDegree.get(dependent) ?? 0) - 1;
      inDegree.set(dependent, newDegree);
      if (newDegree === 0) queue.push(dependent);
    }
  }
  // If cycle detected (shouldn't happen in practice), append remaining unsorted
  for (const name of localNames) {
    if (!sorted.includes(name)) sorted.push(name);
  }
  const locals = sorted.map((name) => localMap.get(name)!);

  const importLines: string[] = [];
  for (const [spec, group] of importsBySpec.entries()) {
    const parts: string[] = [];
    for (const n of group.plain) parts.push(n);
    for (const [local, exported] of group.aliased.entries()) parts.push(`${exported} as ${local}`);
    importLines.push(`import { ${parts.join(", ")} } from "${spec}";`);
  }
  const typeImportLines: string[] = [];
  for (const [spec, group] of typeImportsBySpec.entries()) {
    const parts: string[] = [];
    for (const n of group.plain) parts.push(n);
    for (const [local, exported] of group.aliased.entries()) parts.push(`${exported} as ${local}`);
    typeImportLines.push(`import type { ${parts.join(", ")} } from "${spec}";`);
  }
  return [...importLines, ...typeImportLines, ...locals].join("\n");
}

function emitAtomCompositeShowcase(
  componentName: string,
  displayName: string,
  meta: MetaAtomComposite,
  source: string,
  sourceName: string,
  usage?: UsageInfo,
  carried?: Map<string, CarriedRef>,
  useClient?: boolean
): string {
  const header = showcaseHeader(sourceName);
  const skip = meta.skip ?? [];

  // Explicit examples from meta.examples (authoritative — no children fallback applied)
  const explicitExamples: Array<{ name: string; props: Record<string, unknown> }> = [...meta.examples];

  // CVA auto-expansion. v0.7.8: do NOT dedup against explicit examples — Variants
  // is the exhaustive proof grid; overlap with Examples is intentional.
  const cvaConfig = parseCva(source);
  let cvaExamples: Array<{ name: string; props: Record<string, string> }> = [];
  if (cvaConfig) {
    cvaExamples = cvaCartesian(cvaConfig, skip);
  }

  const useClientLine = useClient ? `"use client";\n` : "";

  // Stub-meta: default stub with no CVA expansion → placeholder card, no component render.
  if (isStubMeta(meta.examples, cvaConfig)) {
    return [
      useClientLine + header,
      `import React from "react";`,
      ``,
      `export default function ${displayName}Showcase() {`,
      `  return (`,
      `    <main className="p-8">`,
      `      <h1 className="text-2xl font-bold mb-6">${displayName}</h1>`,
      `      <div className="rounded-md border border-dashed border-muted-foreground/30 bg-muted/30 p-6 text-sm text-muted-foreground">`,
      `        No examples defined. Backfill{" "}`,
      `        <code className="rounded bg-muted px-1">meta.examples</code> in{" "}`,
      `        <code className="rounded bg-muted px-1">design-system/&lt;tier&gt;/${componentName}.tsx</code>`,
      `        {" "}to render this component.`,
      `      </div>`,
      `    </main>`,
      `  );`,
      `}`,
      ``,
    ].join("\n");
  }

  // ── Explicit "Examples" section ──────────────────────────────────────────
  let explicitSection = "";
  if (explicitExamples.length > 0) {
    const blocks = explicitExamples
      .map((ex) => {
        const propsStr = renderPropsAttr(ex.props);
        return [
          `        <div className="flex flex-col items-start gap-1">`,
          `          <${displayName}${propsStr ? " " + propsStr : ""} />`,
          `          <span className="text-xs text-muted-foreground">${ex.name}</span>`,
          `        </div>`,
        ].join("\n");
      })
      .join("\n");
    explicitSection = [
      `      <section className="mb-10">`,
      `        <h2 className="text-xl font-semibold mb-4">Examples</h2>`,
      `        <div className="flex flex-wrap items-end gap-3">`,
      blocks,
      `        </div>`,
      `      </section>`,
    ].join("\n");
  }

  // ── CVA variant grid grouped by first axis ───────────────────────────────
  let cvaSection = "";
  if (cvaExamples.length > 0 && cvaConfig) {
    const variantNames = Object.keys(cvaConfig.variants);
    const primaryAxis = variantNames[0]; // e.g. "intent"
    const primaryValues = cvaConfig.variants[primaryAxis];

    const groupSections = primaryValues
      .map((primaryVal) => {
        const groupCombos = cvaExamples.filter((ce) => ce.props[primaryAxis] === primaryVal);
        if (groupCombos.length === 0) return null;

        const groupLabel = primaryVal.charAt(0).toUpperCase() + primaryVal.slice(1);

        const acceptsChildren = componentAcceptsChildren(source);
        const buttonBlocks = groupCombos
          .map((ce) => {
            const propsStr = Object.entries(ce.props)
              .map(([k, v]) => {
                // #66 / #67: boolean-shaped CVA axes (values literally "true"/"false")
                // must emit as JSX expressions `{true}`/`{false}` so the component's
                // boolean prop type accepts them. Plain string-valued axes stay quoted.
                if (v === "true") return `${k}={true}`;
                if (v === "false") return `${k}={false}`;
                return `${k}="${v}"`;
              })
              .join(" ");
            // Children fallback for auto-generated combos. Icon sizes get a
            // lucide Square placeholder; text sizes get the displayName —
            // but only when the component actually accepts children (#68).
            const children = autoChildren(ce.props, displayName, acceptsChildren);
            // Secondary axis label (everything except the primary axis)
            const secondaryLabel = Object.entries(ce.props)
              .filter(([k]) => k !== primaryAxis)
              .map(([, v]) => v)
              .join(", ");
            return [
              `          <div className="flex flex-col items-start gap-1">`,
              `            <${displayName}${propsStr ? " " + propsStr : ""}${children ? `>${children}</${displayName}>` : " />"}`,
              `            <span className="text-xs text-muted-foreground">${secondaryLabel || primaryVal}</span>`,
              `          </div>`,
            ].join("\n");
          })
          .filter(Boolean)
          .join("\n");

        return [
          `        <section className="mb-6">`,
          `          <h2 className="text-lg font-semibold mb-3">${groupLabel}</h2>`,
          `          <div className="flex flex-wrap items-end gap-3">`,
          buttonBlocks,
          `          </div>`,
          `        </section>`,
        ].join("\n");
      })
      .filter(Boolean)
      .join("\n");

    cvaSection = [
      `      <section className="mb-10">`,
      `        <h2 className="text-xl font-semibold mb-4">Variants</h2>`,
      groupSections,
      `      </section>`,
    ].join("\n");
  }

  // ── Top-of-page Usage block (analyzer-driven) ───────────────────────────
  const usageSection = emitUsageBlock(usage, cvaConfig);

  const body =
    usageSection || explicitSection || cvaSection
      ? [usageSection, explicitSection, cvaSection].filter(Boolean).join("\n")
      : `      <p className="text-muted-foreground">No examples defined.</p>`;

  const importLine = hasDefaultExport(source)
    ? `import ${displayName} from "./${componentName}";`
    : `import { ${displayName} } from "./${componentName}";`;

  // Square placeholder is injected for any icon-size cell without explicit children.
  const needsSquareImport = cvaExamples.some((ce) => {
    if ("children" in ce.props) return false;
    return isIconSize(ce.props["size"] ?? "");
  });
  const squareImportLine = needsSquareImport ? `import { Square } from "lucide-react";` : "";

  // #70: the explicit `importLine` above already imports the primary
  // displayName from "./<componentName>". If the carry mechanism also picked
  // it up (because it was a top-level function declaration registered in
  // importScope), drop it from `carried` to avoid emitting a duplicate import.
  if (carried) {
    const ref = carried.get(displayName);
    if (ref && ref.kind === "import" && ref.rawSpec === `./${componentName}`) {
      carried.delete(displayName);
    }
  }
  const carriedBlock = carried ? renderCarriedRefs(carried) : "";

  return [
    useClientLine + header,
    `import React from "react";`,
    ...(squareImportLine ? [squareImportLine] : []),
    importLine,
    ...(carriedBlock ? [carriedBlock] : []),
    ``,
    `export default function ${displayName}Showcase() {`,
    `  return (`,
    `    <main className="p-8">`,
    `      <h1 className="text-2xl font-bold mb-6">${displayName}</h1>`,
    body,
    `    </main>`,
    `  );`,
    `}`,
    ``,
  ].join("\n");
}

function emitReferenceShowcase(
  componentName: string,
  displayName: string,
  meta: MetaReference,
  sourceName: string,
  useClient?: boolean
): string {
  const header = showcaseHeader(sourceName);
  const useClientLine = useClient ? `"use client";\n` : "";
  return [
    useClientLine + header,
    `import React from "react";`,
    `import { meta } from "./${componentName}";`,
    ``,
    `export default function ${displayName}Showcase() {`,
    `  if (meta.kind !== "reference") return null;`,
    `  const content = meta.render();`,
    `  return (`,
    `    <main className="p-8">`,
    `      <h1 className="text-2xl font-bold mb-6">${meta.title}</h1>`,
    `      <div className="prose prose-neutral dark:prose-invert max-w-none">{content as React.ReactNode}</div>`,
    `    </main>`,
    `  );`,
    `}`,
    ``,
  ].join("\n");
}

// ── main ──────────────────────────────────────────────────────────────────────

async function loadUsageMap(cwd: string): Promise<UsageMap | null> {
  const analyzerPath = join(cwd, "scripts", "analyze-component-usage.ts");
  if (!existsSync(analyzerPath)) return null;
  // Collect candidate app source files: .ts / .tsx under app/, src/, components/, lib/
  const roots = ["app", "src", "components", "lib"];
  const files: string[] = [];
  function walk(dir: string): void {
    let entries: string[];
    try {
      entries = readdirSync(dir);
    } catch {
      return;
    }
    for (const e of entries) {
      if (e === "node_modules" || e.startsWith(".")) continue;
      const p = join(dir, e);
      let st;
      try {
        st = statSync(p, { throwIfNoEntry: false });
      } catch {
        continue;
      }
      if (!st) continue;
      if (st.isDirectory()) walk(p);
      else if (st.isFile() && (e.endsWith(".tsx") || e.endsWith(".ts")) && !e.endsWith(".d.ts")) {
        files.push(p);
      }
    }
  }
  for (const r of roots) {
    const rp = join(cwd, r);
    if (existsSync(rp)) walk(rp);
  }
  try {
    const mod = await import(analyzerPath);
    const fn = mod.default;
    if (typeof fn !== "function") {
      process.stderr.write(
        `analyze-component-usage.ts: default export is not a function — skipping usage tags\n`
      );
      return null;
    }
    const result = await fn(files);
    if (!(result instanceof Map)) {
      process.stderr.write(
        `analyze-component-usage.ts: did not return a Map — skipping usage tags\n`
      );
      return null;
    }
    return result as UsageMap;
  } catch (err) {
    process.stderr.write(
      `analyze-component-usage.ts: failed to load (${(err as Error).message}) — skipping usage tags\n`
    );
    return null;
  }
}

async function main(): Promise<void> {
  const cwd = process.cwd();
  const usageMap = await loadUsageMap(cwd);

  const TIERS = ["atoms", "composites", "references"] as const;
  const COMPANION_SUFFIXES = [".showcase.tsx", ".test.tsx", ".stories.tsx"];
  const SKIP_PATTERNS = [/^index\.ts$/, /\.logic\.ts$/, /\.d\.ts$/];

  let processed = 0;
  let skipped = 0;
  let errors = 0;

  for (const tier of TIERS) {
    const tierDir = join(cwd, "design-system", tier);
    if (!existsSync(tierDir)) continue;

    let entries: string[];
    try {
      entries = readdirSync(tierDir);
    } catch {
      continue;
    }

    for (const entry of entries) {
      if (entry === ".keep" || entry === ".gitkeep") continue;
      if (!entry.endsWith(".tsx")) continue;
      if (COMPANION_SUFFIXES.some((s) => entry.endsWith(s))) continue;
      if (SKIP_PATTERNS.some((re) => re.test(entry))) continue;

      const entryPath = join(tierDir, entry);
      const entryStat = statSync(entryPath, { throwIfNoEntry: false });
      if (!entryStat || !entryStat.isFile()) continue;

      const componentName = basename(entry, ".tsx");
      const displayName = toPascalCase(componentName);
      const sourceName = entry; // e.g. "button.tsx"

      let source: string;
      try {
        source = readFileSync(entryPath, "utf8");
      } catch {
        process.stderr.write(`generate-showcase-companion: cannot read ${entryPath}\n`);
        skipped++;
        continue;
      }

      const astExtract = extractMetaFromAST(entryPath);
      const meta: ParsedMeta | null = astExtract ? astExtract.meta : parseMeta(source);
      const carried = astExtract?.carried;
      const useClient = astExtract?.useClient ?? false;
      if (!meta) {
        process.stderr.write(
          `${entryPath}:0: GEN-000: no meta export found — skipping companion generation\n`
        );
        skipped++;
        continue;
      }

      const showcasePath = join(tierDir, `${componentName}.showcase.tsx`);
      let showcaseContent: string;

      if (meta.kind === "reference") {
        showcaseContent = emitReferenceShowcase(componentName, displayName, meta, sourceName, useClient);
      } else if (isNamespaceOnlyExport(entryPath, displayName)) {
        // #69 / #92: namespace-only export (e.g. `export const Skeleton = { Line, Block, Circle }`).
        // The component is not callable — we cannot emit `<Skeleton ... />` JSX for it, but
        // that is a per-component limitation, not a fatal run error. Skip this component,
        // preserve any hand-authored .showcase.tsx, and continue with the rest of the run.
        process.stderr.write(
          `${entryPath}:0: GEN-069: \`${displayName}\` is a namespace-only export (object literal, not callable). ` +
          `Generator cannot emit <${displayName} ... /> JSX. ` +
          `Either (a) hand-author \`${componentName}.showcase.tsx\` beside this file (it will be preserved across runs), ` +
          `or (b) export a top-level callable \`${displayName}\` component alongside the namespace object.\n`
        );
        errors++;
        continue;
      } else {
        const usage = usageMap?.get(displayName) ?? usageMap?.get(componentName);
        showcaseContent = emitAtomCompositeShowcase(componentName, displayName, meta, source, sourceName, usage, carried, useClient);
      }

      write(showcasePath, showcaseContent);
      console.log(`generate-showcase-companion: wrote ${showcasePath}`);
      processed++;
    }
  }

  console.log(
    `generate-showcase-companion: done — ${processed} component(s) processed, ${skipped} skipped` +
    (errors > 0 ? `, ${errors} error(s)` : "")
  );
  if (errors > 0) process.exit(1);
}

main().catch((err) => {
  process.stderr.write(`generate-showcase-companion: ${(err as Error).message}\n`);
  process.exit(1);
});
