#!/usr/bin/env node --experimental-strip-types
/**
 * generate-showcase-companion.ts — Generates per-component .showcase.tsx and .states.json
 * from the `meta` export in each design-system component source file.
 *
 * Emits for each .tsx under design-system/{atoms,composites,references}/:
 *   <name>.showcase.tsx    — JSX that renders all examples (with @generated header)
 *   <name>.states.json     — states list (with __generated marker)
 *
 * For kind "atom" | "composite": renders each examples[] entry with props spread.
 *   If cva() is detected in source, also auto-expands the CVA variant cross-product.
 *   Suppresses combos listed in skip[].
 * For kind "reference": renders meta.render() call.
 *
 * Usage: node --experimental-strip-types scripts/generate-showcase-companion.ts
 *        (or: tsx scripts/generate-showcase-companion.ts)
 *
 * Exit 0 success, 1 self-error.
 */

import { existsSync, mkdirSync, readFileSync, readdirSync, statSync, writeFileSync } from "node:fs";
import { join, dirname, basename } from "node:path";

// ── header constants ──────────────────────────────────────────────────────────

function showcaseHeader(sourceName: string): string {
  return [
    `// @generated by claude-ds — do not edit. Source: ${sourceName} meta block.`,
    `// @ts-nocheck`,
    `// Transitional: generated showcase props are not typechecked until per-component`,
    `// meta.examples are backfilled to satisfy the component's actual prop types.`,
  ].join("\n");
}

const GENERATED_MARKER_KEY = "__generated";
function generatedMarkerValue(sourceName: string): string {
  return `@generated by claude-ds — do not edit. Source: ${sourceName} meta block.`;
}

// ── helpers ───────────────────────────────────────────────────────────────────

function toPascalCase(name: string): string {
  return name
    .split(/[-_\s]+/)
    .filter(Boolean)
    .map((segment) => segment.charAt(0).toUpperCase() + segment.slice(1))
    .join("");
}

function ensureDir(filePath: string): void {
  mkdirSync(dirname(filePath), { recursive: true });
}

function write(filePath: string, content: string): void {
  ensureDir(filePath);
  writeFileSync(filePath, content, "utf8");
}

/**
 * Detect whether a source file has a default export.
 * Strips line/block comments and string literals first to avoid false positives
 * from "export default" appearing in comments or string values.
 */
function hasDefaultExport(source: string): boolean {
  // Strip block comments
  let stripped = source.replace(/\/\*[\s\S]*?\*\//g, "");
  // Strip line comments
  stripped = stripped.replace(/\/\/[^\n]*/g, "");
  // Strip string literals
  stripped = stripped
    .replace(/"(?:[^"\\]|\\.)*"/g, '""')
    .replace(/'(?:[^'\\]|\\.)*'/g, "''")
    .replace(/`(?:[^`\\]|\\.)*`/g, "``");
  return /^\s*export\s+default\s+/m.test(stripped);
}

/**
 * Strip all string literals (double-quoted, single-quoted, template literals)
 * from a block of source text. Used before scanning for CVA variant keys so
 * that Tailwind modifier prefixes like `hover:`, `focus:`, `aria-expanded:`
 * inside class strings are not mistaken for variant names.
 */
function stripStringLiterals(text: string): string {
  // Replace double-quoted strings
  let result = text.replace(/"(?:[^"\\]|\\.)*"/g, '""');
  // Replace single-quoted strings
  result = result.replace(/'(?:[^'\\]|\\.)*'/g, "''");
  // Replace template literals (simple, non-nested)
  result = result.replace(/`(?:[^`\\]|\\.)*`/g, "``");
  return result;
}

/**
 * Generate a human-readable label from a combo key like "intent=primary_size=sm".
 * Output: "Primary · sm"  (title-case first axis value, keep remaining as-is)
 */
function prettyLabel(comboKey: string): string {
  return comboKey
    .split("_")
    .map((part) => {
      const eqIdx = part.indexOf("=");
      const value = eqIdx >= 0 ? part.slice(eqIdx + 1) : part;
      // Title-case the first character
      return value.charAt(0).toUpperCase() + value.slice(1);
    })
    .join(" · ");
}

// ── meta parsing ──────────────────────────────────────────────────────────────

interface Example {
  name: string;
  props: Record<string, unknown>;
}

interface MetaAtomComposite {
  kind: "atom" | "composite";
  fixtures?: Record<string, unknown>;
  examples: Example[];
  skip?: string[];
}

interface MetaReference {
  kind: "reference";
  title: string;
}

type ParsedMeta = MetaAtomComposite | MetaReference;

/**
 * Regex-based meta extraction from source.
 * Finds `export const meta = { ... }` and evaluates the shape.
 * This is intentionally simple — works for JSON-compatible meta values.
 * Dynamic import would require esbuild/tsx runtime in the consumer which we cannot guarantee.
 */
function parseMeta(source: string): ParsedMeta | null {
  // Find 'export const meta' and grab the kind
  const kindMatch = source.match(/export\s+const\s+meta[^=]*=\s*\{[^}]*kind\s*:\s*["']([^"']+)["']/);
  if (!kindMatch) return null;

  const kind = kindMatch[1] as "atom" | "composite" | "reference";

  if (kind === "reference") {
    // Extract title
    const titleMatch = source.match(/kind\s*:\s*["']reference["'][^}]*title\s*:\s*["']([^"']+)["']/s)
      ?? source.match(/title\s*:\s*["']([^"']+)["'][^}]*kind\s*:\s*["']reference["']/s);
    const title = titleMatch ? titleMatch[1] : "Reference";
    return { kind: "reference", title };
  }

  // atom | composite — extract examples[] and skip[]
  const examples = parseExamples(source);
  const skip = parseSkip(source);
  return { kind, examples, skip };
}

function parseExamples(source: string): Example[] {
  // Find examples array in meta
  const examplesMatch = source.match(/examples\s*:\s*(\[[\s\S]*?\])\s*(?:,|\})/);
  if (!examplesMatch) return [];

  try {
    // Replace JS-style property shorthand, functions, etc. with JSON-safe equivalents.
    // We support: name: "string", props: { key: "val", key2: 123, key3: true/false/null }
    const raw = examplesMatch[1];
    // Attempt JSON.parse after light sanitization
    const sanitized = raw
      .replace(/\/\/[^\n]*/g, "") // remove line comments
      .replace(/,\s*([\]}])/g, "$1") // trailing commas
      .replace(/([{,]\s*)(\w+)\s*:/g, '$1"$2":') // unquoted keys
      .replace(/:\s*undefined\b/g, ": null") // undefined → null
      .replace(/:\s*'([^']*)'/g, ':"$1"'); // single-quoted strings → double-quoted
    const parsed = JSON.parse(sanitized);
    if (!Array.isArray(parsed)) return [];
    return parsed.map((e: unknown) => {
      const obj = e as Record<string, unknown>;
      return {
        name: typeof obj.name === "string" ? obj.name : "unnamed",
        props: typeof obj.props === "object" && obj.props !== null
          ? (obj.props as Record<string, unknown>)
          : {},
      };
    });
  } catch {
    return [];
  }
}

function parseSkip(source: string): string[] {
  const skipMatch = source.match(/skip\s*:\s*(\[[\s\S]*?\])\s*(?:,|\})/);
  if (!skipMatch) return [];
  try {
    const raw = skipMatch[1]
      .replace(/\/\/[^\n]*/g, "")
      .replace(/,\s*\]/g, "]")
      .replace(/'/g, '"');
    const parsed = JSON.parse(raw);
    return Array.isArray(parsed) ? parsed.filter((s) => typeof s === "string") : [];
  } catch {
    return [];
  }
}

// ── CVA parsing ───────────────────────────────────────────────────────────────

interface CvaConfig {
  variants: Record<string, string[]>;
  defaultVariants: Record<string, string>;
}

/**
 * Parse cva() call from source to extract variant keys and values.
 * Pattern: cva(base, { variants: { size: { sm: "...", md: "..." }, tone: { ... } }, defaultVariants: { ... } })
 */
function parseCva(source: string): CvaConfig | null {
  if (!source.includes("cva(")) return null;

  // Extract variants block from cva() call
  const variantsMatch = source.match(/cva\s*\([^)]*\{\s*variants\s*:\s*(\{[\s\S]*?\})\s*(?:,\s*defaultVariants|\})\s*\)/);
  if (!variantsMatch) {
    // Try a broader match for multi-line cva definitions
    const broadMatch = source.match(/variants\s*:\s*\{([\s\S]*?)\}\s*(?:,\s*(?:defaultVariants|compoundVariants)|\s*\}\s*\))/);
    if (!broadMatch) return null;

    try {
      const varBlock = `{${broadMatch[1]}}`;
      const variants = extractVariantKeys(varBlock, source);
      const defaultVariants = extractDefaultVariants(source);
      if (Object.keys(variants).length === 0) return null;
      return { variants, defaultVariants };
    } catch {
      return null;
    }
  }

  try {
    const variants = extractVariantKeys(variantsMatch[1], source);
    const defaultVariants = extractDefaultVariants(source);
    return { variants, defaultVariants };
  } catch {
    return null;
  }
}

function extractVariantKeys(variantsBlock: string, _source: string): Record<string, string[]> {
  const result: Record<string, string[]> = {};
  // Strip string literals first so Tailwind modifier prefixes (hover:, focus:, etc.)
  // inside class value strings are not mistaken for variant keys.
  const stripped = stripStringLiterals(variantsBlock);

  // Match each variant key and its value object (unquoted variant names only after stripping)
  const variantRe = /(\w+)\s*:\s*\{([^}]*)\}/g;
  let m: RegExpExecArray | null;
  while ((m = variantRe.exec(stripped)) !== null) {
    const variantName = m[1];
    const strippedValuesBlock = m[2];

    // For value keys we need BOTH unquoted identifiers (from stripped block) AND
    // quoted identifiers like "icon-sm" (which were removed by stripping).
    // Locate the original values block for this variant name.
    const origVariantRe = new RegExp(`(?:^|[{,\\s])${variantName}\\s*:\\s*\\{([^}]*)\\}`);
    const origMatch = variantsBlock.match(origVariantRe);
    const origValuesBlock = origMatch ? origMatch[1] : strippedValuesBlock;

    const valueKeys: string[] = [];

    // Unquoted keys from the stripped block (no Tailwind modifier leakage)
    const keyRe = /(\w+)\s*:/g;
    let km: RegExpExecArray | null;
    while ((km = keyRe.exec(strippedValuesBlock)) !== null) {
      valueKeys.push(km[1]);
    }

    // Quoted keys from the original block (e.g. "icon-sm": ..., 'icon-lg': ...)
    const quotedKeyRe = /["']([^"']+)["']\s*:/g;
    let qm: RegExpExecArray | null;
    while ((qm = quotedKeyRe.exec(origValuesBlock)) !== null) {
      if (!valueKeys.includes(qm[1])) {
        valueKeys.push(qm[1]);
      }
    }

    if (valueKeys.length > 0) {
      result[variantName] = valueKeys;
    }
  }
  return result;
}

function extractDefaultVariants(source: string): Record<string, string> {
  const dvMatch = source.match(/defaultVariants\s*:\s*\{([^}]*)\}/);
  if (!dvMatch) return {};
  const result: Record<string, string> = {};
  const kvRe = /(\w+)\s*:\s*["']?(\w+)["']?/g;
  let m: RegExpExecArray | null;
  while ((m = kvRe.exec(dvMatch[1])) !== null) {
    result[m[1]] = m[2];
  }
  return result;
}

/** Generate the full cross-product of CVA variants, minus skipped combos. */
function cvaCartesian(config: CvaConfig, skip: string[]): Array<{ name: string; props: Record<string, string> }> {
  const variantNames = Object.keys(config.variants);
  if (variantNames.length === 0) return [];

  const values = variantNames.map((k) => config.variants[k]);

  // Cartesian product
  function product(arrays: string[][]): string[][] {
    return arrays.reduce<string[][]>(
      (acc, cur) => acc.flatMap((a) => cur.map((b) => [...a, b])),
      [[]]
    );
  }

  const combos = product(values);

  return combos
    .map((combo) => {
      const props: Record<string, string> = {};
      const nameParts: string[] = [];
      variantNames.forEach((vk, i) => {
        props[vk] = combo[i];
        nameParts.push(`${vk}=${combo[i]}`);
      });
      return { name: nameParts.join("_"), props };
    })
    .filter((c) => !skip.includes(c.name));
}

// ── showcase emitters ─────────────────────────────────────────────────────────

/**
 * Determine if a size value name refers to an icon-only button slot.
 * Used to decide whether to inject text children.
 */
function isIconSize(sizeValue: string): boolean {
  return sizeValue.includes("icon");
}

/**
 * Build the children prop string for an auto-generated CVA combo.
 * Icon sizes get no children; everything else gets the display name as text.
 */
function autoChildren(props: Record<string, string>, displayName: string): string {
  const sizeVal = props["size"] ?? "";
  if (isIconSize(sizeVal)) return "";
  return displayName;
}

function emitAtomCompositeShowcase(
  componentName: string,
  displayName: string,
  meta: MetaAtomComposite,
  source: string,
  sourceName: string
): string {
  const header = showcaseHeader(sourceName);
  const skip = meta.skip ?? [];

  // Explicit examples from meta.examples (authoritative — no children fallback applied)
  const explicitExamples: Array<{ name: string; props: Record<string, unknown> }> = [...meta.examples];

  // CVA auto-expansion
  const cvaConfig = parseCva(source);
  let cvaExamples: Array<{ name: string; props: Record<string, string> }> = [];
  if (cvaConfig) {
    const expanded = cvaCartesian(cvaConfig, skip);
    const existingNames = new Set(meta.examples.map((e) => e.name));
    cvaExamples = expanded.filter((ce) => !existingNames.has(ce.name));
  }

  // ── Explicit "Examples" section ──────────────────────────────────────────
  let explicitSection = "";
  if (explicitExamples.length > 0) {
    const blocks = explicitExamples
      .map((ex) => {
        const propsStr = Object.entries(ex.props)
          .map(([k, v]) => {
            if (typeof v === "string") return `${k}="${v}"`;
            if (typeof v === "boolean") return v ? k : `${k}={false}`;
            return `${k}={${JSON.stringify(v)}}`;
          })
          .join(" ");
        return [
          `        <div className="flex flex-col items-start gap-1">`,
          `          <${displayName}${propsStr ? " " + propsStr : ""} />`,
          `          <span className="text-xs text-muted-foreground">${ex.name}</span>`,
          `        </div>`,
        ].join("\n");
      })
      .join("\n");
    explicitSection = [
      `      <section className="mb-10">`,
      `        <h2 className="text-xl font-semibold mb-4">Examples</h2>`,
      `        <div className="flex flex-wrap items-end gap-3">`,
      blocks,
      `        </div>`,
      `      </section>`,
    ].join("\n");
  }

  // ── CVA variant grid grouped by first axis ───────────────────────────────
  let cvaSection = "";
  if (cvaExamples.length > 0 && cvaConfig) {
    const variantNames = Object.keys(cvaConfig.variants);
    const primaryAxis = variantNames[0]; // e.g. "intent"
    const primaryValues = cvaConfig.variants[primaryAxis];

    const groupSections = primaryValues
      .map((primaryVal) => {
        const groupCombos = cvaExamples.filter((ce) => ce.props[primaryAxis] === primaryVal);
        if (groupCombos.length === 0) return null;

        const groupLabel = primaryVal.charAt(0).toUpperCase() + primaryVal.slice(1);

        const buttonBlocks = groupCombos
          .map((ce) => {
            const propsStr = Object.entries(ce.props)
              .map(([k, v]) => `${k}="${v}"`)
              .join(" ");
            // Children fallback for auto-generated combos
            const children = autoChildren(ce.props, displayName);
            // Secondary axis label (everything except the primary axis)
            const secondaryLabel = Object.entries(ce.props)
              .filter(([k]) => k !== primaryAxis)
              .map(([, v]) => v)
              .join(", ");
            return [
              `          <div className="flex flex-col items-start gap-1">`,
              `            <${displayName}${propsStr ? " " + propsStr : ""}${children ? `>${children}</${displayName}>` : " />"}`,
              `            <span className="text-xs text-muted-foreground">${secondaryLabel || primaryVal}</span>`,
              `          </div>`,
            ].join("\n");
          })
          .filter(Boolean)
          .join("\n");

        return [
          `        <section className="mb-6">`,
          `          <h2 className="text-lg font-semibold mb-3">${groupLabel}</h2>`,
          `          <div className="flex flex-wrap items-end gap-3">`,
          buttonBlocks,
          `          </div>`,
          `        </section>`,
        ].join("\n");
      })
      .filter(Boolean)
      .join("\n");

    cvaSection = [
      `      <section className="mb-10">`,
      `        <h2 className="text-xl font-semibold mb-4">Variants</h2>`,
      groupSections,
      `      </section>`,
    ].join("\n");
  }

  const body =
    explicitSection || cvaSection
      ? [explicitSection, cvaSection].filter(Boolean).join("\n")
      : `      <p className="text-muted-foreground">No examples defined.</p>`;

  const importLine = hasDefaultExport(source)
    ? `import ${displayName} from "./${componentName}";`
    : `import { ${displayName} } from "./${componentName}";`;

  return [
    header,
    `import React from "react";`,
    importLine,
    ``,
    `export default function ${displayName}Showcase() {`,
    `  return (`,
    `    <main className="p-8">`,
    `      <h1 className="text-2xl font-bold mb-6">${displayName}</h1>`,
    body,
    `    </main>`,
    `  );`,
    `}`,
    ``,
  ].join("\n");
}

function emitReferenceShowcase(
  componentName: string,
  displayName: string,
  meta: MetaReference,
  sourceName: string
): string {
  const header = showcaseHeader(sourceName);
  return [
    header,
    `import React from "react";`,
    `import { meta } from "./${componentName}";`,
    ``,
    `export default function ${displayName}Showcase() {`,
    `  if (meta.kind !== "reference") return null;`,
    `  const content = meta.render();`,
    `  return (`,
    `    <main className="p-8">`,
    `      <h1 className="text-2xl font-bold mb-6">${meta.title}</h1>`,
    `      <div className="prose prose-neutral dark:prose-invert max-w-none">{content as React.ReactNode}</div>`,
    `    </main>`,
    `  );`,
    `}`,
    ``,
  ].join("\n");
}

function emitStatesJson(
  examples: Array<{ name: string; props: Record<string, unknown> }>,
  sourceName: string
): string {
  const markerValue = generatedMarkerValue(sourceName);
  const obj = {
    [GENERATED_MARKER_KEY]: markerValue,
    states: examples.map((ex) => ({ label: ex.name, props: ex.props })),
  };
  return JSON.stringify(obj, null, 2) + "\n";
}

// ── main ──────────────────────────────────────────────────────────────────────

function main(): void {
  const cwd = process.cwd();

  const TIERS = ["atoms", "composites", "references"] as const;
  const COMPANION_SUFFIXES = [".showcase.tsx", ".states.json", ".test.tsx", ".stories.tsx"];
  const SKIP_PATTERNS = [/^index\.ts$/, /\.logic\.ts$/, /\.d\.ts$/];

  let processed = 0;
  let skipped = 0;

  for (const tier of TIERS) {
    const tierDir = join(cwd, "design-system", tier);
    if (!existsSync(tierDir)) continue;

    let entries: string[];
    try {
      entries = readdirSync(tierDir);
    } catch {
      continue;
    }

    for (const entry of entries) {
      if (entry === ".keep" || entry === ".gitkeep") continue;
      if (!entry.endsWith(".tsx")) continue;
      if (COMPANION_SUFFIXES.some((s) => entry.endsWith(s))) continue;
      if (SKIP_PATTERNS.some((re) => re.test(entry))) continue;

      const entryPath = join(tierDir, entry);
      const entryStat = statSync(entryPath, { throwIfNoEntry: false });
      if (!entryStat || !entryStat.isFile()) continue;

      const componentName = basename(entry, ".tsx");
      const displayName = toPascalCase(componentName);
      const sourceName = entry; // e.g. "button.tsx"

      let source: string;
      try {
        source = readFileSync(entryPath, "utf8");
      } catch {
        process.stderr.write(`generate-showcase-companion: cannot read ${entryPath}\n`);
        skipped++;
        continue;
      }

      const meta = parseMeta(source);
      if (!meta) {
        process.stderr.write(
          `${entryPath}:0: GEN-000: no meta export found — skipping companion generation\n`
        );
        skipped++;
        continue;
      }

      const showcasePath = join(tierDir, `${componentName}.showcase.tsx`);
      const statesPath = join(tierDir, `${componentName}.states.json`);

      let showcaseContent: string;
      let allExamples: Array<{ name: string; props: Record<string, unknown> }>;

      if (meta.kind === "reference") {
        showcaseContent = emitReferenceShowcase(componentName, displayName, meta, sourceName);
        allExamples = [];
      } else {
        // Compute full example list (explicit + CVA cross-product) for states.json
        const skip = meta.skip ?? [];
        allExamples = [...meta.examples];
        const cvaConfig = parseCva(source);
        if (cvaConfig) {
          const cvaExamples = cvaCartesian(cvaConfig, skip);
          const existingNames = new Set(meta.examples.map((e) => e.name));
          for (const ce of cvaExamples) {
            if (!existingNames.has(ce.name)) {
              allExamples.push({ name: ce.name, props: ce.props });
            }
          }
        }
        showcaseContent = emitAtomCompositeShowcase(componentName, displayName, meta, source, sourceName);
      }

      const statesContent = emitStatesJson(allExamples, sourceName);

      write(showcasePath, showcaseContent);
      write(statesPath, statesContent);
      console.log(`generate-showcase-companion: wrote ${showcasePath}`);
      console.log(`generate-showcase-companion: wrote ${statesPath}`);
      processed++;
    }
  }

  console.log(
    `generate-showcase-companion: done — ${processed} component(s) processed, ${skipped} skipped`
  );
}

main();
