import { mkdir, readFile, writeFile } from "node:fs/promises";
import { join, resolve } from "node:path";
import { describe, expect, it } from "vitest";
import type { DriftFinding } from "../../src/lib/drift/index.js";
import { getFixer } from "../../src/lib/drift/index.js";
import { compileEmitted } from "../helpers/compile-emitted";
import { makeFakeCtx } from "../helpers/fake-ctx";
import { cleanup, freshTmpDir } from "../helpers/tmpdir";

/**
 * Compile-what-you-emit, fixer edition (PRD #546, issue #554).
 *
 * String assertions prove the CVA-unrendered fixer wrote the *bytes* we expect;
 * they cannot prove the consumer's compiler accepts those examples once they
 * reach the real component. This test closes that gap: it runs the real fixer
 * over the canonical Crewops-shape atom (a multi-CVA file with a sub-element
 * cva() and a boolean axis), renders the examples it wrote onto `<CrewopsAtom>`,
 * and typechecks that showcase against the fixture's own tsconfig semantics.
 *
 * The old file-wide regex parser would have written `density="roomy"` (a
 * sub-element axis) and `invalid="true"` (a boolean-as-string) — both type
 * errors here. The analyzer-backed fixer writes only `tone` / `invalid` with
 * correct types, so the emitted showcase compiles clean.
 */

const FIXTURE_ROOT = resolve("packs/next-react/tests/fixtures/compile-what-you-emit");
const ATOM_REL = "design-system/atoms/crewops-atom.tsx";
const SHOWCASE_REL = "design-system/atoms/crewops-atom.showcase.tsx";

/** Render the props of one emitted meta example as JSX attributes. */
function exampleToJsx(propsInner: string): string {
	const attrs = propsInner
		.replace(/(\w+):\s*"([^"]*)"/g, '$1="$2"')
		.replace(/(\w+):\s*(true|false)\b/g, "$1={$2}")
		.trim();
	return `      <CrewopsAtom ${attrs} />`;
}

/** Build a showcase that renders every example the fixer wrote onto the real component. */
function renderShowcase(fixedAtom: string): string {
	const examplesBlock = fixedAtom.match(/examples:\s*\[([\s\S]*?)\]/);
	const inner = examplesBlock?.[1] ?? "";
	const rows: string[] = [];
	const propsRe = /props:\s*\{([^}]*)\}/g;
	for (const m of inner.matchAll(propsRe)) rows.push(exampleToJsx(m[1]));

	return [
		"// @generated by claude-ds — do not edit. Source: crewops-atom.tsx meta block.",
		'import React from "react";',
		'import { CrewopsAtom } from "./crewops-atom";',
		"",
		"export default function CrewopsAtomShowcase() {",
		"  return (",
		'    <main className="p-8">',
		...rows,
		"    </main>",
		"  );",
		"}",
		"",
	].join("\n");
}

describe("CVA-unrendered fixer output typechecks against the real component", () => {
	it("renders only props the exported component accepts, with correct types", async () => {
		const dir = await freshTmpDir("fixer-cwye-");
		try {
			// Start from the canonical Crewops fixture atom, examples reset to empty
			// so the fixer is the sole author of what lands in meta.examples.
			const fixtureAtom = await readFile(join(FIXTURE_ROOT, ATOM_REL), "utf8");
			const cleanAtom = fixtureAtom.replace(/examples:\s*\[[\s\S]*?\]/, "examples: []");

			await mkdir(join(dir, "design-system/atoms"), { recursive: true });
			await writeFile(join(dir, ATOM_REL), cleanAtom);

			const finding: DriftFinding = {
				ruleId: "DRIFT-CVA-VARIANT-UNRENDERED",
				file: ATOM_REL,
				message: "unexercised",
			};
			const fixer = getFixer("DRIFT-CVA-VARIANT-UNRENDERED");
			if (!fixer) throw new Error("no fixer registered for DRIFT-CVA-VARIANT-UNRENDERED");
			const result = await fixer(finding, makeFakeCtx(dir));
			expect(result.fixed).toBe(true);

			const fixedAtom =
				result.changes[0].kind === "write" ? result.changes[0].after.toString() : "";
			const showcase = renderShowcase(fixedAtom);

			// Sanity: the fixer exercised both of CrewopsAtom's real axes…
			expect(showcase).toContain('tone="neutral"');
			expect(showcase).toContain('tone="accent"');
			expect(showcase).toContain("invalid={true}");
			expect(showcase).toContain("invalid={false}");
			// …and never the sub-element axis.
			expect(showcase).not.toContain("density");

			// The ground truth: does the consumer's compiler accept it?
			const compiled = compileEmitted(
				[
					{ path: ATOM_REL, content: fixedAtom },
					{ path: SHOWCASE_REL, content: showcase },
				],
				FIXTURE_ROOT,
			);
			expect(compiled.hasErrors, compiled.messages.join("\n")).toBe(false);
		} finally {
			await cleanup(dir);
		}
	});
});

/**
 * Sub-part axis collision (#569 fixture triage).
 *
 * The name-shape residue heuristic (DRIFT-META-EXAMPLES-INVALID-PROP) flags a
 * prop named after a cva axis that the showcased root does NOT carry as a
 * "leaked sub-element axis." But when the ROOT component genuinely declares a
 * prop whose name happens to collide with an internal sub-part's axis, that prop
 * is real, not residue — and dropping it would break the consumer.
 *
 * Per PRD #566 the type oracle, not the name shape, is the correctness gate:
 * because the component's own prop type accepts `density`, the emitted showcase
 * typechecks. This pins that guarantee mechanically at the oracle layer.
 */
describe("type oracle treats a hand-authored prop colliding with a sub-part axis as real", () => {
	const COMPONENT_REL = "design-system/atoms/multi-part-atom.tsx";
	const COMPONENT_SHOWCASE_REL = "design-system/atoms/multi-part-atom.showcase.tsx";

	const component = [
		'import { cva, type VariantProps } from "class-variance-authority";',
		"",
		'const rootVariants = cva("root", {',
		'  variants: { tone: { neutral: "n", accent: "a" } },',
		"});",
		"",
		"// Sub-part cva: `density` is the Marker's axis, attributed to no exported",
		"// component — exactly the shape the residue heuristic would flag on the root.",
		'const markerVariants = cva("marker", {',
		'  variants: { density: { compact: "c", roomy: "r" } },',
		"});",
		"",
		"function Marker(props: VariantProps<typeof markerVariants>) {",
		"  return <span className={markerVariants(props)} />;",
		"}",
		"",
		"export type MultiPartAtomProps = VariantProps<typeof rootVariants> & {",
		"  // Hand-authored prop whose NAME collides with the sub-part's `density`",
		"  // axis, yet is a real prop of the root.",
		'  density?: "compact" | "roomy";',
		"};",
		"",
		"export function MultiPartAtom({ tone, density }: MultiPartAtomProps) {",
		"  return (",
		"    <span className={rootVariants({ tone })}>",
		'      <Marker density={density ?? "compact"} />',
		"    </span>",
		"  );",
		"}",
		"",
	].join("\n");

	function showcase(attrs: string): string {
		return [
			"// @generated by claude-ds — do not edit. Source: multi-part-atom.tsx meta block.",
			'import React from "react";',
			'import { MultiPartAtom } from "./multi-part-atom";',
			"",
			"export default function MultiPartAtomShowcase() {",
			"  return (",
			'    <main className="p-8">',
			`      <MultiPartAtom ${attrs} />`,
			"    </main>",
			"  );",
			"}",
			"",
		].join("\n");
	}

	it("accepts the colliding hand-authored prop (plausibly real, not residue)", () => {
		const compiled = compileEmitted(
			[
				{ path: COMPONENT_REL, content: component },
				{ path: COMPONENT_SHOWCASE_REL, content: showcase('tone="accent" density="roomy"') },
			],
			FIXTURE_ROOT,
		);
		expect(compiled.hasErrors, compiled.messages.join("\n")).toBe(false);
	});

	it("still rejects a genuinely non-existent prop (the oracle is a real gate)", () => {
		const compiled = compileEmitted(
			[
				{ path: COMPONENT_REL, content: component },
				{ path: COMPONENT_SHOWCASE_REL, content: showcase('bogus="x"') },
			],
			FIXTURE_ROOT,
		);
		expect(compiled.hasErrors).toBe(true);
	});
});
