/**
 * Issue #534 / PRD #529 defect 5 — shared output aggregation, end-to-end.
 *
 * The Crewops heal run printed 62 identical "skipped — verify by hand" lines:
 * reconform's generated-integrity phase hand-rolled a per-file loop with no
 * collapse. Two pins here, both against the non-TTY byte stream (the agent
 * surface):
 *
 *   1. Defect-5 regression: many same-kind skipped notices collapse to one
 *      summary line + a `--verbose` hint; `--verbose` restores the full list.
 *   2. No-repeated-line grammar invariant: over a representative set of command
 *      transcripts run against a realistically-adopted consumer, no same-kind
 *      per-file line template repeats past `NOTICE_COLLAPSE_THRESHOLD` — so a
 *      new command or renderer that walls its output is caught here, not in a
 *      consumer.
 *
 * The fixture is a real `adopt` (scaffold present, tree healthy) plus a handful
 * of JSX-bearing composites the integrity check must skip — the exact shape
 * that reproduced defect 5. Adopting once into a template and copying per test
 * keeps the suite inside the PRD speed budget.
 */

import { cp, mkdir, writeFile } from "node:fs/promises";
import { join } from "node:path";
import { afterAll, afterEach, beforeAll, beforeEach, describe, expect, it } from "vitest";
import { NOTICE_COLLAPSE_THRESHOLD } from "../../src/lib/render/index.js";
import { runCli } from "../helpers/runcli";
import { cleanup, freshTmpDir } from "../helpers/tmpdir";

const SKIP_COUNT = NOTICE_COLLAPSE_THRESHOLD + 5;

/**
 * A composite whose only example is JSX-bearing (ADR-0026): the regex
 * regenerator can't reproduce it, so the generated-integrity check skips it and
 * names it for hand review. Ships an existing `@generated` showcase so the
 * planner reaches the skip branch instead of treating the companion as missing.
 */
async function addJsxSkippedComponent(dir: string, name: string): Promise<void> {
	const Name = name[0].toUpperCase() + name.slice(1);
	await writeFile(
		join(dir, "design-system", "composites", `${name}.tsx`),
		[
			`import { Command } from "cmdk";`,
			`export const meta = {`,
			`  kind: "composite" as const,`,
			`  examples: [`,
			`    { name: "composed", props: { children: <Command><Command.Input /></Command> } },`,
			`  ],`,
			`};`,
			`export function ${Name}() { return null; }`,
			``,
		].join("\n"),
	);
	await writeFile(
		join(dir, "design-system", "composites", `${name}.showcase.tsx`),
		`// @generated by claude-ds — do not edit. Source: ${name}.tsx meta block.\nimport React from "react";\nimport { ${Name} } from "./${name}";\nexport default function ${Name}Showcase() { return <${Name} children={<div />} />; }\n`,
	);
}

/** Build the shared post-adopt fixture once: scaffold + SKIP_COUNT JSX skips. */
let template: string;

beforeAll(async () => {
	template = await freshTmpDir("claude-ds-agg-template-");
	const r = await runCli(["adopt", "--pack", "next-react", "--yes"], { cwd: template });
	if (r.code !== 0) throw new Error(`fixture adopt failed (code ${r.code}):\n${r.stderr}`);
	await mkdir(join(template, "design-system", "composites"), { recursive: true });
	for (let i = 0; i < SKIP_COUNT; i++) await addJsxSkippedComponent(template, `combo${i}`);
});

afterAll(async () => {
	await cleanup(template);
});

let dir: string;
beforeEach(async () => {
	dir = await freshTmpDir("claude-ds-agg-");
	await cp(template, dir, { recursive: true });
});
afterEach(async () => {
	await cleanup(dir);
});

function skipLines(stream: string): string[] {
	return stream.split("\n").filter((l) => l.includes("skipped") && l.includes("verify by hand"));
}

describe("defect 5: repeated same-kind skipped notices collapse (#534)", () => {
	it("collapses the per-file wall to one summary line + a --verbose hint", async () => {
		const r = await runCli(["reconform"], { cwd: dir });
		const lines = skipLines(r.stdout);
		// One collapsed line, not SKIP_COUNT identical-shaped lines (the defect).
		expect(lines).toHaveLength(1);
		expect(lines[0]).toContain(`${SKIP_COUNT} files skipped`);
		expect(lines[0]).toContain("--verbose");
	});

	it("--verbose restores the full per-file list", async () => {
		const r = await runCli(["reconform", "--verbose"], { cwd: dir });
		const lines = skipLines(r.stdout);
		expect(lines).toHaveLength(SKIP_COUNT);
		expect(lines.every((l) => l.includes("--verbose"))).toBe(false);
	});
});

/**
 * Mask the variable parts of a line (paths, counts) so two same-kind per-file
 * notices that differ only by their subject collapse to one template. A
 * template appearing past the threshold is a per-file wall that should have
 * been aggregated. The captured stream is non-TTY (identity color adapter), so
 * there is no ANSI to strip.
 */
function normalizeLine(line: string): string {
	return line
		.replace(/\b[\w@./-]+\.(tsx|ts|jsx|js|json|md|css|mjs|cjs)\b/g, "<path>")
		.replace(/\b\d+\b/g, "<n>")
		.trim();
}

function repeatedTemplates(stream: string): Array<{ template: string; count: number }> {
	const counts = new Map<string, number>();
	for (const raw of stream.split("\n")) {
		const t = normalizeLine(raw);
		if (t.length === 0) continue;
		counts.set(t, (counts.get(t) ?? 0) + 1);
	}
	return [...counts.entries()]
		.filter(([, n]) => n > NOTICE_COLLAPSE_THRESHOLD)
		.map(([template, count]) => ({ template, count }));
}

describe("no-repeated-line grammar invariant over command transcripts (#534)", () => {
	// Default (non-verbose) transcripts only: --verbose is the deliberate opt-in
	// to the full per-file list, so its repetition is by request, not a defect.
	const COMMANDS: string[][] = [["audit"], ["sync"], ["reconform"], ["doctor"], ["heal"]];

	for (const argv of COMMANDS) {
		it(`'${argv.join(" ")}' transcript has no un-aggregated per-file wall`, async () => {
			const r = await runCli(argv, { cwd: dir });
			const offenders = repeatedTemplates(`${r.stdout}\n${r.stderr}`);
			expect(offenders).toEqual([]);
		});
	}
});
