/**
 * The `regen-showcases` command (PRD #566, issue #568) — the CLI-canonical
 * showcase regenerator the pack shim invokes (ADR-0031).
 *
 * It owns the consumer-side directory walk (atoms/composites/references) and
 * delegates per-file emission to `generateShowcase` (the single emission path,
 * issue #567). These tests pin the walk + skip behaviour and assert the written
 * bytes are exactly what `generateShowcase` produces — so the command can never
 * drift from the canonical generator.
 */

import { existsSync } from "node:fs";
import { mkdir, mkdtemp, readFile, rm, writeFile } from "node:fs/promises";
import { tmpdir } from "node:os";
import { join } from "node:path";
import { afterAll, beforeAll, describe, expect, it } from "vitest";
import { generateShowcase } from "../../src/lib/showcase/generator.js";
import { runCli } from "../helpers/runcli";

const ATOM = [
	`import React from "react";`,
	`import { cva } from "class-variance-authority";`,
	`const buttonVariants = cva("base", {`,
	`  variants: { intent: { primary: "p", secondary: "s" }, size: { sm: "sm", md: "md" } },`,
	`  defaultVariants: { intent: "primary", size: "md" },`,
	`});`,
	`export function Button({ intent, size, ...props }: { intent?: "primary" | "secondary"; size?: "sm" | "md" }) {`,
	`  return <button className={buttonVariants({ intent, size })} {...props} />;`,
	`}`,
	`export const meta = { kind: "atom", examples: [{ name: "default", props: {} }], skip: [] };`,
	``,
].join("\n");

const REFERENCE = [
	`import React from "react";`,
	`export const meta = {`,
	`  kind: "reference" as const,`,
	`  title: "Design Tokens",`,
	`  render: () => <div className="tokens">swatches</div>,`,
	`};`,
	``,
].join("\n");

const NO_META = `import React from "react";\nexport function Plain() { return <div />; }\n`;

const NAMESPACE_ONLY = [
	`import React from "react";`,
	`function Line() { return <hr />; }`,
	`function Block() { return <div />; }`,
	`export const Skeleton = { Line, Block };`,
	`export const meta = { kind: "atom", examples: [{ name: "default", props: {} }], skip: [] };`,
	``,
].join("\n");

describe("regen-showcases command", () => {
	let dir: string;
	let result: Awaited<ReturnType<typeof runCli>>;

	beforeAll(async () => {
		dir = await mkdtemp(join(tmpdir(), "regen-showcases-"));
		await writeFile(join(dir, "package.json"), JSON.stringify({ name: "consumer" }, null, 2));
		const atoms = join(dir, "design-system", "atoms");
		const composites = join(dir, "design-system", "composites");
		const references = join(dir, "design-system", "references");
		await mkdir(atoms, { recursive: true });
		await mkdir(composites, { recursive: true });
		await mkdir(references, { recursive: true });

		await writeFile(join(atoms, "button.tsx"), ATOM);
		await writeFile(join(atoms, "plain.tsx"), NO_META);
		await writeFile(join(atoms, "skeleton.tsx"), NAMESPACE_ONLY);
		// companion + non-source files must be ignored by the walk
		await writeFile(join(atoms, "index.ts"), `export * from "./button";\n`);
		await writeFile(join(references, "tokens.tsx"), REFERENCE);

		result = await runCli(["regen-showcases"], { cwd: dir });
	});

	afterAll(async () => {
		await rm(dir, { recursive: true, force: true });
	});

	it("exits 0", () => {
		expect(result.code, result.stderr).toBe(0);
	});

	it("writes an atom showcase whose bytes equal generateShowcase output", async () => {
		const sourcePath = join(dir, "design-system", "atoms", "button.tsx");
		const showcasePath = join(dir, "design-system", "atoms", "button.showcase.tsx");
		expect(existsSync(showcasePath)).toBe(true);

		const written = await readFile(showcasePath, "utf8");
		const source = await readFile(sourcePath, "utf8");
		const canonical = generateShowcase({ filePath: sourcePath, source });
		expect(written).toBe(canonical.content);
		expect(written).toMatch(/^\/\/ @generated by claude-ds/);
	});

	it("emits a reference showcase via meta.render()", async () => {
		const showcasePath = join(dir, "design-system", "references", "tokens.showcase.tsx");
		expect(existsSync(showcasePath)).toBe(true);
		const written = await readFile(showcasePath, "utf8");
		expect(written).toMatch(/^\/\/ @generated by claude-ds/);
	});

	it("skips a no-meta source with GEN-000 and writes no companion", () => {
		expect(result.stderr).toMatch(/GEN-000/);
		expect(existsSync(join(dir, "design-system", "atoms", "plain.showcase.tsx"))).toBe(false);
	});

	it("skips a namespace-only export with GEN-069 and writes no companion", () => {
		expect(result.stderr).toMatch(/GEN-069/);
		expect(existsSync(join(dir, "design-system", "atoms", "skeleton.showcase.tsx"))).toBe(false);
	});

	it("ignores index.ts and never treats a companion as a source", () => {
		expect(existsSync(join(dir, "design-system", "atoms", "index.showcase.tsx"))).toBe(false);
	});

	it("is idempotent — a second run reproduces byte-identical companions", async () => {
		const path = join(dir, "design-system", "atoms", "button.showcase.tsx");
		const first = await readFile(path, "utf8");
		await runCli(["regen-showcases"], { cwd: dir });
		const second = await readFile(path, "utf8");
		expect(second).toBe(first);
	});
});
