// SOURCE OF TRUTH for the CVA component-attribution analyzer (issue #552).
//
// This module is mirrored byte-for-byte into the pack at
// `packs/next-react/files/scripts/lib/cva-analyzer.ts` so the showcase
// generator (a pack script that cannot import the CLI's src tree) and the
// CLI's CVA-consuming fixers share ONE implementation — not two parallel
// regex parsers that can drift (PRD #546). Edit this file; the mirror is
// regenerated by `scripts/sync-cva-analyzer.mjs` (run from `npm run build`)
// and pinned identical by `tests/unit/cva-analyzer-mirror.test.ts`.
//
// The TypeScript compiler module is injected (never imported here) so the
// same source runs in both contexts: the CLI passes its own `typescript`
// dependency; the pack script passes the consumer's runtime-resolved one.
// Analysis is purely syntactic (a single `createSourceFile`, no type
// checker), which keeps it cheap and portable.

import type * as TS from "typescript";

/** A variant axis with its value type. */
export type CvaAxis =
	// A string-union axis (`size: { sm, md, lg }`) — emitters render its values
	// as JSX attributes.
	| { kind: "enum"; values: string[] }
	// A boolean axis (`invalid: { true, false }`) — emitters render `{true}` /
	// `{false}` JSX expressions, never the strings "true"/"false".
	| { kind: "boolean" };

/** The CVA variant surface attributed to one exported component. */
export interface ComponentCva {
	/** Variant axes, keyed by axis name (the settable prop). */
	axes: Record<string, CvaAxis>;
	/** Default variant selections, typed (string for enum axes, boolean for boolean axes). */
	defaultVariants: Record<string, string | boolean>;
}

/**
 * Per-component CVA attribution for one source file, keyed by exported
 * component name. A component appears only when it consumes at least one
 * `cva()`; a `cva()` consumed solely by non-exported sub-elements is
 * attributed to no one and is therefore absent from every entry.
 */
export type CvaAttribution = Record<string, ComponentCva>;

interface CvaConfig {
	axes: Record<string, CvaAxis>;
	defaultVariants: Record<string, string | boolean>;
}

/**
 * Analyze one atom/composite source file and return, per exported component,
 * the variant axes it consumes (with typed values) and its default variants.
 *
 * Attribution walks the AST: a `cva()` result belongs to the exported
 * component whose props include `VariantProps<typeof thatCva>` or that applies
 * it in its own JSX (`thatCva(...)`). A `cva()` consumed by multiple exported
 * components is attributed to each.
 */
export function analyzeCvaComponents(
	ts: typeof TS,
	source: string,
	fileName = "component.tsx",
): CvaAttribution {
	if (!source.includes("cva(")) return {};

	const sf = ts.createSourceFile(fileName, source, ts.ScriptTarget.Latest, true, ts.ScriptKind.TSX);

	const cvaDefs = collectCvaDefs(ts, sf);
	if (cvaDefs.size === 0) return {};
	const cvaNames = new Set(cvaDefs.keys());

	const typeDecls = collectTypeDecls(ts, sf);
	const exportedNames = collectExportedNames(ts, sf);

	const result: CvaAttribution = {};
	for (const component of collectComponents(ts, sf, exportedNames)) {
		const consumed = new Set<string>();
		for (const name of consumedViaProps(ts, component.firstParamType, cvaNames, typeDecls)) {
			consumed.add(name);
		}
		for (const name of consumedViaBody(ts, component.node, cvaNames)) {
			consumed.add(name);
		}
		if (consumed.size === 0) continue;

		const axes: Record<string, CvaAxis> = {};
		const defaultVariants: Record<string, string | boolean> = {};
		for (const cvaName of consumed) {
			const config = cvaDefs.get(cvaName);
			if (!config) continue;
			Object.assign(axes, config.axes);
			Object.assign(defaultVariants, config.defaultVariants);
		}
		if (Object.keys(axes).length > 0) result[component.name] = { axes, defaultVariants };
	}
	return result;
}

// ── cva() definitions ─────────────────────────────────────────────────────────

function collectCvaDefs(ts: typeof TS, sf: TS.SourceFile): Map<string, CvaConfig> {
	const defs = new Map<string, CvaConfig>();
	const visit = (node: TS.Node): void => {
		if (
			ts.isVariableDeclaration(node) &&
			ts.isIdentifier(node.name) &&
			node.initializer &&
			ts.isCallExpression(node.initializer) &&
			ts.isIdentifier(node.initializer.expression) &&
			node.initializer.expression.text === "cva"
		) {
			const config = parseCvaConfig(ts, sf, node.initializer);
			if (config) defs.set(node.name.text, config);
		}
		node.forEachChild(visit);
	};
	visit(sf);
	return defs;
}

function parseCvaConfig(
	ts: typeof TS,
	sf: TS.SourceFile,
	call: TS.CallExpression,
): CvaConfig | null {
	// cva(base?, { variants, defaultVariants }) — find the options object (the
	// argument carrying `variants`).
	const options = call.arguments.find(
		(arg): arg is TS.ObjectLiteralExpression =>
			ts.isObjectLiteralExpression(arg) && hasProperty(ts, arg, "variants"),
	);
	if (!options) return null;

	const variantsObj = getObjectProperty(ts, options, "variants");
	if (!variantsObj || !ts.isObjectLiteralExpression(variantsObj)) return null;

	const axes: Record<string, CvaAxis> = {};
	for (const prop of variantsObj.properties) {
		if (!ts.isPropertyAssignment(prop)) continue;
		const axisName = propName(ts, prop.name);
		if (axisName === null) continue;
		if (!ts.isObjectLiteralExpression(prop.initializer)) continue;

		const valueKeys: string[] = [];
		for (const valueProp of prop.initializer.properties) {
			const key = ts.isPropertyAssignment(valueProp)
				? propName(ts, valueProp.name)
				: ts.isShorthandPropertyAssignment(valueProp)
					? valueProp.name.text
					: null;
			if (key !== null) valueKeys.push(key);
		}
		if (valueKeys.length === 0) continue;

		axes[axisName] = isBooleanAxis(valueKeys)
			? { kind: "boolean" }
			: { kind: "enum", values: valueKeys };
	}
	if (Object.keys(axes).length === 0) return null;

	const defaultVariants: Record<string, string | boolean> = {};
	const defaultsObj = getObjectProperty(ts, options, "defaultVariants");
	if (defaultsObj && ts.isObjectLiteralExpression(defaultsObj)) {
		for (const prop of defaultsObj.properties) {
			if (!ts.isPropertyAssignment(prop)) continue;
			const axisName = propName(ts, prop.name);
			if (axisName === null) continue;
			const value = literalValue(ts, prop.initializer, sf);
			if (value !== undefined) defaultVariants[axisName] = value;
		}
	}

	return { axes, defaultVariants };
}

/** A CVA axis is boolean when its only value keys are `true` / `false`. */
function isBooleanAxis(keys: string[]): boolean {
	return keys.every((k) => k === "true" || k === "false") && keys.includes("true");
}

// ── type declarations ──────────────────────────────────────────────────────────

function collectTypeDecls(
	ts: typeof TS,
	sf: TS.SourceFile,
): Map<string, TS.InterfaceDeclaration | TS.TypeAliasDeclaration> {
	const decls = new Map<string, TS.InterfaceDeclaration | TS.TypeAliasDeclaration>();
	const visit = (node: TS.Node): void => {
		if (ts.isInterfaceDeclaration(node) || ts.isTypeAliasDeclaration(node)) {
			decls.set(node.name.text, node);
		}
		node.forEachChild(visit);
	};
	visit(sf);
	return decls;
}

// ── exported names ──────────────────────────────────────────────────────────────

function collectExportedNames(ts: typeof TS, sf: TS.SourceFile): Set<string> {
	const names = new Set<string>();
	for (const stmt of sf.statements) {
		if (ts.isFunctionDeclaration(stmt) && stmt.name && hasExportModifier(ts, stmt)) {
			names.add(stmt.name.text);
		} else if (ts.isVariableStatement(stmt) && hasExportModifier(ts, stmt)) {
			for (const decl of stmt.declarationList.declarations) {
				if (ts.isIdentifier(decl.name)) names.add(decl.name.text);
			}
		} else if (
			ts.isExportDeclaration(stmt) &&
			stmt.exportClause &&
			ts.isNamedExports(stmt.exportClause)
		) {
			for (const spec of stmt.exportClause.elements) names.add(spec.name.text);
		}
	}
	return names;
}

function hasExportModifier(ts: typeof TS, node: TS.HasModifiers): boolean {
	return (ts.getModifiers(node) ?? []).some((m) => m.kind === ts.SyntaxKind.ExportKeyword);
}

// ── exported components ─────────────────────────────────────────────────────────

interface ComponentDecl {
	name: string;
	node: TS.Node;
	firstParamType: TS.TypeNode | undefined;
}

function collectComponents(
	ts: typeof TS,
	sf: TS.SourceFile,
	exportedNames: Set<string>,
): ComponentDecl[] {
	const components: ComponentDecl[] = [];
	for (const stmt of sf.statements) {
		if (ts.isFunctionDeclaration(stmt) && stmt.name && isComponentName(stmt.name.text)) {
			if (!exportedNames.has(stmt.name.text)) continue;
			components.push({
				name: stmt.name.text,
				node: stmt,
				firstParamType: stmt.parameters[0]?.type,
			});
		} else if (ts.isVariableStatement(stmt)) {
			for (const decl of stmt.declarationList.declarations) {
				if (!ts.isIdentifier(decl.name) || !isComponentName(decl.name.text)) continue;
				if (!exportedNames.has(decl.name.text)) continue;
				if (!decl.initializer) continue;
				const fn = unwrapComponentFn(ts, decl.initializer);
				if (fn)
					components.push({
						name: decl.name.text,
						node: fn.node,
						firstParamType: fn.firstParamType,
					});
			}
		}
	}
	return components;
}

/**
 * Recover the component function from a variable initializer. A component is
 * either a bare arrow/function expression or one wrapped in a higher-order
 * component call — `forwardRef(...)` / `memo(...)` (bare or `React.`-qualified),
 * the dominant shadcn-style atom shape. Returns the inner function node (for
 * body-usage attribution) and its props type: the inner param annotation when
 * present, else the wrapper's props type argument (`forwardRef<Ref, Props>`).
 */
function unwrapComponentFn(
	ts: typeof TS,
	init: TS.Expression,
): { node: TS.Node; firstParamType: TS.TypeNode | undefined } | null {
	if (ts.isArrowFunction(init) || ts.isFunctionExpression(init)) {
		return { node: init, firstParamType: init.parameters[0]?.type };
	}
	if (ts.isCallExpression(init) && isHocName(ts, init.expression)) {
		const inner = init.arguments.find(
			(a): a is TS.ArrowFunction | TS.FunctionExpression =>
				ts.isArrowFunction(a) || ts.isFunctionExpression(a),
		);
		if (inner) {
			// forwardRef<Ref, Props>((props, ref) => …) carries the props type as its
			// SECOND type argument; the inner params are usually unannotated.
			const propsTypeArg = init.typeArguments?.[1];
			return { node: inner, firstParamType: inner.parameters[0]?.type ?? propsTypeArg };
		}
	}
	return null;
}

/** `forwardRef` / `memo`, bare or `React.`-qualified (matches the generator). */
function isHocName(ts: typeof TS, callee: TS.Expression): boolean {
	const HOCS = new Set(["forwardRef", "memo"]);
	if (ts.isIdentifier(callee)) return HOCS.has(callee.text);
	return (
		ts.isPropertyAccessExpression(callee) &&
		ts.isIdentifier(callee.expression) &&
		callee.expression.text === "React" &&
		HOCS.has(callee.name.text)
	);
}

/** A component is an exported declaration whose name is PascalCase. */
function isComponentName(name: string): boolean {
	return name.length > 0 && name[0] === name[0].toUpperCase() && name[0] !== name[0].toLowerCase();
}

// ── attribution: props type (VariantProps<typeof X>) ────────────────────────────

function consumedViaProps(
	ts: typeof TS,
	typeNode: TS.TypeNode | undefined,
	cvaNames: Set<string>,
	typeDecls: Map<string, TS.InterfaceDeclaration | TS.TypeAliasDeclaration>,
): Set<string> {
	const found = new Set<string>();
	if (!typeNode) return found;
	const seen = new Set<string>();

	const walk = (node: TS.Node): void => {
		if (ts.isTypeQueryNode(node)) {
			const name = leftmostIdentText(ts, node.exprName);
			if (name && cvaNames.has(name)) found.add(name);
		}
		if (ts.isTypeReferenceNode(node)) {
			const name = leftmostIdentText(ts, node.typeName);
			if (name && typeDecls.has(name) && !seen.has(name)) {
				seen.add(name);
				typeDecls.get(name)?.forEachChild(walk);
			}
		}
		node.forEachChild(walk);
	};
	walk(typeNode);
	return found;
}

// ── attribution: JSX body usage (X(...)) ────────────────────────────────────────

function consumedViaBody(ts: typeof TS, node: TS.Node, cvaNames: Set<string>): Set<string> {
	const found = new Set<string>();
	const walk = (n: TS.Node): void => {
		if (
			ts.isCallExpression(n) &&
			ts.isIdentifier(n.expression) &&
			cvaNames.has(n.expression.text)
		) {
			found.add(n.expression.text);
		}
		n.forEachChild(walk);
	};
	walk(node);
	return found;
}

// ── small AST helpers ───────────────────────────────────────────────────────────

function propName(ts: typeof TS, name: TS.PropertyName): string | null {
	if (ts.isIdentifier(name)) return name.text;
	if (ts.isStringLiteral(name)) return name.text;
	if (ts.isNumericLiteral(name)) return name.text;
	return null;
}

function hasProperty(ts: typeof TS, obj: TS.ObjectLiteralExpression, key: string): boolean {
	return obj.properties.some(
		(p) =>
			(ts.isPropertyAssignment(p) || ts.isShorthandPropertyAssignment(p)) &&
			propName(ts, p.name) === key,
	);
}

function getObjectProperty(
	ts: typeof TS,
	obj: TS.ObjectLiteralExpression,
	key: string,
): TS.Expression | null {
	for (const p of obj.properties) {
		if (ts.isPropertyAssignment(p) && propName(ts, p.name) === key) return p.initializer;
	}
	return null;
}

function literalValue(
	ts: typeof TS,
	node: TS.Expression,
	sf: TS.SourceFile,
): string | boolean | undefined {
	if (ts.isStringLiteral(node)) return node.text;
	if (node.kind === ts.SyntaxKind.TrueKeyword) return true;
	if (node.kind === ts.SyntaxKind.FalseKeyword) return false;
	if (ts.isNumericLiteral(node)) return node.text;
	if (ts.isNoSubstitutionTemplateLiteral(node)) return node.text;
	void sf;
	return undefined;
}

function leftmostIdentText(ts: typeof TS, name: TS.EntityName): string | null {
	let current: TS.EntityName = name;
	while (ts.isQualifiedName(current)) current = current.left;
	return ts.isIdentifier(current) ? current.text : null;
}
