/**
 * Unit tests for `planGeneratedIntegrityFixes` (sub-issue #228).
 *
 * The Op replaces the old `runGeneratedIntegrityCheck` direct-writer:
 *  - emits one `write` Change per drifted companion (GEN-001 / GEN-002),
 *  - exposes detected violations on its typed outcome (PRD #258) — surfacing
 *    through `RunReport.ops[i].outcome.violations` for caller-side scorecard
 *    + check-script stderr,
 *  - the `dryRun` param is gone — the caller picks `run()` mode.
 */

import { chmod, mkdir, readFile, writeFile } from "node:fs/promises";
import { join } from "node:path";
import { afterEach, beforeEach, describe, expect, it } from "vitest";
import { planGeneratedIntegrityFixes } from "../../../src/lib/checks/generated-integrity";
import type { Change } from "../../../src/lib/operation";
import type { ProjectContext } from "../../../src/lib/project";
import { run } from "../../../src/lib/runner";
import { makeFakeCtx } from "../../helpers/fake-ctx";
import { makeCfg, makeManifest } from "../../helpers/fixtures";
import { cleanup, freshTmpDir } from "../../helpers/tmpdir";

let cwd: string;
let packDir: string;
beforeEach(async () => {
	cwd = await freshTmpDir("gen-int-cwd-");
	packDir = await freshTmpDir("gen-int-pack-");
});
afterEach(async () => {
	await cleanup(cwd);
	await cleanup(packDir);
});

const baseCfg = makeCfg();

const emptyManifest = makeManifest();

const FMT_MARKER = "// fake-formatted";

/**
 * Fake stdin-aware formatter (issue #493): when invoked as a stdin filter it
 * echoes stdin then appends a marker line — a deterministic stand-in for the
 * consumer's canonical formatting. Installed at `<cwd>/node_modules/.bin/<name>`
 * so `resolveConsumerFormatter` finds it without a real biome/prettier install.
 */
async function installStdinFormatter(dir: string, name: string): Promise<void> {
	const binDir = join(dir, "node_modules", ".bin");
	await mkdir(binDir, { recursive: true });
	const script = [
		"#!/usr/bin/env bash",
		'for a in "$@"; do',
		'  case "$a" in',
		"    --stdin-file-path=*|--stdin-filepath) STDIN=1 ;;",
		"  esac",
		"done",
		'if [ -n "$STDIN" ]; then',
		"  cat",
		`  printf '\\n${FMT_MARKER}\\n'`,
		"  exit 0",
		"fi",
		"exit 0",
	].join("\n");
	const p = join(binDir, name);
	await writeFile(p, script, "utf8");
	await chmod(p, 0o755);
}

function makeCtx(): ProjectContext {
	return makeFakeCtx(cwd, {
		cfg: baseCfg,
		packDir,
		manifest: emptyManifest,
		exists: async () => false,
	});
}

const ATOM_WITH_META = [
	`import type { Meta } from "@/design-system/types/meta";`,
	`export const meta: Meta = { kind: "atom", examples: [{ name: "default", props: {} }] };`,
	`export function Tag() { return null; }`,
	``,
].join("\n");

describe("planGeneratedIntegrityFixes (sub-issue #228)", () => {
	it("emits no Change and no violations when the project has no design-system", async () => {
		const op = planGeneratedIntegrityFixes();
		const { changes, outcome } = await op.plan(makeCtx());
		expect(changes).toEqual([]);
		expect(outcome.violations).toEqual([]);
	});

	it("emits a write Change + GEN-001 violation when companion is missing @generated header", async () => {
		await mkdir(join(cwd, "design-system", "atoms"), { recursive: true });
		await writeFile(join(cwd, "design-system", "atoms", "tag.tsx"), ATOM_WITH_META);
		await writeFile(
			join(cwd, "design-system", "atoms", "tag.showcase.tsx"),
			`// hand-written stub\nexport default function TagShowcase() { return null; }\n`,
		);

		const op = planGeneratedIntegrityFixes();
		const { changes, outcome } = await op.plan(makeCtx());

		expect(changes).toHaveLength(1);
		const c = changes[0] as Extract<Change, { kind: "write" }>;
		expect(c.kind).toBe("write");
		expect(c.path).toBe("design-system/atoms/tag.showcase.tsx");
		expect(c.after.toString("utf8").startsWith("// @generated by claude-ds")).toBe(true);

		expect(outcome.violations).toHaveLength(1);
		expect(outcome.violations[0].ruleId).toBe("GEN-001");
		expect(outcome.violations[0].file).toBe("design-system/atoms/tag.showcase.tsx");
	});

	it("emits a write Change + GEN-002 violation when the regenerated content differs", async () => {
		await mkdir(join(cwd, "design-system", "atoms"), { recursive: true });
		await writeFile(join(cwd, "design-system", "atoms", "tag.tsx"), ATOM_WITH_META);
		// Has the @generated header but stale content.
		await writeFile(
			join(cwd, "design-system", "atoms", "tag.showcase.tsx"),
			`// @generated by claude-ds — do not edit. Source: tag.tsx meta block.\nexport default function StaleStub() { return null; }\n`,
		);

		const op = planGeneratedIntegrityFixes();
		const { changes, outcome } = await op.plan(makeCtx());

		expect(changes).toHaveLength(1);
		expect(outcome.violations).toHaveLength(1);
		expect(outcome.violations[0].ruleId).toBe("GEN-002");
	});

	it("emits nothing when companion matches regeneration", async () => {
		await mkdir(join(cwd, "design-system", "atoms"), { recursive: true });
		await writeFile(join(cwd, "design-system", "atoms", "tag.tsx"), ATOM_WITH_META);
		// Plan once to get the canonical content, then write that to disk before
		// re-planning — proves idempotence.
		const planOnly = planGeneratedIntegrityFixes();
		const seed = await planOnly.plan(makeCtx());
		// No companion on disk yet → seed is empty. Write a header-only stub that
		// will trigger regen to compute the canonical bytes.
		await writeFile(
			join(cwd, "design-system", "atoms", "tag.showcase.tsx"),
			`// @generated by claude-ds — placeholder\n`,
		);
		expect(seed.changes).toEqual([]);

		// First plan + apply.
		const op1 = planGeneratedIntegrityFixes();
		const report1 = await run(makeCtx(), [op1], "apply");
		expect((report1.ops[0].outcome as { violations: unknown[] }).violations.length).toBeGreaterThan(
			0,
		);

		// Second plan against the now-canonical disk → no Changes, no violations.
		const op2 = planGeneratedIntegrityFixes();
		const { changes, outcome } = await op2.plan(makeCtx());
		expect(changes).toEqual([]);
		expect(outcome.violations).toEqual([]);
	});

	it("completes a required prop via cross-example consensus in the regenerated showcase", async () => {
		// Crewops radio shape: `value` is required by an external package type
		// (invisible to the syntactic type walk), the third example is old-fixer
		// residue missing it, and combos are skip[]-suppressed. The regenerated
		// showcase must borrow `value` for the residue entry — emitting without
		// it is a guaranteed TS2741 in the consumer's verify gate.
		const radio = [
			`import { Radio as RadioPrimitive } from "@fake-ui/react/radio";`,
			`import { cva } from "class-variance-authority";`,
			`const radioVariants = cva("radio", {`,
			`  variants: { size: { sm: "s", default: "d" } },`,
			`  defaultVariants: { size: "default" },`,
			`});`,
			`type RadioProps = RadioPrimitive.Root.Props & { size?: "sm" | "default" };`,
			`export function Radio({ size, ...props }: RadioProps) { return <input className={radioVariants({ size })} {...props} />; }`,
			`export const meta = {`,
			`  kind: "atom" as const,`,
			`  examples: [`,
			`    { name: "size=default", props: { value: "lead-inspection" } },`,
			`    { name: "size=sm", props: { size: "sm", value: "lead-maintenance" } },`,
			`    { name: "default", props: { size: "default" } },`,
			`  ],`,
			`  skip: ["size=sm", "size=default"],`,
			`};`,
		].join("\n");
		await mkdir(join(cwd, "design-system", "atoms"), { recursive: true });
		await writeFile(join(cwd, "design-system", "atoms", "radio.tsx"), radio);
		await writeFile(
			join(cwd, "design-system", "atoms", "radio.showcase.tsx"),
			`// @generated by claude-ds — placeholder\n`,
		);

		const op = planGeneratedIntegrityFixes();
		const { changes } = await op.plan(makeCtx());
		expect(changes).toHaveLength(1);
		const content = (changes[0] as Extract<Change, { kind: "write" }>).after.toString("utf8");
		const renders = content.match(/<Radio /g) ?? [];
		const withValue = content.match(/<Radio [^>\n]*value="lead-/g) ?? [];
		expect(renders.length).toBeGreaterThanOrEqual(3);
		expect(withValue.length).toBe(renders.length);
	});

	it("does not false-positive (or clobber) on a JSX-bearing example (ADR-0026)", async () => {
		// A composed-widget example authors the assembled JSX in props.children.
		// The whole-array JSON.parse used to throw on it, drop every example, and
		// regenerate a stub that would CLOBBER the real AST-generated showcase — a
		// "never break a consumer" violation. Per-entry parsing flags the JSX entry
		// and the file is skipped from comparison: no violation, no Change.
		const jsxAtom = [
			`import type { Meta } from "@/design-system/types/meta";`,
			`import { Command } from "cmdk";`,
			`export const meta: Meta = {`,
			`  kind: "composite",`,
			`  role: "combobox",`,
			`  examples: [`,
			`    { name: "sm", props: { size: "sm" } },`,
			`    { name: "composed", props: { children: <Command><Command.Input /></Command> } },`,
			`  ],`,
			`};`,
			`export function Combobox() { return null; }`,
			``,
		].join("\n");
		await mkdir(join(cwd, "design-system", "composites"), { recursive: true });
		await writeFile(join(cwd, "design-system", "composites", "combobox.tsx"), jsxAtom);
		// A real (non-stub) companion sits on disk with the canonical @generated header.
		await writeFile(
			join(cwd, "design-system", "composites", "combobox.showcase.tsx"),
			`// @generated by claude-ds — do not edit. Source: combobox.tsx meta block.\nimport React from "react";\nimport { Combobox } from "./combobox";\nexport default function ComboboxShowcase() { return <Combobox children={<div />} />; }\n`,
		);

		const op = planGeneratedIntegrityFixes();
		const { changes, outcome } = await op.plan(makeCtx());

		expect(changes).toEqual([]);
		expect(outcome.violations).toEqual([]);
	});

	it("names a JSX-skipped companion in outcome.skipped so it can't hide a broken showcase (#509)", async () => {
		// The ADR-0026 skip is silent today: a JSX-bearing example is excluded
		// from comparison (the regex regenerator can't reproduce AST output), so a
		// drifted-but-skipped companion reads as clean. Surface the skip — name the
		// companion in `outcome.skipped` — so a subset of broken showcases can't
		// hide behind "all generated files clean."
		const jsxAtom = [
			`import type { Meta } from "@/design-system/types/meta";`,
			`import { Command } from "cmdk";`,
			`export const meta: Meta = {`,
			`  kind: "composite",`,
			`  role: "combobox",`,
			`  examples: [`,
			`    { name: "sm", props: { size: "sm" } },`,
			`    { name: "composed", props: { children: <Command><Command.Input /></Command> } },`,
			`  ],`,
			`};`,
			`export function Combobox() { return null; }`,
			``,
		].join("\n");
		await mkdir(join(cwd, "design-system", "composites"), { recursive: true });
		await writeFile(join(cwd, "design-system", "composites", "combobox.tsx"), jsxAtom);
		await writeFile(
			join(cwd, "design-system", "composites", "combobox.showcase.tsx"),
			`// @generated by claude-ds — do not edit. Source: combobox.tsx meta block.\nimport React from "react";\nimport { Combobox } from "./combobox";\nexport default function ComboboxShowcase() { return <Combobox children={<div />} />; }\n`,
		);

		const op = planGeneratedIntegrityFixes();
		const { changes, outcome } = await op.plan(makeCtx());

		// Still no Change / violation (skip ≠ repair), but the file is named.
		expect(changes).toEqual([]);
		expect(outcome.violations).toEqual([]);
		expect(outcome.skipped).toContain("design-system/composites/combobox.showcase.tsx");
	});

	it("does not flag a clean companion as skipped (skipped is empty when nothing is JSX-skipped) (#509)", async () => {
		await mkdir(join(cwd, "design-system", "atoms"), { recursive: true });
		await writeFile(join(cwd, "design-system", "atoms", "tag.tsx"), ATOM_WITH_META);

		const op = planGeneratedIntegrityFixes();
		const { outcome } = await op.plan(makeCtx());
		expect(outcome.skipped).toEqual([]);
	});

	it("does not GEN-002 a companion that matches the consumer-FORMATTED regeneration (#493)", async () => {
		await mkdir(join(cwd, "design-system", "atoms"), { recursive: true });
		await writeFile(join(cwd, "design-system", "atoms", "tag.tsx"), ATOM_WITH_META);

		// 1. Capture the canonical regeneration with no formatter configured.
		await writeFile(
			join(cwd, "design-system", "atoms", "tag.showcase.tsx"),
			`// @generated by claude-ds — do not edit. Source: tag.tsx meta block.\nexport default function Stale() { return null; }\n`,
		);
		const seed = await planGeneratedIntegrityFixes().plan(makeCtx());
		const canonical = (seed.changes[0] as Extract<Change, { kind: "write" }>).after.toString(
			"utf8",
		);

		// 2. Stand up a consumer formatter (fake, stdin-aware: appends a marker
		//    line) and write the consumer-formatted companion to disk.
		await installStdinFormatter(cwd, "biome");
		await writeFile(join(cwd, "biome.json"), "{}");
		const consumerFormatted = `${canonical}\n${FMT_MARKER}\n`;
		await writeFile(join(cwd, "design-system", "atoms", "tag.showcase.tsx"), consumerFormatted);

		// 3. The integrity check formats its regeneration the same way before
		//    comparing — so the formatting-only difference is no longer drift.
		const { changes, outcome } = await planGeneratedIntegrityFixes().plan(makeCtx());
		expect(outcome.violations).toEqual([]);
		expect(changes).toEqual([]);
	});

	it("applied via run() rewrites the companion to canonical bytes", async () => {
		await mkdir(join(cwd, "design-system", "atoms"), { recursive: true });
		await writeFile(join(cwd, "design-system", "atoms", "tag.tsx"), ATOM_WITH_META);
		await writeFile(
			join(cwd, "design-system", "atoms", "tag.showcase.tsx"),
			`// hand-written stub\nexport default function TagShowcase() { return null; }\n`,
		);

		const op = planGeneratedIntegrityFixes();
		await run(makeCtx(), [op], "apply");

		const after = await readFile(join(cwd, "design-system", "atoms", "tag.showcase.tsx"), "utf8");
		expect(after.startsWith("// @generated by claude-ds")).toBe(true);
	});
});
