/**
 * Unit tests for `planGeneratedIntegrityFixes` (sub-issue #228).
 *
 * The Op replaces the old `runGeneratedIntegrityCheck` direct-writer:
 *  - emits one `write` Change per drifted companion (GEN-001 / GEN-002),
 *  - exposes detected violations on its typed outcome (PRD #258) — surfacing
 *    through `RunReport.ops[i].outcome.violations` for caller-side scorecard
 *    + check-script stderr,
 *  - the `dryRun` param is gone — the caller picks `run()` mode.
 */

import { mkdir, readFile, writeFile } from "node:fs/promises";
import { join } from "node:path";
import { afterEach, beforeEach, describe, expect, it } from "vitest";
import { planGeneratedIntegrityFixes } from "../../../src/lib/checks/generated-integrity";
import type { Change } from "../../../src/lib/operation";
import type { ProjectContext } from "../../../src/lib/project";
import { run } from "../../../src/lib/runner";
import { makeFakeCtx } from "../../helpers/fake-ctx";
import { makeCfg, makeManifest } from "../../helpers/fixtures";
import { cleanup, freshTmpDir } from "../../helpers/tmpdir";

let cwd: string;
let packDir: string;
beforeEach(async () => {
	cwd = await freshTmpDir("gen-int-cwd-");
	packDir = await freshTmpDir("gen-int-pack-");
});
afterEach(async () => {
	await cleanup(cwd);
	await cleanup(packDir);
});

const baseCfg = makeCfg();

const emptyManifest = makeManifest();

function makeCtx(): ProjectContext {
	return makeFakeCtx(cwd, {
		cfg: baseCfg,
		packDir,
		manifest: emptyManifest,
		exists: async () => false,
	});
}

const ATOM_WITH_META = [
	`import type { Meta } from "@/design-system/types/meta";`,
	`export const meta: Meta = { kind: "atom", examples: [{ name: "default", props: {} }] };`,
	`export function Tag() { return null; }`,
	``,
].join("\n");

describe("planGeneratedIntegrityFixes (sub-issue #228)", () => {
	it("emits no Change and no violations when the project has no design-system", async () => {
		const op = planGeneratedIntegrityFixes();
		const { changes, outcome } = await op.plan(makeCtx());
		expect(changes).toEqual([]);
		expect(outcome.violations).toEqual([]);
	});

	it("emits a write Change + GEN-001 violation when companion is missing @generated header", async () => {
		await mkdir(join(cwd, "design-system", "atoms"), { recursive: true });
		await writeFile(join(cwd, "design-system", "atoms", "tag.tsx"), ATOM_WITH_META);
		await writeFile(
			join(cwd, "design-system", "atoms", "tag.showcase.tsx"),
			`// hand-written stub\nexport default function TagShowcase() { return null; }\n`,
		);

		const op = planGeneratedIntegrityFixes();
		const { changes, outcome } = await op.plan(makeCtx());

		expect(changes).toHaveLength(1);
		const c = changes[0] as Extract<Change, { kind: "write" }>;
		expect(c.kind).toBe("write");
		expect(c.path).toBe("design-system/atoms/tag.showcase.tsx");
		expect(c.after.toString("utf8").startsWith("// @generated by claude-ds")).toBe(true);

		expect(outcome.violations).toHaveLength(1);
		expect(outcome.violations[0].ruleId).toBe("GEN-001");
		expect(outcome.violations[0].file).toBe("design-system/atoms/tag.showcase.tsx");
	});

	it("emits a write Change + GEN-002 violation when the regenerated content differs", async () => {
		await mkdir(join(cwd, "design-system", "atoms"), { recursive: true });
		await writeFile(join(cwd, "design-system", "atoms", "tag.tsx"), ATOM_WITH_META);
		// Has the @generated header but stale content.
		await writeFile(
			join(cwd, "design-system", "atoms", "tag.showcase.tsx"),
			`// @generated by claude-ds — do not edit. Source: tag.tsx meta block.\nexport default function StaleStub() { return null; }\n`,
		);

		const op = planGeneratedIntegrityFixes();
		const { changes, outcome } = await op.plan(makeCtx());

		expect(changes).toHaveLength(1);
		expect(outcome.violations).toHaveLength(1);
		expect(outcome.violations[0].ruleId).toBe("GEN-002");
	});

	it("emits nothing when companion matches regeneration", async () => {
		await mkdir(join(cwd, "design-system", "atoms"), { recursive: true });
		await writeFile(join(cwd, "design-system", "atoms", "tag.tsx"), ATOM_WITH_META);
		// Plan once to get the canonical content, then write that to disk before
		// re-planning — proves idempotence.
		const planOnly = planGeneratedIntegrityFixes();
		const seed = await planOnly.plan(makeCtx());
		// No companion on disk yet → seed is empty. Write a header-only stub that
		// will trigger regen to compute the canonical bytes.
		await writeFile(
			join(cwd, "design-system", "atoms", "tag.showcase.tsx"),
			`// @generated by claude-ds — placeholder\n`,
		);
		expect(seed.changes).toEqual([]);

		// First plan + apply.
		const op1 = planGeneratedIntegrityFixes();
		const report1 = await run(makeCtx(), [op1], "apply");
		expect((report1.ops[0].outcome as { violations: unknown[] }).violations.length).toBeGreaterThan(
			0,
		);

		// Second plan against the now-canonical disk → no Changes, no violations.
		const op2 = planGeneratedIntegrityFixes();
		const { changes, outcome } = await op2.plan(makeCtx());
		expect(changes).toEqual([]);
		expect(outcome.violations).toEqual([]);
	});

	it("does not false-positive (or clobber) on a JSX-bearing example (ADR-0026)", async () => {
		// A composed-widget example authors the assembled JSX in props.children.
		// The whole-array JSON.parse used to throw on it, drop every example, and
		// regenerate a stub that would CLOBBER the real AST-generated showcase — a
		// "never break a consumer" violation. Per-entry parsing flags the JSX entry
		// and the file is skipped from comparison: no violation, no Change.
		const jsxAtom = [
			`import type { Meta } from "@/design-system/types/meta";`,
			`import { Command } from "cmdk";`,
			`export const meta: Meta = {`,
			`  kind: "composite",`,
			`  role: "combobox",`,
			`  examples: [`,
			`    { name: "sm", props: { size: "sm" } },`,
			`    { name: "composed", props: { children: <Command><Command.Input /></Command> } },`,
			`  ],`,
			`};`,
			`export function Combobox() { return null; }`,
			``,
		].join("\n");
		await mkdir(join(cwd, "design-system", "composites"), { recursive: true });
		await writeFile(join(cwd, "design-system", "composites", "combobox.tsx"), jsxAtom);
		// A real (non-stub) companion sits on disk with the canonical @generated header.
		await writeFile(
			join(cwd, "design-system", "composites", "combobox.showcase.tsx"),
			`// @generated by claude-ds — do not edit. Source: combobox.tsx meta block.\nimport React from "react";\nimport { Combobox } from "./combobox";\nexport default function ComboboxShowcase() { return <Combobox children={<div />} />; }\n`,
		);

		const op = planGeneratedIntegrityFixes();
		const { changes, outcome } = await op.plan(makeCtx());

		expect(changes).toEqual([]);
		expect(outcome.violations).toEqual([]);
	});

	it("applied via run() rewrites the companion to canonical bytes", async () => {
		await mkdir(join(cwd, "design-system", "atoms"), { recursive: true });
		await writeFile(join(cwd, "design-system", "atoms", "tag.tsx"), ATOM_WITH_META);
		await writeFile(
			join(cwd, "design-system", "atoms", "tag.showcase.tsx"),
			`// hand-written stub\nexport default function TagShowcase() { return null; }\n`,
		);

		const op = planGeneratedIntegrityFixes();
		await run(makeCtx(), [op], "apply");

		const after = await readFile(join(cwd, "design-system", "atoms", "tag.showcase.tsx"), "utf8");
		expect(after.startsWith("// @generated by claude-ds")).toBe(true);
	});
});
